const {test,expect}=require('@playwright/test');
const fixture=require('./ui-fixture.cjs');
async function load(page){await page.goto('/');await expect(page.locator('.story-viewbar')).toBeVisible();await page.locator('#import-file').setInputFiles({name:'drawer-story.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture()))});await page.locator('[data-action=accept-import]').click();}
const snapshot=page=>page.evaluate(()=>{const d=CounterplotTutorial.snapshot();return d.projects.find(p=>p.id===d.active);});
async function stash(page,id){await page.locator(`[data-drag=node][data-drag-id=${id}]`).click();await page.locator('#dialog [data-action=stash-node]').click();await expect(page.locator(`[data-node=${id}]`)).toHaveCount(0);}
async function pointerDrag(page,source,target){await source.scrollIntoViewIfNeeded();const a=await source.boundingBox(),b=await target.boundingBox();await source.dispatchEvent('pointerdown',{button:0,pointerId:77,clientX:a.x+a.width/2,clientY:a.y+a.height/2,pointerType:'touch'});await page.locator('body').dispatchEvent('pointermove',{pointerId:77,clientX:a.x+a.width/2+15,clientY:a.y+a.height/2,pointerType:'touch'});await page.locator('body').dispatchEvent('pointermove',{pointerId:77,clientX:b.x+b.width/2,clientY:b.y+b.height/2,pointerType:'touch'});await page.locator('body').dispatchEvent('pointerup',{pointerId:77,clientX:b.x+b.width/2,clientY:b.y+b.height/2,pointerType:'touch'});}
test('whole branches can be set aside, survive reload, and return with history and links intact',async({page})=>{
 await load(page);const before=await snapshot(page);await stash(page,'ui-node-0');await page.locator('.tray-drawer').click();await expect(page.locator('.drawer-card')).toHaveCount(1);await expect(page.locator('.drawer-card')).toContainText('1 nested piece');await expect(page.locator('#save-status')).toContainText('Saved on this device');await page.reload();await page.locator('.tray-drawer').click();await page.getByRole('button',{name:'Put back',exact:true}).click();const after=await snapshot(page);for(const k of ['nodes','characters','world','timeline','readingSequence','readingOrder'])expect(after[k]).toEqual(before[k]);await page.locator('.topbar [data-action=undo]').click();expect((await snapshot(page)).nodes).toHaveLength(0);await page.locator('.topbar [data-action=redo]').click();expect((await snapshot(page)).nodes).toHaveLength(2);
});
test('pointer dragging supports storage and precise placement out of the open Drawer',async({page})=>{
 await load(page);await pointerDrag(page,page.locator('[data-drag=node][data-drag-id=ui-node-1]'),page.locator('.tray-drawer'));await expect(page.locator('[data-node=ui-node-1]')).toHaveCount(0);await page.waitForTimeout(250);await page.locator('.tray-drawer').click();const target=page.locator('.outline-tail');await target.evaluate(el=>el.scrollIntoView({block:'center',behavior:'instant'}));await pointerDrag(page,page.locator('[data-drag=drawer]'),target);await expect(page.locator('[data-node=ui-node-1]')).toBeVisible();expect((await snapshot(page)).nodes.find(n=>n.id==='ui-node-1').parentId).toBe('');await expect(page.locator('#piece-drawer')).toHaveCount(0);
});
test('native drag and drop can store and restore a thread without opening a modal',async({page})=>{
 await load(page);await page.evaluate(()=>{const source=document.querySelector('[data-drag=node][data-drag-id=ui-node-0]'),target=document.querySelector('.tray-drawer'),dt=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));});await expect(page.locator('[data-node=ui-node-0]')).toHaveCount(0);await page.waitForTimeout(200);await page.locator('.tray-drawer').click();await page.evaluate(()=>{const source=document.querySelector('[data-drag=drawer]'),target=document.querySelector('.outline-tail'),dt=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:dt}));target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,dataTransfer:dt}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));});await expect(page.locator('[data-node=ui-node-0]')).toBeVisible();await expect(page.locator('[data-node=ui-node-1]')).toBeVisible();await expect(page.locator('#dialog')).not.toBeVisible();
});
test('Empty archive never consumes Drawer pieces and keyboard placement remains available',async({page})=>{
 await load(page);await stash(page,'ui-node-1');await page.locator('[data-action=archive-node][data-id=ui-node-0]').click();await page.locator('.tray [data-nav=archive]').click();await expect(page.locator('.archive-row')).toHaveCount(1);await page.getByRole('button',{name:'Empty archive',exact:true}).click();await page.locator('#dialog [type=submit]').click();expect((await snapshot(page)).archive.filter(a=>a.storage==='drawer')).toHaveLength(1);await page.locator('[data-nav=outline]').first().click();await page.locator('.tray-drawer').click();await page.locator('[data-drag=drawer]').click();await page.locator('#dialog [type=submit]').click();await expect(page.locator('[data-node=ui-node-1]')).toBeVisible();
});
test('Drawer and toolbar fit small screens, keep existing tray pieces accessible, and expose labelled tools',async({page})=>{
 await load(page);for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});await page.locator('.tray-drawer').click();const bounds=await page.locator('.tray').evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,scroll:el.scrollWidth,width:el.clientWidth};});expect(bounds.left).toBeGreaterThanOrEqual(0);expect(bounds.right).toBeLessThanOrEqual(width+1);expect(bounds.scroll).toBeLessThanOrEqual(bounds.width+1);await expect(page.locator('.tray-piece')).toHaveCount(5);await expect(page.locator('.tray-trash')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);const box=await page.locator('#piece-drawer').boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width);await page.keyboard.press('Escape');await expect(page.locator('.tray-drawer')).toBeFocused();await page.locator('.story-tools-menu>summary').click();await expect(page.locator('.story-tools-menu').getByRole('button',{name:'Pictures & references',exact:true})).toBeVisible();const menu=await page.locator('.story-tools-popover').boundingBox();expect(menu.x).toBeGreaterThanOrEqual(0);expect(menu.x+menu.width).toBeLessThanOrEqual(width+1);await page.keyboard.press('Escape');}
 await page.locator('.story-tools-menu>summary').click();await page.getByRole('button',{name:'Story settings',exact:true}).click();await expect(page.locator('#dialog')).toBeVisible();await expect(page.locator('.story-tools-menu')).not.toHaveAttribute('open','');
});
test('cancelling a drag leaves a piece in Drawer, and search finds stored content',async({page})=>{
 await load(page);await stash(page,'ui-node-0');await page.locator('.tray-drawer').click();const source=page.locator('[data-drag=drawer]'),r=await source.boundingBox();await source.dispatchEvent('pointerdown',{button:0,pointerId:3,clientX:r.x,clientY:r.y});await page.locator('body').dispatchEvent('pointermove',{pointerId:3,clientX:r.x+20,clientY:r.y});await page.locator('body').dispatchEvent('pointercancel',{pointerId:3});await expect(page.locator('#piece-drawer')).toBeVisible();expect((await snapshot(page)).nodes).toHaveLength(0);await page.keyboard.press('Escape');await page.locator('[data-action=search]').click();await page.locator('#story-search').fill('Discovery');await expect(page.locator('.search-result').first()).toContainText('Drawer');await page.locator('.search-result').first().click();await expect(page.locator('#piece-drawer')).toBeVisible();
});
