const {test,expect}=require('@playwright/test');
const fixture=require('./ui-fixture.cjs');
async function load(page){const d=fixture(),p=d.projects[0];p.plots=Array.from({length:10},(_,i)=>({id:i?'plot-'+i:'ui-plot',label:String.fromCharCode(65+i),title:i===0?'The mission':i===1?'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum tincidunt leo, eu hendrerit quam maximus ut. Aliquam vitae dapibus urna. Duis pharetra dui et lectus ornare, ut pellentesque libero volutpat. Nunc a ultrices elit, et tristique leo. Etiam hendrerit eleifend orci sed tincidunt':'A long plot title about the mission and its consequences '+i,notes:''}));await page.goto('/');await expect(page.locator('.story-viewbar')).toBeVisible();await page.locator('#import-file').setInputFiles({name:'plots.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(d))});await page.locator('[data-action=accept-import]').click();await expect(page.locator('#dialog')).not.toBeVisible();}
test('plot strip scrolls and fades while Collapse all stays fixed on its row',async({page},testInfo)=>{
 await load(page);for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});const nav=page.getByRole('navigation',{name:'Plot views'}),collapse=page.locator('.plot-collapse button');await expect(collapse).toHaveText('Collapse all');await expect(page.locator('[data-action=collapse-all]')).toHaveCount(1);let boxes;await expect.poll(async()=>{boxes=await page.evaluate(()=>['.plot-scroll nav','.plot-collapse button'].map(selector=>{const el=document.querySelector(selector);if(!el)return null;const r=el.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};}));return boxes.every(r=>r&&r.width>0&&r.height>0);}).toBe(true);const [n,c]=boxes;expect(c.x).toBeGreaterThanOrEqual(n.x+n.width);expect(Math.abs(c.y+c.height/2-(n.y+n.height/2))).toBeLessThan(10);await nav.evaluate(el=>{el.scrollLeft=0;});await expect(page.locator('.plot-scroll')).toHaveClass(/can-scroll-right/);await nav.evaluate(el=>{el.scrollLeft=el.scrollWidth;});await expect(page.locator('.plot-scroll')).toHaveClass(/can-scroll-left/);await expect(page.locator('.plot-scroll')).not.toHaveClass(/can-scroll-right/);await expect.poll(async()=>{const box=await collapse.boundingBox();return box?.x;}).toBe(c.x);await collapse.click();await expect(collapse).toHaveText('Expand all');expect(await nav.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);await collapse.click();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);}
 await page.screenshot({path:testInfo.outputPath('plot-strip.png'),fullPage:false});
});
test('plot management uses one title row with separate nonoverlapping actions',async({page},testInfo)=>{
 await load(page);await page.getByRole('button',{name:'Manage plots',exact:true}).click();await expect(page.locator('#dialog .plot-row')).toHaveCount(10);await expect(page.locator('#dialog .history-row')).toHaveCount(0);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});const rows=page.locator('.plot-row');expect(await rows.evaluateAll(rows=>rows.every(row=>{const title=row.querySelector('strong').getBoundingClientRect(),actions=[...row.querySelectorAll('.btn')].map(x=>x.getBoundingClientRect());return row.scrollWidth<=row.clientWidth+1&&actions.every(a=>a.left>=title.right||a.right<=title.left||a.top>=title.bottom||a.bottom<=title.top);}))).toBeTruthy();}
 await page.screenshot({path:testInfo.outputPath('manage-plots.png'),fullPage:false});await page.locator('.plot-row').first().getByRole('button',{name:'Cast roles',exact:true}).click();await expect(page.getByRole('heading',{name:'A · The mission',exact:true})).toBeVisible();
});
