const {test,expect}=require('@playwright/test');
const fixture=require('./ui-fixture.cjs');
async function load(page){const data=fixture(),p=data.projects[0];p.nodes[0].goal='Discover the truth';p.nodes[0].action='Take the pearl';p.nodes[0].gain='A clue';p.nodes[0].cost='A new enemy';p.timeline[0].storyDate='1929-03-12';await page.goto('/');await expect(page.locator('.story-viewbar')).toBeVisible();await page.locator('#import-file').setInputFiles({name:'story.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('[data-action=accept-import]').click();return p;}
async function view(page,name){await page.getByRole('tab',{name,exact:true}).click();}
const snapshot=page=>page.evaluate(()=>{const w=CounterplotTutorial.snapshot();return w.projects.find(p=>p.id===w.active);});
test('Sequence includes closings, edits the correct edge, and preserves moved moments on reload',async({page})=>{
 await load(page);const before=await snapshot(page);await view(page,'Sequence');await expect(page.locator('.moment-card')).toHaveCount(3);const closing=page.locator('[data-moment-key="ui-node-0:close"]');await expect(closing).toContainText('The scene leaves a new question.');await closing.getByRole('button',{name:'Edit closing',exact:true}).click();await page.locator('[name=closing]').fill('She escapes with the pearl.');await page.locator('#dialog [type=submit]').click();await expect(closing).toContainText('She escapes with the pearl.');await closing.getByRole('button',{name:'Move earlier',exact:true}).click();const after=await snapshot(page);expect(after.readingSequence).toEqual(['ui-node-0:open','ui-node-0:close','ui-node-1:open']);expect(after.timeline).toEqual(before.timeline);expect(after.nodes.map(n=>n.parentId)).toEqual(before.nodes.map(n=>n.parentId));expect(after.nodes[0].opening).toEqual(before.nodes[0].opening);await page.locator('.topbar [data-action=undo]').click();expect((await snapshot(page)).readingSequence).toEqual(before.readingSequence);await page.locator('.topbar [data-action=redo]').click();await expect(page.locator('#save-status')).toContainText('Saved on this device');await page.reload();await view(page,'Sequence');expect((await snapshot(page)).readingSequence).toEqual(after.readingSequence);await expect(page.locator('.moment-close')).toContainText('She escapes with the pearl.');
});
test('Sequence drag moves a closing independently of outline and chronology',async({page})=>{
 await load(page);await view(page,'Sequence');const before=await snapshot(page);const source=page.locator('[data-moment-key="ui-node-0:close"] [draggable=true]'),target=page.locator('[data-moment-key="ui-node-1:open"]');const transfer=await page.evaluateHandle(()=>new DataTransfer());await source.dispatchEvent('dragstart',{dataTransfer:transfer});await target.dispatchEvent('dragover',{dataTransfer:transfer});await target.dispatchEvent('drop',{dataTransfer:transfer});const after=await snapshot(page);expect(after.readingSequence[1]).toBe('ui-node-0:close');expect(after.timeline).toEqual(before.timeline);expect(after.nodes).toEqual(before.nodes);
});
test('Chronology groups dates without changing history and reorders only in story order',async({page})=>{
 await load(page);await view(page,'Chronology');const before=await snapshot(page);await expect(page.locator('.chronology-track')).toBeVisible();await expect(page.locator('.timeline-moment')).toHaveCount(3);await page.getByRole('button',{name:'Group by date',exact:true}).click();await expect(page.locator('.timeline-date')).toHaveText(['1929-03-12','Undated']);await expect(page.locator('.chronology-track [data-sequence-drag]')).toHaveCount(0);await expect(page.locator('.chronology-track [data-action=sequence-nudge]')).toHaveCount(0);expect((await snapshot(page)).timeline).toEqual(before.timeline);await page.getByRole('button',{name:'Story order',exact:true}).click();await page.locator('.timeline-moment').first().getByRole('button',{name:'Move later',exact:true}).click();const after=await snapshot(page);expect(after.timeline).not.toEqual(before.timeline);expect(after.readingSequence).toEqual(before.readingSequence);await page.locator('.topbar [data-action=undo]').click();expect((await snapshot(page)).timeline).toEqual(before.timeline);
});
test('Choices groups decisions and places scene craft beside the content on desktop',async({page})=>{
 await load(page);await view(page,'Choices');const card=page.locator('.choice-card').first();await expect(card.locator('dt')).toHaveText(['Goal','Choice','Gain','Cost']);await page.setViewportSize({width:1440,height:1000});const [content,action]=await Promise.all([card.locator('.choice-content').boundingBox(),card.locator('.choice-action').boundingBox()]);expect(action.x).toBeGreaterThanOrEqual(content.x+content.width);await card.getByRole('button',{name:'Open scene craft'}).click();await expect(page.getByRole('tab',{name:'Refine',exact:true})).toHaveAttribute('aria-selected','true');await page.getByText('Additional craft notes',{exact:true}).click();await expect(page.locator('.refine-form [name=goal]')).toHaveValue('Discover the truth');
});
test('story view cards fit narrow screens and the floating bar stays visible in every view',async({page})=>{
 await load(page);for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const name of ['Sequence','Chronology','Choices']){await view(page,name);await expect(page.locator('.tray[aria-label="MICE building pieces"]')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);const cards=page.locator('.moment-card,.choice-card');expect(await cards.evaluateAll(xs=>xs.every(e=>e.scrollWidth<=e.clientWidth+2))).toBeTruthy();}}
});

test('Read shows an undrafted plan including closings, and keeps draft prose separate',async({page})=>{
 const data=fixture(),p=data.projects[0];for(const n of p.nodes)n.prose='';p.nodes[0].opening='The question opens.';p.nodes[1].opening='A clue arrives.';p.nodes[0].closing='The question is answered.';
 await page.goto('/');await page.locator('#import-file').setInputFiles({name:'plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('[data-action=accept-import]').click();await view(page,'Read');
 await expect(page.locator('.manuscript-prose')).toHaveText(['The question opens.','A clue arrives.','The question is answered.']);
 await expect(page.getByRole('button',{name:'Plan',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.locator('[data-reading-moment="ui-node-0:close"] button').click();await expect(page.getByLabel('Closing plan',{exact:true})).toHaveValue('The question is answered.');
 await view(page,'Read');await page.getByRole('button',{name:'Draft',exact:true}).click();await expect(page.locator('.reading-empty')).toContainText('No draft prose');await page.getByRole('button',{name:'Read the plan',exact:true}).click();await expect(page.locator('.manuscript-prose')).toHaveCount(3);
 await view(page,'Write');await page.locator('.moment-switcher [data-edge=close]').click();await page.getByLabel('Closing draft prose').fill('She finally understood.');await view(page,'Read');await page.getByRole('button',{name:'Draft',exact:true}).click();await expect(page.locator('.manuscript-prose')).toHaveText(['She finally understood.']);
 await page.reload();await view(page,'Read');await expect(page.getByRole('button',{name:'Draft',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.locator('.manuscript-prose')).toHaveText(['She finally understood.']);
});
