const {test,expect}=require('@playwright/test');
const fixture=require('./ui-fixture.cjs');
async function load(page){const data=fixture(),p=data.projects[0];p.drafts=[{id:'draft-moment',kind:'form',title:'A moment in the story',form:'moment',context:{kind:'moment',id:p.timeline[0].key},values:[['title','A clue before midnight'],['storyDate','1929-03-12'],['storyEndDate','']],updatedAt:'2026-10-05T12:00:00Z'},{id:'draft-scene',kind:'scene',title:'A scene to keep',draft:{title:'Across the river',notes:'She carries the pearl across the river.'}},{id:'draft-missing',kind:'form',title:'Missing thread',form:'sequence-closing',context:{kind:'sequence-closing',id:'gone-thread'},values:[['closing','A closing worth keeping']],updatedAt:'2026-10-04T12:00:00Z'}];await page.goto('/');await expect(page.locator('.story-viewbar')).toBeVisible();await page.locator('#import-file').setInputFiles({name:'unfinished.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('[data-action=accept-import]').click();}
async function inbox(page){await page.locator('[data-nav=archive]').first().click();await page.getByRole('tab',{name:/Unfinished edits/}).click();}
const row=(page,id)=>page.locator(`[data-unfinished-id="${id}"]`);
const snapshot=page=>page.evaluate(()=>{const w=CounterplotTutorial.snapshot();return w.projects.find(p=>p.id===w.active);});
test('unfinished edits live in Archive with searchable previews and keyboard tabs',async({page})=>{
 await load(page);await expect(page.locator('.story-viewbar [data-action=drafts]')).toHaveCount(0);await inbox(page);await expect(row(page,'draft-moment')).toContainText('A clue before midnight');await expect(row(page,'draft-moment').locator('time')).toHaveAttribute('datetime','2026-10-05T12:00:00.000Z');await expect(row(page,'draft-scene')).toContainText('Time not recorded');await page.getByLabel('Search unfinished edits').fill('pearl');await expect(page.locator('.unfinished-edit')).toHaveCount(1);await page.getByLabel('Search unfinished edits').fill('');const tab=page.getByRole('tab',{name:/Unfinished edits/});await tab.focus();await tab.press('Home');await expect(page.getByRole('tab',{name:/Archived pieces/})).toBeFocused();await page.keyboard.press('End');await expect(tab).toBeFocused();await expect(tab).toHaveAttribute('aria-selected','true');
});
test('discard is undoable and survives reload without changing saved story content',async({page})=>{
 await load(page);const before=await snapshot(page);await inbox(page);await row(page,'draft-moment').getByRole('button',{name:'Discard',exact:true}).click();await expect(row(page,'draft-moment')).toHaveCount(0);expect((await snapshot(page)).nodes).toEqual(before.nodes);await page.locator('.topbar [data-action=undo]').click();await expect(row(page,'draft-moment')).toBeVisible();await row(page,'draft-moment').getByRole('button',{name:'Discard',exact:true}).click();await expect(page.locator('#save-status')).toContainText('Saved on this device');await page.reload();await inbox(page);await expect(row(page,'draft-moment')).toHaveCount(0);await expect(page.locator('.unfinished-edit')).toHaveCount(2);
});
test('Resume preserves the saved story until submission and then removes its unfinished entry',async({page})=>{
 await load(page);const before=await snapshot(page);await inbox(page);await row(page,'draft-moment').getByRole('button',{name:'Resume',exact:true}).click();await expect(page.locator('#dialog [name=title]')).toHaveValue('A clue before midnight');expect((await snapshot(page)).timeline).toEqual(before.timeline);await page.locator('#dialog [type=submit]').click();await expect(row(page,'draft-moment')).toHaveCount(0);expect((await snapshot(page)).timeline[0].title).toBe('A clue before midnight');await page.locator('.topbar [data-action=undo]').click();await expect(row(page,'draft-moment')).toBeVisible();expect((await snapshot(page)).timeline).toEqual(before.timeline);
});
test('imported scenes move into the story once and unavailable originals keep their edits',async({page})=>{
 await load(page);await inbox(page);await row(page,'draft-missing').getByRole('button',{name:'Resume',exact:true}).click();await expect(page.locator('#dialog')).toContainText('The original item is no longer available');await expect(page.locator('#dialog')).toContainText('A closing worth keeping');await page.locator('#dialog [data-action=close-dialog]').click();await expect(row(page,'draft-missing')).toBeVisible();await row(page,'draft-scene').getByRole('button',{name:'Add to story',exact:true}).click();const after=await snapshot(page);expect(after.nodes.filter(n=>n.prose==='She carries the pearl across the river.')).toHaveLength(1);expect(after.drafts.some(d=>d.id==='draft-scene')).toBeFalsy();await page.locator('.topbar [data-action=undo]').click();await inbox(page);await expect(row(page,'draft-scene')).toBeVisible();
});
test('unfinished edits fit narrow screens and Archive navigation still opens archived pieces',async({page})=>{
 await load(page);await inbox(page);for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width+1);expect(await page.locator('.unfinished-edit').evaluateAll(xs=>xs.every(x=>x.scrollWidth<=x.clientWidth+1))).toBeTruthy();}await page.locator('[data-nav=outline]').first().click();await page.locator('.tray [data-nav=archive]').click();await expect(page.getByRole('tab',{name:/Archived pieces/})).toHaveAttribute('aria-selected','true');await expect(page.locator('[data-action=purge-all]')).toHaveCount(0);
});

test('quickly closing an editor saves the latest typing and emptying Archive keeps it',async({page})=>{
 await load(page);await page.getByRole('tab',{name:'Chronology',exact:true}).click();await page.locator('[data-action=edit-moment]').first().click();await page.evaluate(()=>{const input=document.querySelector('#dialog [name=title]');input.value='Typed just before closing';input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#dialog [data-action=close-dialog]').click();});await expect(page.locator('#dialog')).not.toBeVisible();const saved=await snapshot(page);expect(saved.drafts.some(d=>d.values?.some(([key,value])=>key==='title'&&value==='Typed just before closing'))).toBeTruthy();await page.getByRole('tab',{name:'Outline',exact:true}).click();await page.locator('[data-action=archive-node][data-id=ui-node-0]').click();await page.locator('[data-nav=archive]').first().click();await page.getByRole('button',{name:'Empty archive',exact:true}).click();await page.locator('#dialog [type=submit]').click();await page.getByRole('tab',{name:/Unfinished edits/}).click();expect((await snapshot(page)).drafts).toEqual(saved.drafts);await expect(page.locator('.unfinished-edit').filter({hasText:'Typed just before closing'})).toBeVisible();
});
test('a rejected save keeps the unfinished edit available to resume',async({page})=>{
 await load(page);const before=await snapshot(page);await inbox(page);await row(page,'draft-moment').getByRole('button',{name:'Resume',exact:true}).click();await page.locator('#dialog [name=storyEndDate]').fill('1929-03-01');await page.locator('#dialog [type=submit]').click();await expect(page.locator('#dialog')).toBeVisible();expect((await snapshot(page)).timeline).toEqual(before.timeline);await page.locator('#dialog [data-action=close-dialog]').click();await expect(row(page,'draft-moment')).toBeVisible();await row(page,'draft-moment').getByRole('button',{name:'Resume',exact:true}).click();await expect(page.locator('#dialog [name=storyEndDate]')).toHaveValue('1929-03-01');
});
