/* Shared palette, local reference cards, and deliberate archive deletion. */
let paintOpen=false, brush='', mediaBusy=false;
const swatches=()=>W.palette(workspace);
function colorStyle(id,fallback='green'){const all=[...W.PALETTE,...(workspace.swatches||[])];const s=all.find(x=>x.id===id)||all.find(x=>x.id===fallback);if(!s)return '';const t=W.colorTokens(s.hex);return `--accent:${t.ink};--tint:${t.tint};--swatch:${t.swatch}`}
function paintAttrs(type,id,cid=''){return `data-paint="${type}" data-paint-id="${esc(id)}" data-paint-cid="${esc(cid)}"`}
function paintButton(type,id,cid=''){return ib('piece-color',id,'spark','Color this piece',`data-owner="${type}" data-cid="${esc(cid)}"`)}
function owner(type,id,cid=''){return type==='project'?p():type==='character'?person(id):type==='node'?node(id):type==='world'?p().world.find(w=>w.id===id):type==='connection'?p().connections.find(r=>r.id===id):type==='block'?person(cid)?.blocks.find(b=>b.id===id):null}
function paint(type,id,cid,color){const obj=owner(type,id,cid);if(!obj){toast('Color this block at the beginning of the story.');return}mutate('Changed piece color',()=>{obj.color=color;if(type==='block'){for(const x of person(cid).changes)if(x.blockId===id&&x.block)x.block.color=color;}ui.snap=id})}
function colorField(value='',automatic=true){return `<div class="field"><span>Color</span><div class="color-picker">${automatic?`<label class="auto-swatch"><input type="radio" name="color" value="" aria-label="Automatic color"${!value?' checked':''}><span>Auto</span></label>`:''}${[...swatches(),...([...W.PALETTE,...(workspace.swatches||[])].filter(s=>s.id===value&&!swatches().some(v=>v.id===s.id)))].map(s=>`<label style="${colorStyle(s.id)}" title="${esc(s.name)}"><input type="radio" name="color" value="${s.id}" aria-label="${esc(s.name)}"${s.id===value?' checked':''}></label>`).join('')}</div><small class="hint">Create your own swatches in Colors, at the top of the workshop.</small></div>`}
function paintTray(){return paintOpen?`<section class="paint-tray" aria-label="Color tray"><div><strong>${brush?'Now touch a piece':'A little color goes a long way.'}</strong><small>${brush?'Tap a scene, thread, character, world detail, or block. Escape puts the brush down.':'Drag a swatch onto a piece. Or click a swatch, then click a piece.'}</small></div><div class="paint-swatches">${swatches().map(s=>`<button class="paint-chip${brush===s.id?' chosen':''}" style="${colorStyle(s.id)}" draggable="true" data-drag="swatch" data-drag-id="${s.id}" ${act('choose-brush',s.id)} aria-label="Paint with ${esc(s.name)}" aria-pressed="${brush===s.id}" title="${esc(s.name)}"><span></span><small>${esc(s.name)}</small></button>`).join('')}</div>${btn('palette-manager','Edit palette','edit')}${ib('toggle-paint','','close','Close color tray')}</section>`:''}
function paletteManager(){modalData={kind:'palette'};dialog('YOUR COLORS, ACROSS THE WORKSHOP','Make it yours.',`<p class="help">Use the same colors across all your stories. Editing a custom swatch recolors every piece that uses it. Deleting a swatch removes it from the palette. Pieces already using it keep their color. Undo restores the swatch. MICE letters still tell you what each thread does.</p><div class="palette-list">${swatches().map(s=>`<div class="palette-row" style="${colorStyle(s.id)}"><span class="color-sample"></span><div class="grow"><strong>${esc(s.name)}</strong><small>${s.hex.toUpperCase()}</small></div>${W.PALETTE.some(x=>x.id===s.id)?'<small class="hint">Classic</small>':ib('edit-swatch',s.id,'edit','Edit '+s.name)}${ib('delete-swatch',s.id,'trash','Delete '+s.name+' swatch')}</div>`).join('')}</div>`,btn('new-swatch','Create a swatch','plus',true))}
function editSwatch(id=''){const s=swatches().find(s=>s.id===id)||{name:'',hex:'#708f8b'};modalData={kind:'swatch',id};dialog('MIX SOMETHING OF YOUR OWN',id?'Refine this color.':'A new color for your stories.',field('Swatch name','name',s.name,'Rain on glass')+`<div class="two-fields">${field('Pick a color','picker',s.hex,'','color')}${field('Hex color','hex',s.hex,'#708f8b')}</div><div id="swatch-preview" class="swatch-preview" style="${tokenStyle(s.hex)}"><span class="color-sample"></span><div><strong>Your words stay readable.</strong><p>Cards use a gentle tint and a darker ink version of this color.</p></div></div>`,submit(id?'Save swatch':'Add swatch',id?'Updates every piece using this swatch.':'Available across every story in this workshop.'),'swatch')}
function tokenStyle(hex){const t=W.colorTokens(hex);return `--accent:${t.ink};--tint:${t.tint};--swatch:${t.swatch}`}
function pieceColor(type,id,cid=''){const o=owner(type,id,cid);if(!o){toast('Select The beginning to recolor a starting block.');return}modalData={kind:'piece-color',type,id,cid};dialog('A COLOR TO FIND IT BY','Give this piece a color.',colorField(o.color||'',type!=='character'),submit('Keep color'),'piece-color')}
function referencesButton(type,id){const o=owner(type,id);return `<button class="text-btn" ${act('references',id,`data-owner="${type}"`)}>${icon('book')}Pictures & references${o?.references?.length?' · '+o.references.length:''}</button>`}
function referenceSummary(type,id){const o=owner(type,id),list=o?.references||[];return `<div class="reference-summary">${referencesButton(type,id)}${list.length?`<div class="reference-peeks">${list.slice(0,4).map(r=>`<button ${act('open-reference',r.id,`data-owner="${type}" data-owner-id="${id}"`)} title="${esc(r.title)}">${r.image?`<img src="${r.image}" alt="${esc(r.title)}">`:`<span>${icon(r.url?'connections':'book')}${esc(r.title)}</span>`}</button>`).join('')}</div>`:''}</div>`}
function references(type='project',id=p().id){const o=owner(type,id);if(!o)return;modalData={kind:'references',type,id};dialog('KEEP THE THINGS THAT SPARK SOMETHING',esc(o.name||o.title||o.label||'Story references'),`<p class="help">Pictures, useful links, and notes, kept with this ${type==='node'?'story piece':type}. Images are saved inside your backups.</p><div class="reference-grid">${(o.references||[]).map(r=>`<button class="reference-card" ${act('open-reference',r.id,`data-owner="${type}" data-owner-id="${id}"`)}>${r.image?`<img src="${r.image}" alt="${esc(r.title)}">`:`<div class="reference-symbol">${icon(r.url?'connections':'book')}</div>`}<strong>${esc(r.title)}</strong><small>${esc(r.url?new URL(r.url).hostname:r.note||'Image reference')}</small></button>`).join('')||'<p class="help">A costume sketch. A research link. A detail you want to remember. Start with one.</p>'}</div>`,btn('new-reference','Add a reference','plus',true))}
function editReference(type,id,rid=''){const r=owner(type,id)?.references?.find(r=>r.id===rid)||{title:'',url:'',note:'',image:''};modalData={kind:'reference',type,id,rid,image:r.image||''};dialog('A SMALL COLLECTION OF INSPIRATION',rid?'Keep it within reach.':'Pin a reference.',`<div class="media-drop" data-media-drop="reference"><div id="reference-image">${r.image?`<img src="${r.image}" alt="Reference preview">`:'<p>Drop an image here, or choose one below.</p>'}</div><div class="row wrap">${btn('choose-reference-image','Choose image','plus')}${btn('remove-reference-image','Remove image','close')}</div><small>JPEG, PNG, WebP, or GIF · optimized for this local notebook</small></div>${field('Title','title',r.title,'What do you want to remember?')}${field('Link · optional','url',r.url,'https://…')}${field('Notes · optional','note',r.note,'Why this belongs in the story…','textarea')}${r.url?`<a class="text-btn reference-link" href="${esc(W.safeURL(r.url))}" target="_blank" rel="noopener noreferrer">Open reference link ↗</a>`:''}`,`${rid?`<button type="button" class="text-btn" ${act('remove-reference',rid)}>Remove reference</button>`:'<span class="hint">Only add the details you need.</span>'}<button type="submit" class="btn primary">Save reference${icon('check')}</button>`,'reference')}
function portraitDialog(cid){const c=person(cid);if(!c)return;modalData={kind:'portrait',cid,image:c.portrait||''};dialog('A FACE TO PUT TO THE NAME',esc(c.name),`<div class="media-drop portrait-drop" data-media-drop="portrait"><div id="portrait-preview">${c.portrait?`<img src="${c.portrait}" alt="Portrait of ${esc(c.name)}">`:`<div class="portrait-placeholder">${esc(initials(c.name))}</div>`}</div><div class="row wrap">${btn('choose-portrait','Choose portrait','plus')}${btn('remove-portrait','Use initials','close')}</div><p>Drop a picture here or choose one. The original file stays untouched; the workshop saves a smaller copy.</p></div>`,submit('Save portrait'),'portrait')}
async function prepareImage(file,portrait=false){if(!file||!/^image\/(jpeg|png|webp|gif)$/.test(file.type))throw Error('Choose a JPEG, PNG, WebP, or GIF image.');if(file.size>20000000)throw Error('Choose an image under 20 MB.');const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image could not be opened. Try another file.'));img.src=url});const size=portrait?600:1400,scale=Math.min(1,size/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#faf8f0';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let result='',quality=.84;do{result=canvas.toDataURL('image/jpeg',quality);quality-=.12}while(result.length>240000&&quality>.22);if(result.length>650000)throw Error('This image is still too large. Choose a smaller version.');return result}finally{URL.revokeObjectURL(url)}}
async function receiveImage(file){if(!modalData||!['portrait','reference'].includes(modalData.kind)||mediaBusy)return;const m=modalData;mediaBusy=true;const submitButton=$('#dialog [type="submit"]');if(submitButton)submitButton.disabled=true;const error=$('#form-error');error.textContent='Preparing your picture…';try{const image=await prepareImage(file,m.kind==='portrait');if(modalData!==m)return;m.image=image;const preview=$(m.kind==='portrait'?'#portrait-preview':'#reference-image');preview.innerHTML=`<img src="${image}" alt="Selected image preview">`;if(m.kind==='reference'&&!$('#dialog [name="title"]').value)$('#dialog [name="title"]').value=file.name.replace(/\.[^.]+$/,'');error.textContent='Ready to save.'}catch(e){if(modalData===m)formError(e)}finally{mediaBusy=false;if(submitButton?.isConnected)submitButton.disabled=false}}
function chooseImage(){const f=$('#media-file');f.value='';f.click()}
function confirmPurge(id=''){const rows=id?p().archive.filter(a=>a.id===id):[...p().archive];if(!rows.length)return;modalData={kind:'purge',ids:rows.map(a=>a.id)};const chars=rows.filter(a=>a.kind==='character');dialog('MAKE ROOM FOR WHAT YOU WANT TO KEEP','Delete permanently?',`<p class="help">Delete ${rows.length===1?'this archived item':'these '+rows.length+' archived items'} and everything stored inside ${rows.length===1?'it':'them'}?</p><ul class="purge-list">${rows.slice(0,15).map(a=>`<li><strong>${esc(a.title)}</strong>${a.kind==='branch'?`<span>${a.nodes.length} pieces, their prose, references, and ${a.changes.length} stored character changes</span>`:''}</li>`).join('')}${rows.length>15?'<li>And '+(rows.length-15)+' more items.</li>':''}</ul>${chars.length?'<p class="help">Deleting a character also removes their cast links, connections, and separately archived blocks.</p>':''}<p class="help">This clears Undo history for this session. Previously exported copies remain separate.</p>`,`<button type="button" class="btn" data-action="close-dialog">Keep them</button><button type="submit" class="btn danger">Delete permanently${icon('trash')}</button>`,'purge')}
function eraseArchive(ids){finishEdit();if(blocked){formError('Saving is blocked. Export your work and reload before permanently deleting items.');return}const before=W.copy(workspace);try{W.purgeArchive(p(),ids);W.validate(workspace);if(!save()){workspace=before;formError('Deletion was cancelled because the new save could not be written.');return}past=[];future=[];closeDialog();render();document.dispatchEvent(new CustomEvent('counterplot:edit',{detail:{label:'Deleted archived items permanently',permanent:true,before:W.copy(before),after:W.copy(workspace)}}));toast('Deleted permanently')}catch(e){workspace=before;formError(e)}}
function duplicateBlock(cid,bid){const c=person(cid),b=c?.blocks.find(b=>b.id===bid);if(!b)return;const duplicate=W.copy(b);duplicate.id=W.uid();mutate('Made a copy of this piece',()=>{c.blocks.splice(c.blocks.indexOf(b)+1,0,duplicate);ui.snap=duplicate.id});closeDialog();editBlock(cid,duplicate.id)}
function extraSubmit(form,data,m){const v=k=>String(data.get(k)||'').trim(),which=form.dataset.form;
 if(which==='swatch'){if(!v('name'))throw Error('Give the swatch a name.');if(!/^#[0-9a-f]{6}$/i.test(v('hex')))throw Error('Use a hex color like #708f8b.');if(mutate('Saved color swatch',()=>{workspace.swatches||=[];const s=workspace.swatches.find(s=>s.id===m.id);if(s)Object.assign(s,{name:v('name'),hex:v('hex')});else workspace.swatches.push({id:W.uid(),name:v('name'),hex:v('hex')});}))paletteManager();return true}
 if(which==='piece-color'){paint(m.type,m.id,m.cid,v('color'));closeDialog();return true}
 if(which==='portrait'||which==='reference'){if(mediaBusy)throw Error('Wait a moment for the picture to finish.');const o=which==='portrait'?person(m.cid):owner(m.type,m.id);if(!o)throw Error('This item is no longer available.');if(which==='reference'&&!v('title'))throw Error('Give the reference a short title.');if(v('url')&&!W.safeURL(v('url')))throw Error('Use a full https:// or http:// link.');const before=W.copy(workspace);try{if(which==='portrait')o.portrait=m.image;else{const r={id:m.rid||W.uid(),title:v('title'),url:v('url')?W.safeURL(v('url')):'',note:v('note'),image:m.image};o.references||=[];const at=o.references.findIndex(x=>x.id===m.rid);if(at>=0)o.references[at]=r;else o.references.push(r)}W.validate(workspace);if(m.image&&new TextEncoder().encode(JSON.stringify(workspace)).byteLength>32000000)throw Error('This workspace would exceed 32 MB. Export a backup before reducing pictures or adding another.');if(!save()){workspace=before;throw Error('The picture was not saved. Export your work before closing this window.')}record(before,which==='portrait'?'Updated portrait':'Saved reference');render();if(which==='portrait')closeDialog();else references(m.type,m.id);toast(which==='portrait'?'Portrait saved':'Reference pinned',true)}catch(e){workspace=before;throw e}return true}
 if(which==='purge'){eraseArchive(m.ids);return true}
 return false;
}
document.addEventListener('dragover',e=>{if(!drag&&e.target.closest('[data-media-drop]')){e.preventDefault();e.target.closest('[data-media-drop]').classList.add('media-over')}});
document.addEventListener('dragleave',e=>{e.target.closest('[data-media-drop]')?.classList.remove('media-over')});
document.addEventListener('drop',e=>{const drop=e.target.closest('[data-media-drop]');if(!drag&&drop&&e.dataTransfer?.files?.length){e.preventDefault();drop.classList.remove('media-over');receiveImage(e.dataTransfer.files[0])}});

/* Optional Milieu links. Reuse ordinary World entries and existing worldIds. */
function milieuWorld(n){
 const linked=n.worldIds.map(id=>p().world.find(w=>w.id===id)).filter(w=>w&&['place','culture'].includes(w.type));
 return `<div class="milieu-world" aria-label="Setting and culture for ${esc(name(n))}"><span class="milieu-label">Setting / culture <small>optional</small></span><div class="milieu-links">${linked.map(w=>`<span class="milieu-chip"><button type="button" ${act('edit-world',w.id)} aria-label="Open ${esc(w.type==='culture'?'culture':'setting')}: ${esc(w.name)}">${icon('world')}<span>${esc(w.name)}</span><small>${w.type==='culture'?'Culture':'Setting'}</small></button><button type="button" class="milieu-remove" ${act('milieu-unlink',n.id,`data-world="${esc(w.id)}"`)} aria-label="Unlink ${esc(w.name)} from ${esc(name(n))}">×</button></span>`).join('')}<button type="button" class="milieu-add" ${act('milieu-link',n.id)}>${linked.length?'+ Link':'+ Link setting or culture'}</button></div></div>`;
}
function milieuPicker(id){
 const n=node(id);if(!n)return;
 const entries=p().world.filter(w=>['place','culture'].includes(w.type)&&!n.worldIds.includes(w.id));
 modalData={kind:'milieu-link',id};
 dialog('SETTING / CULTURE · OPTIONAL','Link to '+esc(name(n)),`<p class="help">Choose an existing entry to link it immediately. The original stays in World; editing it updates every linked thread.</p><label class="field"><span>Find a setting or culture</span><input name="milieu-search" type="search" placeholder="Search by name…" autocomplete="off"></label><div class="milieu-options">${entries.map(w=>`<button type="button" class="milieu-option" ${act('milieu-choose',id,`data-world="${esc(w.id)}"`)}><span>${esc(w.name)}</span><small>${w.type==='culture'?'Culture':'Setting'}</small></button>`).join('')}</div><p class="help milieu-no-results"${entries.length?' hidden':''}>${entries.length?'No matching entries.':'No unlinked settings or cultures yet.'} Create one below, or close this dialog to leave the link empty.</p>`,btn('milieu-new','New setting','plus',false,`data-id="${esc(id)}" data-type="place"`)+btn('milieu-new','New culture','plus',false,`data-id="${esc(id)}" data-type="culture"`));
}
document.addEventListener('input',e=>{if(e.target.name!=='milieu-search')return;const query=e.target.value.trim().toLocaleLowerCase();let visible=0;for(const option of document.querySelectorAll('.milieu-option')){option.hidden=!option.textContent.toLocaleLowerCase().includes(query);if(!option.hidden)visible++;}const empty=document.querySelector('.milieu-no-results');if(empty)empty.hidden=visible>0;});

// World links share the card's plot/cast row; the existing link editor remains the source of truth.
function worldChips(n){return [...new Set(n.worldIds||[])].map(id=>p().world.find(w=>w.id===id)).filter(Boolean).map(w=>`<button type="button" class="world-chip" ${act('edit-world',w.id)} aria-label="Open world entry: ${esc(w.name)}">${icon('world')}<span>${esc(w.name)}</span></button>`).join('');}
