/* Contextual tools for the retained story features. This runs inside the app. */
W.validate(workspace);
const craftFields=['ideaNotes','context','goal','purpose','entry','tension','stakes','development','turn','action','after','gain','cost','response','reaction','readerExpectation','next','exit'];
const human=s=>s.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
const disclosure=(title,body,open=false)=>`<details class="story-disclosure" ${open?'open':''}><summary>${esc(title)}</summary><div class="stack">${body}</div></details>`;
const peopleOptions=()=>[['','Unassigned'],...W.allCharacters(p()).map(c=>[c.id,c.name])];
const targetOptions=()=>[['','None'],...W.allCharacters(p()).map(c=>[c.id,c.name]),...W.allWorld(p()).map(w=>[w.id,w.name])];
const momentOptions=()=>[['','Opening state'],...W.events(p()).map(e=>[e.id||e.key,(e.storyDate?e.storyDate+' · ':'')+(e.title||name(e.node))+' · '+e.edge])];
const recordTools=(kind,id)=>btn('history','History','change',false,`data-kind="${kind}" data-id="${esc(id)}"`)+btn('used-here','Used here','search',false,`data-id="${esc(id)}"`);
let branchFocus='',storyFilter='',onlyReview=false,calendarView=false;
const oldVisibleNodes=visibleNodes;
visibleNodes=function(){const ids=branchFocus?W.descendants(p(),branchFocus):null;if(ids)ids.add(branchFocus);const chosen=oldVisibleNodes().filter(n=>(!ids||ids.has(n.id))&&(!storyFilter||n.cast.includes(storyFilter))&&(!onlyReview||W.continuity(p(),n).stale));const keep=new Set(chosen.map(n=>n.id));for(const n of chosen){let parent=n.parentId;while(parent){keep.add(parent);parent=node(parent)?.parentId||'';}}return oldVisibleNodes().filter(n=>keep.has(n.id));};
const oldWorkbench=workbench;
workbench=function(){
  const views=[['outline','Outline'],['write','Write'],['read','Read'],['sequence','Sequence'],['chronology','Chronology'],['choices','Choices']];
  const nav=`<div class="story-viewbar"><nav role="tablist" aria-label="Story views">${views.map(([id,label])=>`<button class="btn ${ui.mode===id?'primary':''}" ${act('story-view',id)} id="story-tab-${id}" role="tab" aria-selected="${ui.mode===id}" aria-controls="story-panel" tabindex="${ui.mode===id?0:-1}">${label}</button>`).join('')}</nav><div class="story-tools">${storyToolButtons()}</div><button class="btn story-tools-toggle" ${act('story-tools')}>${icon('edit')}Story tools</button></div>`;
  const filters=`<div class="story-filters">${branchFocus?btn('branch-focus','Whole story / '+esc(name(node(branchFocus))),'outline'):''}<label>Cast <select id="story-cast-filter">${opts([['','Everyone'],...p().characters.map(c=>[c.id,c.name])],storyFilter)}</select></label><label><input id="story-review-filter" type="checkbox" ${onlyReview?'checked':''}> Needs review</label></div>`;
  const content=()=>{
  if(['outline','write'].includes(ui.mode))return filters+oldWorkbench().replace(/<div class="segmented" aria-label="Workbench view">[\s\S]*?<\/div>/,'');
  const visible=new Set(visibleNodes().map(n=>n.id));
  if(ui.mode==='read')return filters+`<article class="continuous-manuscript"><h1>${esc(p().title)}</h1>${W.reading(p()).filter(n=>visible.has(n.id)&&n.prose).map(n=>`<section><button class="text-btn" ${act('write-node',n.id)}>Edit ${esc(name(n))}</button><h2>${esc(name(n))}</h2><div class="manuscript-prose">${esc(n.prose)}</div></section>`).join('')||'<p>Write on any thread or beat, then read the manuscript here.</p>'}</article>`;
  if(ui.mode==='choices')return filters+heading('CHARACTER CHOICES','What they choose','Goals, decisions, and the consequences they leave behind.')+`<div class="story-choices choice-list">${W.reading(p()).filter(n=>visible.has(n.id)).map(choiceCard).join('')||'<p class="list-note">No pieces match these filters.</p>'}</div>`;
  if(ui.mode==='sequence'){const moments=W.readingMoments(p()).filter(e=>visible.has(e.node.id));return filters+heading('MANUSCRIPT ORDER','The reader’s journey','Every opening, beat, and closing. Drag moments into the order your reader encounters them.')+`<div class="story-sequence moment-list"><div class="view-key"><span>${moments.length} moments</span><span>Outline and chronology stay independent</span></div>${moments.map((e,i)=>momentCard(e,i,'readingSequence')).join('')||'<p class="list-note">No moments match these filters.</p>'}</div>`;}
  const events=W.events(p()).filter(e=>(!storyFilter||e.node.cast?.includes(storyFilter))&&(!onlyReview||node(e.node.id)&&W.continuity(p(),e.node).stale));
  const ordered=calendarView?[...events].sort((a,b)=>(a.storyDate||'9999').localeCompare(b.storyDate||'9999')):events;let previousDate=null;
  return filters+heading('STORY CHRONOLOGY','When things happen',calendarView?'Moments grouped by date. Switch to story order to drag moments and change their history.':'Follow the story through time. Drag moments to retime character, world, and relationship history.',btn('calendar-view',calendarView?'Story order':'Group by date','book')+btn('new-moment','Add moment','plus'))+`<div class="story-sequence chronology-track"><div class="view-key"><span>${events.length} moments</span><span>${calendarView?'Grouped by date':'Story order · earliest to latest'}</span></div>${ordered.map((e,i)=>{const date=e.storyDate||'Undated',group=calendarView&&date!==previousDate?`<h2 class="timeline-date">${esc(date)}</h2>`:'';previousDate=date;return group+momentCard(e,i,'timeline',!calendarView);}).join('')||'<p class="list-note">No moments match these filters.</p>'}</div>`;
  };
  return nav+`<section id="story-panel" role="tabpanel" aria-labelledby="story-tab-${ui.mode}">${content()}</section>`;
};
function storyToolButtons(){return btn('story-settings','Story settings','edit')+btn('outline-text','Text outline','import')+btn('structure-review','Review structure','check');}
actions['story-tools']=()=>{modalData={kind:'story-tools'};dialog('YOUR STORY','Story tools',`<div class="stack">${storyToolButtons()}</div>`);};
function momentLabel(e){return e.nodeId===''?'Story moment':e.edge==='close'?'Thread closes':e.node.type==='B'?'Beat':'Thread opens';}
function momentCast(n){return (n.cast||[]).map(id=>person(id)).filter(Boolean).map(c=>`<span class="moment-person">${avatar(c)}${esc(c.name)}</span>`).join('');}
function momentCard(e,index,collection,sortable=true){
 const n=e.node,t=W.TYPES[n.type]||W.TYPES.B,closing=e.edge==='close',label=momentLabel(e),title=e.title||name(n),timeline=collection==='timeline';
 const description=closing?n.closing:n.opening||n.prose?.slice(0,180);
 const actionsHTML=timeline?btn('edit-moment','Details','edit',false,`data-id="${esc(e.key)}"`)+btn('consequences','Changes','change',false,`data-id="${esc(e.key)}"`):closing?btn('sequence-closing','Edit closing','edit',false,`data-id="${esc(n.id)}"`):btn('write-node','Write','write',false,`data-id="${esc(n.id)}"`);
 return `<article class="moment-card color-${t.color}${closing?' moment-close':''}${timeline?' timeline-moment':''}" style="${colorStyle(n.color,t.color)}" ${sortable?`data-sort-collection="${collection}" data-sort-id="${esc(e.key)}"`:''} data-moment-key="${esc(e.key)}">
 <div class="moment-position"><span class="moment-number">${String(index+1).padStart(2,'0')}</span>${sortable?`<button class="grip" draggable="true" data-sequence-drag="${collection}" data-sequence-id="${esc(e.key)}" aria-label="Move ${esc(label+': '+title)}">⠿</button>`:''}</div>
 <div class="moment-content"><div class="moment-meta"><span class="moment-type" title="${esc(t.name)}">${n.type==='B'?icon('write'):esc(n.type)}</span><span>${label}</span>${timeline&&e.storyDate?`<time>${esc(e.storyDate)}${e.storyEndDate?' → '+esc(e.storyEndDate):''}</time>`:''}${e.archived&&e.nodeId?'<span>Archived piece</span>':''}${momentCast(n)}</div><h2>${esc(title)}</h2>${description?`<p class="moment-description">${esc(description)}</p>`:`<p class="moment-placeholder">${closing?'What is different when this thread closes?':timeline?'An undetailed moment in story time.':'What happens here?'}</p>`}</div>
 <div class="moment-actions">${sortable?`<div class="moment-move">${ib('sequence-nudge',e.key,'up','Move earlier',`data-collection="${collection}" data-direction="-1"`)}${ib('sequence-nudge',e.key,'down','Move later',`data-collection="${collection}" data-direction="1"`)}</div>`:''}<div class="moment-edit">${actionsHTML}</div></div></article>`;
}
function choiceCard(n,index){
 const t=W.TYPES[n.type],parts=[['Goal',n.goal],['Choice',n.action||n.turn||n.development],['Gain',n.gain],['Cost',n.cost],['Reaction',n.reaction],['After',n.after]].filter(([,value])=>value);
 return `<article class="choice-card color-${t.color}" style="${colorStyle(n.color,t.color)}"><span class="choice-number">${String(index+1).padStart(2,'0')}</span><div class="choice-content"><div class="moment-meta"><span class="moment-type" title="${esc(t.name)}">${n.type==='B'?icon('write'):n.type}</span><span>${esc(n.sceneKind&&n.sceneKind!=='open'?human(n.sceneKind):t.name)}</span>${momentCast(n)}</div><h2>${esc(name(n))}</h2>${parts.length?`<dl class="choice-beats">${parts.map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`:`<p class="choice-context">${esc(n.opening||'What do they want, and what do they decide?')}</p>`}</div><div class="choice-action">${btn('scene-details','Open scene craft','edit',false,`data-id="${esc(n.id)}"`)}</div></article>`;
}
function sequenceClosing(id){const n=node(id);if(!n||n.type==='B')return;modalData={kind:'sequence-closing',id};dialog('THREAD CLOSES',esc(name(n)),field('Closing beat','closing',n.closing,'What changes by the end of this thread?','textarea'),submit('Keep closing'),'sequence-closing');}
actions['sequence-closing']=el=>sequenceClosing(el.dataset.id);
function sequenceRow(collection,id,title,description,tools){return `<article class="sequence-row" data-sort-collection="${collection}" data-sort-id="${esc(id)}"><button class="grip" draggable="true" data-sequence-drag="${collection}" data-sequence-id="${esc(id)}" aria-label="Move ${esc(title)}">⠿</button><div class="grow"><strong>${esc(title)}</strong><p>${esc(description)}</p></div><div class="row">${ib('sequence-nudge',id,'up','Move earlier',`data-collection="${collection}" data-direction="-1"`)}${ib('sequence-nudge',id,'down','Move later',`data-collection="${collection}" data-direction="1"`)}${tools}</div></article>`;}
document.addEventListener('keydown',e=>{const tab=e.target.closest?.('[role=tab][data-action=story-view]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...tab.closest('[role=tablist]').querySelectorAll('[role=tab]')],index=tabs.indexOf(tab),next=e.key==='Home'?tabs[0]:e.key==='End'?tabs.at(-1):tabs[(index+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];actions['story-view'](next);document.getElementById(next.id)?.focus({preventScroll:true});});
let sequenceDrag=null;
document.addEventListener('dragstart',e=>{const el=e.target.closest('[data-sequence-drag]');if(!el)return;finishEdit();sequenceDrag={collection:el.dataset.sequenceDrag,id:el.dataset.sequenceId};e.dataTransfer.setData('text/plain','Counterplot sequence');e.dataTransfer.effectAllowed='move';});
document.addEventListener('dragover',e=>{const row=e.target.closest('[data-sort-collection]');if(sequenceDrag&&row?.dataset.sortCollection===sequenceDrag.collection){e.preventDefault();row.classList.add('sequence-landing');}});
document.addEventListener('dragleave',e=>e.target.closest('[data-sort-collection]')?.classList.remove('sequence-landing'));
document.addEventListener('drop',e=>{const row=e.target.closest('[data-sort-collection]');if(!sequenceDrag||row?.dataset.sortCollection!==sequenceDrag.collection)return;e.preventDefault();const d=sequenceDrag;sequenceDrag=null;mutate('Moved '+(d.collection==='timeline'?'story moment':'reading position'),pr=>W.reorder(pr,d.collection,d.id,row.dataset.sortId));});
document.addEventListener('dragend',()=>{sequenceDrag=null;$$('.sequence-landing').forEach(x=>x.classList.remove('sequence-landing'));});
document.addEventListener('change',e=>{if(e.target.id==='story-cast-filter'){storyFilter=e.target.value;render();}if(e.target.id==='story-review-filter'){onlyReview=e.target.checked;render();}});
const oldInspector=inspector;
inspector=function(){const html=oldInspector(),n=node(ui.selected);return n?html.replace('</aside>',`<div class="section stack">${btn('scene-details','Scene craft & links','edit',false,`data-id="${n.id}"`)}${btn('continuity','Review continuity'+(W.continuity(p(),n).stale?' · changed':''),'change',false,`data-id="${n.id}"`)}${btn('branch-focus','Focus on this branch','focus',false,`data-id="${n.id}"`)}${btn('continue-scene','Continue from here','arrow',false,`data-id="${n.id}"`)}${recordTools('node',n.id)}${n.type!=='B'?btn('remove-frame','Remove frame; keep contents','close',false,`data-id="${n.id}"`):''}</div></aside>`):html;};
function sceneDetails(id){const n=node(id);if(!n)return;modalData={kind:'scene-details',id};
  const cast=W.allCharacters(p()).map(c=>select(c.name,'role-'+c.id,[['','Not in scene'],['present','Present'],['assist','Supports'],['oppose','Opposes'],['complicate','Complicates'],['witness','Witnesses']],n.ensemble?.find(x=>x.id===c.id)?.role||(n.cast.includes(c.id)?'present':''))).join('');
  const links=W.allNodes(p()).filter(x=>x.type!=='B').map(t=>select(name(t),'thread-'+t.id,[['','No contribution'],['open','Opens'],['advance','Advances'],['close','Closes']],n.miceLinks?.find(x=>x.miceId===t.id)?.edge||n.miceLinks?.find(x=>x.miceId===t.id)?.role||'')).join('');
  const sceneOptions=[['','None'],...W.allNodes(p()).filter(x=>x.id!==id).map(x=>[x.sceneId||x.id,name(x)])];
  dialog('A CLOSER LOOK',name(n),select('Point of view','povId',peopleOptions(),n.povId||n.focus||'')+disclosure('People and their roles',cast)+disclosure('Scene craft',field('Lane label','thread',n.thread||'')+select('Approach','sceneKind',[['open','Open'],['attempt','Attempt'],['discovery','Discovery'],['relationship','Relationship'],['aftermath','Aftermath']],n.sceneKind||'open')+craftFields.map(k=>field(human(k),k,n[k]||'','','textarea')).join('')+field('Internal beats · one per line','beats',(n.beats||[]).join('\n'),'','textarea'))+disclosure('Story connections',links+select('Continues from','parent',sceneOptions,n.parent||'')+W.allNodes(p()).filter(x=>x.id!==id).map(x=>`<label class="check-chip"><input type="checkbox" name="extraParents" value="${esc(x.sceneId||x.id)}" ${n.extraParents?.some(v=>v.id===(x.sceneId||x.id))?'checked':''}>Also follows ${esc(name(x))}</label>`).join(''))+disclosure('Thread links',select('Opening scene','openSceneId',sceneOptions,n.openSceneId||'')+select('Closing scene','closeSceneId',sceneOptions,n.closeSceneId||'')),submit('Keep details'),'scene-details');
}
function editMoment(key=''){const e=p().timeline.find(x=>x.key===key)||{title:'',storyDate:'',storyEndDate:''};modalData={kind:'moment',id:key};dialog('STORY TIME',key?'A moment in the story':'Add a story moment',field('Title','title',e.title)+field('Start date','storyDate',e.storyDate||'','','date')+field('End date','storyEndDate',e.storyEndDate||'','','date'),submit('Keep moment'),'moment');}
function history(kind,id){const subject=kind==='character'?W.allCharacters(p()).find(x=>x.id===id):kind==='world'?W.allWorld(p()).find(x=>x.id===id):kind==='connection'?W.allConnections(p()).find(x=>x.id===id):node(id);if(!subject)return;
  modalData={kind:'history',subjectKind:kind,id};let rows=[];
  if(kind==='character')rows=[...subject.changes.map(x=>({...x,label:x.op+' · '+(x.block?.text||x.blockId)})),...subject.lifeChanges.map(x=>({...x,label:'Life · '+x.status})),...subject.stateCheckpoints.map(x=>({...x,label:'Saved earlier self · '+x.blocks.length+' pieces'}))];
  else if(kind==='world')rows=[...(subject.stateChanges||[]).map(x=>({...x,label:x.value})),...(subject.faction?.changes||[]).map(x=>({...x,label:x.operation+' · '+(x.block?.text||x.blockId)}))];
  else if(kind==='connection')rows=(subject.changes||[]).map(x=>({...x,label:[x.bond,x.aWant,x.bWant,x.notes].filter(Boolean).join(' · ')}));
  else rows=W.events(p()).filter(e=>e.nodeId===id).map(e=>({id:e.id,momentId:e.id,label:e.edge}));
  dialog('HISTORY',subject.name||subject.label||name(subject),rows.map(x=>`<article class="history-row"><strong>${esc(x.label)}</strong><small>${esc(momentOptions().find(y=>y[0]===(x.momentId||W.momentId(p(),x.at)))?.[1]||'Opening')}</small><p>${esc(x.reason||'')}</p></article>`).join('')||'<p>No timed changes yet.</p>',btn('new-history','Add a change','plus',true,`data-kind="${kind}" data-id="${id}"`));
}
const originalCharacterEditor=editCharacter;
editCharacter=function(id=''){originalCharacterEditor(id);if(!id)return;const c=person(id);$('#dialog .dialog-body').insertAdjacentHTML('beforeend',disclosure('Story presence',select('Opening life status','lifeStatus',[['alive','Alive'],['dead','Dead']],c.lifeStatus)+field('Prominence','prominence',c.prominence?.opening||'')+recordTools('character',id)+btn('earlier-self','Save this point as an earlier self','copy',false,`data-id="${id}"`)+btn('duplicate-character','Duplicate with history','copy',false,`data-id="${id}"`)))};
const originalWorldEditor=editWorld;
editWorld=function(id='',linkNode='',initialType='place'){originalWorldEditor(id,linkNode,initialType);const w=p().world.find(x=>x.id===id)||{};$('#dialog .dialog-body').insertAdjacentHTML('beforeend',disclosure('Tracked state',field('State label','stateLabel',w.stateLabel||'','Ownership, condition, location…')+field('Opening value','stateValue',w.stateValue||'')+select('Opening target','stateTargetId',targetOptions(),w.stateTargetId||''))+(id?disclosure('Knowledge & history',btn('knowledge','Who knows this?','edit',false,`data-id="${id}"`)+recordTools('world',id)+(w.type==='group'?btn('faction','Faction pieces','characters',false,`data-id="${id}"`):'')):''));};
editConnection=function(id=''){const targets=targetOptions().slice(1);if(targets.length<2){toast('Create two people or World groups first.');return;}const r=p().connections.find(x=>x.id===id)||{a:targets[0][0],b:targets[1][0],label:'',notes:''},t=r.terms||{};modalData={kind:'connection',id};dialog('THE SPACE BETWEEN THEM','What holds them together?',select('One person or faction','a',targets,r.a)+select('Another person or faction','b',targets,r.b)+field('Connection','label',r.label)+field('What one wants','aWant',r.aWant||'','','textarea')+field('What the other wants','bWant',r.bWant||'','','textarea')+field('Notes','notes',r.notes,'','textarea')+disclosure('Membership & terms',select('Membership','membership',['unspecified','member','associate','former','none'].map(x=>[x,human(x)]),t.membership||'unspecified')+field('Position','position',t.position||'')+select('Visibility','visibility',['open','concealed','contested'].map(x=>[x,human(x)]),t.visibility||'open')+field('One person’s tie','aTie',t.aTie||'')+field('The other’s tie','bTie',t.bTie||'')+select('Supporting fact','factId',[['','None'],...p().world.filter(e=>e.type==='fact').map(e=>[e.id,e.name])],t.factId||'')+`<label><input name="active" type="checkbox" ${t.active!==false?'checked':''}> Active connection</label><label><input name="leadership" type="checkbox" ${t.leadership?'checked':''}> Leadership</label>`)+(id?recordTools('connection',id):''),submit('Keep connection'),'connection');};
function knowledge(id,cid=''){const item=cid?person(cid)?.blocks.find(b=>b.id===id):p().world.find(e=>e.id===id);if(!item)return;modalData={kind:'knowledge',id,cid};const knowers=[...W.allCharacters(p()),...W.allWorld(p()).filter(w=>w.type==='group')];dialog('KNOWLEDGE',item.name||item.text,`<p class="help">Character knowledge follows story time. Reader disclosure follows manuscript order.</p>`+knowers.map(c=>`<div class="knowledge-row"><label><input type="checkbox" name="knower" value="${c.id}" ${(item.knownBy||[]).includes(c.id)?'checked':''}>${esc(c.name)}</label>${select('Knows from','known-'+c.id,momentOptions(),item.knownFrom?.[c.id]||'')}</div>`).join('')+(!cid&&item.type==='fact'?disclosure('Reader appearances',W.reading(p(),{archived:true}).map(n=>select(name(n),'reader-'+(n.sceneId||n.writingId),[['','Not shown'],['shown','First shown'],['reinterpreted','Reinterpreted']],item.readerAppearances?.find(x=>x.sceneId===(n.sceneId||n.writingId))?.kind||'')).join('')):''),submit('Keep knowledge'),'knowledge');}
const originalBlockEditor=editBlock;
editBlock=function(cid,bid='',kindId){originalBlockEditor(cid,bid,kindId);const b=person(cid)?.blocks.find(x=>x.id===bid)||{};$('#dialog .dialog-body').insertAdjacentHTML('beforeend',disclosure('Attachments & circumstances',select('Primary target','targetId',targetOptions(),b.targetId||'')+select('Circumstances','context',['any','public','private','danger','ease'].map(x=>[x,human(x)]),b.context||'any')+['for','from','at','with','against'].map(role=>select(human(role),'link-'+role,targetOptions(),b.links?.find(x=>x.role===role)?.targetId||'')).join('')+(bid?btn('block-knowledge','Who knows this?','edit',false,`data-id="${bid}" data-cid="${cid}"`):'')));};
function newHistory(kind,id,key=''){const subject=kind==='character'?person(id):kind==='world'?p().world.find(w=>w.id===id):p().connections.find(r=>r.id===id);if(!subject)return;modalData={kind:'history-change',subjectKind:kind,id};const fields=kind==='character'?select('Life status','status',[['alive','Alive'],['dead','Dead']],subject.lifeStatus):kind==='world'?field(subject.stateLabel||'State','value',subject.stateValue||'')+select('Target','targetId',targetOptions(),''):field('Connection','bond',subject.label)+field('One wants','aWant',subject.aWant||'')+field('Other wants','bWant',subject.bWant||'')+field('Notes','notes',subject.notes||'','','textarea');dialog('A CHANGE IN THE STORY',subject.name||subject.label,select('At moment','momentId',momentOptions().slice(1),W.momentId(p(),key)||momentOptions()[1]?.[0])+fields+field('Reason','reason','','','textarea'),submit('Keep change'),'history-change');}
function storySettings(){const w=p().storyWorld;modalData={kind:'story-settings'};dialog('YOUR STORY','The world and the draft',field('Version label','version',p().version)+field('Setting','setting',w.setting||p().subtitle,'','textarea')+select('Reality','reality',['undecided','ordinary','extraordinary','ambiguous'].map(x=>[x,human(x)]),w.reality||'undecided')+field('Tone · comma separated','tones',(w.tones||[]).join(', '))+field('Story priorities','priorities',w.priorities||'','','textarea')+field('World notes and constraints','notes',w.notes||'','','textarea'),submit('Keep story settings'),'story-settings');}
function drafts(){closeDialog();ui.archiveTab='unfinished';ui.unfinishedSearch='';navigate('archive');}
function editPreview(d){
 const values=d.form?d.values||[]:Object.entries(d.draft||{}),skip=/^(id|.*Id|.*Ids|color|type|kind|status|parent|op|at|knower|extraParents|plots|ids)$|^(known-|role-|thread-)/;
 const fields=values.filter(([key,value])=>typeof value==='string'&&value.trim()&&!skip.test(key)&&!/^w[a-f0-9]{25,}$/.test(value));
 return fields.slice(0,3).map(([key,value])=>({label:human(key.replace(/([a-z])([A-Z])/g,'$1 $2')),value:value.trim()}));
}
function unfinishedRows(query=''){
 const q=query.trim().toLocaleLowerCase(),items=[...p().drafts].sort((a,b)=>(Date.parse(b.updatedAt||b.created)||0)-(Date.parse(a.updatedAt||a.created)||0));
 return items.filter(d=>JSON.stringify([d.title,d.form,d.kind,d.values,d.draft]).toLocaleLowerCase().includes(q)).map(d=>{
  const label=({'scene-details':'Scene craft','sequence-closing':'Thread closing',form:'Unfinished form',scene:'Imported scene',world:'World entry'})[d.form||d.kind]||human(d.form||d.kind||'Edit');
  const date=new Date(d.updatedAt||d.created||''),dated=Number.isFinite(date.getTime()),preview=editPreview(d);
  return `<article class="unfinished-edit" data-unfinished-id="${esc(d.id)}"><div class="unfinished-content"><div class="unfinished-meta"><span>${esc(label)}</span>${dated?`<time datetime="${date.toISOString()}">${esc(date.toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}))}</time>`:'<span>Time not recorded</span>'}</div><h2>${esc(d.title||d.draft?.title||label)}</h2>${preview.length?`<dl class="unfinished-preview">${preview.map(f=>`<div><dt>${esc(f.label)}</dt><dd>${esc(f.value.length>180?f.value.slice(0,180)+'…':f.value)}</dd></div>`).join('')}</dl>`:'<p class="muted">Saved selections are ready to review.</p>'}</div><div class="unfinished-actions">${btn('recover-draft',!d.form&&d.kind==='scene'?'Add to story':'Resume','edit',false,`data-id="${esc(d.id)}"`)}<button class="text-btn" ${act('discard-edit',d.id)}>Discard</button>${ib('export-draft',d.id,'export','Export unfinished edit: '+(d.title||label))}</div></article>`;
 }).join('')||`<p class="list-note">${q?'No unfinished edits match.':'Nothing unfinished. Changes you leave in an editor will wait here.'}</p>`;
}
archive=function(){
 const unfinished=ui.archiveTab==='unfinished',tab=unfinished?'unfinished':'archived';
 const tabs=`<div class="archive-tabs" role="tablist" aria-label="Archive sections">${[['archived','Archived pieces',p().archive.length],['unfinished','Unfinished edits',p().drafts.length]].map(([id,label,count])=>`<button id="archive-tab-${id}" role="tab" aria-selected="${id===tab}" aria-controls="archive-panel" tabindex="${id===tab?0:-1}" ${act('archive-tab',id)}>${label}<span>${count}</span></button>`).join('')}</div>`;
 const body=unfinished?`<p class="archive-intro">Pick up an edit you left unfinished, or discard it. Your saved story stays as it is until you keep the edit.</p>${p().drafts.length?`<input id="unfinished-search" class="archive-search" placeholder="Find an unfinished edit…" aria-label="Search unfinished edits" value="${esc(ui.unfinishedSearch||'')}">`:''}<div id="unfinished-rows">${unfinishedRows(ui.unfinishedSearch||'')}</div>`:p().archive.length?`<input id="archive-search" class="archive-search" placeholder="Find an archived idea…" aria-label="Search archive"><div id="archive-rows">${archiveRows()}</div>`:empty('Room for the ideas you set aside.','Drop a piece onto Archive in the tray. Its nested pieces, writing, and character changes will wait here.','','archive');
 return heading('ROOM FOR SECOND THOUGHTS','Archive','Saved pieces and unfinished edits, ready when you need them.',!unfinished&&p().archive.length?btn('purge-all','Empty archive','trash'):'')+`<div class="content-page">${tabs}<section id="archive-panel" role="tabpanel" aria-labelledby="archive-tab-${tab}">${body}</section></div>`;
};
actions['archive-tab']=el=>{ui.archiveTab=el.dataset.id;ui.unfinishedSearch='';render();};
actions['discard-edit']=el=>{mutate('Discarded unfinished edit',pr=>{pr.drafts=pr.drafts.filter(d=>d.id!==el.dataset.id);});};
document.addEventListener('input',e=>{if(e.target.id==='unfinished-search'){ui.unfinishedSearch=e.target.value;$('#unfinished-rows').innerHTML=unfinishedRows(e.target.value);}});
document.addEventListener('keydown',e=>{const tab=e.target.closest?.('[data-action=archive-tab]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const id=e.key==='Home'?'archived':e.key==='End'?'unfinished':tab.dataset.id==='archived'?'unfinished':'archived';actions['archive-tab']({dataset:{id}});$('#archive-tab-'+id)?.focus();});
function unavailableEdit(d){modalData={kind:'unavailable-edit'};dialog('UNFINISHED EDIT','The original item is no longer available',`<p>Your unfinished work is still saved. Export it to retain every field, or return to Unfinished edits.</p><dl class="unfinished-preview">${editPreview(d).map(f=>`<div><dt>${esc(f.label)}</dt><dd>${esc(f.value)}</dd></div>`).join('')}</dl>`,btn('export-draft','Export unfinished edit','export',false,`data-id="${esc(d.id)}"`));}

function outlineText(){modalData={kind:'outline-text'};dialog('PLAIN TEXT OUTLINE','Paste a few building blocks',`<p class="help">Use &lt;C&gt;, &lt;M&gt;, &lt;I&gt;, or &lt;E&gt; to open a thread; &lt;/C&gt; and matching closing tags to end it. Plain lines become beats.</p>`+field('Tagged outline','outline',W.taggedOutline(p()),'','textarea')+'<div id="outline-preview"></div>',submit('Preview new pieces'),'outline-text');}
const oldExtraSubmit=extraSubmit;
extraSubmit=function(form,data,m){const v=k=>String(data.get(k)||'').trim(),kind=form.dataset.form;
  if(kind==='sequence-closing'){if(mutate('Updated closing beat',()=>{node(m.id).closing=v('closing');}))closeDialog();return true;}
  if(kind==='scene-details'){if(mutate('Kept scene details',()=>{const n=node(m.id);for(const k of craftFields)n[k]=v(k);n.sceneKind=v('sceneKind');n.thread=v('thread');n.povId=v('povId');n.focus=n.povId;n.beats=v('beats').split('\n').filter(Boolean);n.ensemble=W.allCharacters(p()).filter(c=>v('role-'+c.id)).map(c=>({...n.ensemble?.find(x=>x.id===c.id),id:c.id,role:v('role-'+c.id)}));n.cast=[...new Set([...n.ensemble.map(x=>x.id),n.povId].filter(Boolean))];n.miceLinks=W.allNodes(p()).filter(t=>t.type!=='B'&&v('thread-'+t.id)).map(t=>({...n.miceLinks?.find(x=>x.miceId===t.id),miceId:t.id,edge:v('thread-'+t.id),role:v('thread-'+t.id)}));n.parent=v('parent');n.extraParents=data.getAll('extraParents').map(id=>n.extraParents?.find(x=>x.id===id)||{id,hash:''});n.openSceneId=v('openSceneId');n.closeSceneId=v('closeSceneId');}))closeDialog();return true;}
  if(kind==='moment'){if(mutate('Kept story moment',()=>{let e=p().timeline.find(x=>x.key===m.id);if(!e){const id=W.uid();e={id,key:id+':moment',nodeId:'',edge:'open'};p().timeline.push(e);}Object.assign(e,{title:v('title'),storyDate:v('storyDate'),storyEndDate:v('storyEndDate')});}))closeDialog();return true;}
  if(kind==='knowledge'){if(mutate('Kept knowledge timing',()=>{const item=m.cid?person(m.cid).blocks.find(b=>b.id===m.id):p().world.find(w=>w.id===m.id);item.knownBy=data.getAll('knower');item.knownFrom=Object.fromEntries(item.knownBy.map(id=>[id,v('known-'+id)]));if(!m.cid&&item.type==='fact'){item.readerAppearances=W.reading(p(),{archived:true}).filter(n=>v('reader-'+(n.sceneId||n.writingId))).map(n=>{const sceneId=n.sceneId||n.writingId;return {...item.readerAppearances?.find(x=>x.sceneId===sceneId),id:item.readerAppearances?.find(x=>x.sceneId===sceneId)?.id||W.uid(),sceneId,kind:v('reader-'+sceneId),note:item.readerAppearances?.find(x=>x.sceneId===sceneId)?.note||''};});if(item.readerAppearances.filter(x=>x.kind==='shown').length>1)throw Error('Choose one first-shown scene.');}}))closeDialog();return true;}
  if(kind==='history-change'){if(!v('momentId'))throw Error('Choose a story moment.');const subject=m.subjectKind==='character'?person(m.id):m.subjectKind==='world'?p().world.find(w=>w.id===m.id):p().connections.find(r=>r.id===m.id);if(mutate('Kept historical change',()=>{const key=m.subjectKind==='character'?'lifeChanges':m.subjectKind==='world'?'stateChanges':'changes';const fields=m.subjectKind==='character'?['status']:m.subjectKind==='world'?['value','targetId']:['bond','aWant','bWant','notes'];const x=(subject[key]||=[]).find(x=>x.momentId===v('momentId'))||{id:W.uid()};Object.assign(x,{momentId:v('momentId'),reason:v('reason')},Object.fromEntries(fields.map(k=>[k,v(k)])));if(!subject[key].includes(x))subject[key].push(x);})){closeDialog();}return true;}
  if(kind==='story-settings'){if(mutate('Kept story settings',()=>{p().version=v('version');Object.assign(p().storyWorld,{setting:v('setting'),reality:v('reality'),tones:v('tones').split(',').map(x=>x.trim()).filter(Boolean),priorities:v('priorities'),notes:v('notes')});p().subtitle=v('setting');}))closeDialog();return true;}
  if(kind==='outline-text'){const nodes=W.parseOutline(v('outline'));modalData={kind:'outline-preview',nodes};dialog('OUTLINE PREVIEW',nodes.length+' new pieces',nodes.map(n=>`<p>${esc(n.type)} · ${esc(n.title||n.opening)}</p>`).join(''),btn('accept-outline','Add these pieces','plus',true));return true;}
  // Extend existing forms inside the same model transaction, including their Undo record.
  if(['character','block','world','connection'].includes(kind)){
    const originalMutate=mutate;
    mutate=function(label,fn,options){return originalMutate(label,pr=>{fn(pr);let target;if(kind==='character'){target=person(m.id)||person(ui.character);if(data.has('lifeStatus'))target.lifeStatus=v('lifeStatus');if(data.has('prominence'))target.prominence={...(target.prominence||{changes:[],checkpoints:[]}),opening:v('prominence')};}
      if(kind==='block'){target=person(m.cid).blocks.find(b=>b.id===m.bid)||person(m.cid).blocks.at(-1);target.targetId=v('targetId');target.context=v('context');target.links=['for','from','at','with','against'].flatMap(role=>{const previous=(target.links||[]).filter(x=>x.role===role);return [...(v('link-'+role)?[{...previous[0],role,targetId:v('link-'+role)}]:[]),...previous.slice(1)];});}
      if(kind==='world'){target=pr.world.find(w=>w.id===m.id)||pr.world.at(-1);Object.assign(target,{stateLabel:v('stateLabel'),stateValue:v('stateValue'),stateTargetId:v('stateTargetId')});}
      if(kind==='connection'){target=pr.connections.find(r=>r.id===m.id)||pr.connections.at(-1);Object.assign(target,{aWant:v('aWant'),bWant:v('bWant'),terms:{membership:v('membership'),position:v('position'),visibility:v('visibility'),aTie:v('aTie'),bTie:v('bTie'),factId:v('factId'),active:data.has('active'),leadership:data.has('leadership')}});}
    },options);};queueMicrotask(()=>{mutate=originalMutate;});
  }
  return oldExtraSubmit(form,data,m);
};
Object.assign(actions,{
  'story-view':el=>{finishEdit();ui.mode=el.dataset.id;render();},
  'branch-focus':el=>{closeDialog();branchFocus=el.dataset.id||'';ui.mode='outline';render();},
  'scene-details':el=>sceneDetails(el.dataset.id), 'story-settings':storySettings,
  'calendar-view':()=>{calendarView=!calendarView;render();},'new-moment':()=>editMoment(),'edit-moment':el=>editMoment(el.dataset.id),
  'sequence-nudge':el=>{const collection=el.dataset.collection,ids=$$(`[data-sort-collection="${collection}"]`).map(row=>row.dataset.sortId),at=ids.indexOf(el.dataset.id),dir=Number(el.dataset.direction);if(at<0||at+dir<0||at+dir>=ids.length)return;mutate('Moved '+(collection==='timeline'?'story moment':'reading position'),pr=>W.reorder(pr,collection,ids[at],ids[dir<0?at-1:at+2]||''));},
  'remove-frame':el=>mutate('Removed frame; kept writing and contents',pr=>W.removeFrame(pr,el.dataset.id)),
  'history':el=>history(el.dataset.kind,el.dataset.id),'new-history':el=>newHistory(el.dataset.kind,el.dataset.id),
  'knowledge':el=>knowledge(el.dataset.id),'block-knowledge':el=>knowledge(el.dataset.id,el.dataset.cid),
  'duplicate-character':el=>{if(mutate('Duplicated character and history',pr=>{ui.character=W.duplicateCharacter(pr,el.dataset.id).id;}))closeDialog();},
  'earlier-self':el=>{const c=person(el.dataset.id);if(!ui.at){toast('Choose a story moment on the character timeline first.');return;}mutate('Saved an earlier self',()=>{const s=W.characterState(p(),c,ui.at);c.stateCheckpoints.push({id:W.uid(),momentId:W.momentId(p(),ui.at),blocks:W.copy(s.blocks),lifeStatus:s.lifeStatus});});},
  'used-here':el=>dialog('CONNECTED PIECES','Used here',W.usedHere(p(),el.dataset.id).map(x=>`<button class="search-result" ${act('found-record',x.id,`data-kind="${x.kind}" data-archived="${x.archived}"`)}><strong>${esc(x.label)}</strong><small>${esc(x.kind==='draft'?'Unfinished edit':x.kind)}${x.archived?' · Archive':''}</small></button>`).join('')||'<p>No other pieces link here yet.</p>'),
  'continuity':el=>{const n=node(el.dataset.id),review=W.continuity(p(),n);modalData={kind:'continuity',id:n.id};dialog('CONTINUITY REVIEW',review.stale?'The story around this scene changed':'Compare the story around this scene',`<p>Your prose stays yours. Accepting records the current context.</p><div class="continuity-comparison"><section><h3>Previously reviewed</h3><pre>${esc(JSON.stringify(review.previous,null,2)||'No previous review')}</pre></section><section><h3>Current context</h3><pre>${esc(JSON.stringify(review.current,null,2))}</pre></section></div>`,btn('accept-continuity','Accept current context','check',true));},
  'accept-continuity':()=>{const id=modalData.id;if(mutate('Accepted current continuity',pr=>W.acceptContinuity(pr,node(id))))closeDialog();},
  'outline-text':outlineText,'accept-outline':()=>{const ns=modalData.nodes;if(mutate('Added text outline',pr=>pr.nodes.push(...ns)))closeDialog();},
  'drafts':drafts,'export-draft':el=>{const d=p().drafts.find(x=>x.id===el.dataset.id);download(JSON.stringify(d,null,2),'Counterplot unfinished edit.json','application/json');},
  'recover-draft':el=>{const d=p().drafts.find(x=>x.id===el.dataset.id);if(!d)return;if(d.form){restoreFormDraft(d);return;}const n=W.node('B');Object.assign(n,W.copy(d.draft||{}),{id:W.uid(),type:'B',parentId:'',prose:d.draft?.notes||d.draft?.prose||'',notes:'',cast:[],worldIds:[],title:(d.draft?.title||'Recovered draft')+' · recovered'});if(mutate('Opened recovered draft as a separate piece',pr=>{pr.nodes.push(n);pr.drafts=pr.drafts.filter(x=>x.id!==d.id);ui.selected=n.id;})){closeDialog();ui.mode='write';navigate('outline');}},
});
searchResults=function(q){return W.search(p(),q).map(x=>`<button class="search-result" ${act('found-record',x.id,`data-kind="${x.kind}" data-archived="${x.archived}"`)}><strong>${esc(x.title)}</strong><small>${esc(x.kind==='draft'?'Unfinished edit':x.kind)}${x.archived?' · Archive':''}</small></button>`).join('')||'<p class="list-note">No matching writing or records.</p>';};
actions['found-record']=el=>{if(el.dataset.archived==='true'){closeDialog();ui.archiveTab='archived';navigate('archive');return;}if(el.dataset.kind==='draft'){drafts();return;}if(el.dataset.kind==='connection'){editConnection(el.dataset.id);return;}actions['search-result'](el);};

// Unfinished forms live with the story and survive reload, without storing executable HTML.
let formDraftTimer,activeFormDraft='',submittingFormDraft=null;
const draftable=new Set(['sequence-closing','character','block','change','world','connection','scene-details','moment','knowledge','history-change','story-settings','faction-block','plot-role','consequences']);
function captureFormDraft(){
  clearTimeout(formDraftTimer);const form=$('#dialog[open] form[data-form]');if(!form||(!activeFormDraft&&!editorIsDirty())||!draftable.has(form.dataset.form)||sessionMode==='@author'||window.__COUNTERPLOT_STUDIO__)return;
  const formData=[...new FormData(form)].filter(([,value])=>typeof value==='string');
  if(!activeFormDraft)activeFormDraft=W.uid();
  const previous=p().drafts.find(d=>d.id===activeFormDraft),draft={id:activeFormDraft,kind:'form',title:$('#dialog-title')?.textContent||'Unfinished form',form:form.dataset.form,context:W.copy(modalData),values:formData,updatedAt:new Date().toISOString()};
  if(previous)Object.assign(previous,draft);else p().drafts.push(draft);save();
}
document.addEventListener('input',e=>{if(e.target.closest('#dialog form')){clearTimeout(formDraftTimer);formDraftTimer=setTimeout(captureFormDraft,200);}});
document.addEventListener('change',e=>{if(e.target.closest('#dialog form'))captureFormDraft();});
const baseDialog=dialog;
dialog=function(...args){if($('#dialog').open)captureFormDraft();activeFormDraft='';return baseDialog(...args);};
const baseCloseDialog=closeDialog;
closeDialog=function(){captureFormDraft();if(submittingFormDraft?.projectId===p().id){const id=submittingFormDraft.id;p().drafts=p().drafts.filter(d=>d.id!==id);submittingFormDraft=null;save();const count=$('[data-nav=archive] .count');if(count)count.textContent=String(p().archive.length+p().drafts.length).padStart(2,'0');}activeFormDraft='';baseCloseDialog();queueMicrotask(()=>{if(ui.page==='archive'&&!$('#dialog').open){render();$('#archive-tab-'+(ui.archiveTab||'archived'))?.focus({preventScroll:true});}});};
actions['close-dialog']=()=>closeDialog();
// Capture identifies the edit; successful handlers close the dialog and consume it.
// Cleanup cannot run in a microtask here: browsers may flush it before bubbling.
document.addEventListener('submit',e=>{if(!e.target.matches('#dialog form'))return;captureFormDraft();submittingFormDraft=activeFormDraft?{id:activeFormDraft,projectId:p().id}:null;clearTimeout(formDraftTimer);},true);
document.addEventListener('submit',e=>{if(e.target.matches('#dialog form'))submittingFormDraft=null;});
document.addEventListener('counterplot:before-mode-change',captureFormDraft);window.addEventListener('pagehide',captureFormDraft);document.addEventListener('visibilitychange',()=>{if(document.hidden)captureFormDraft();});
function restoreFormDraft(d){const m=d.context||{};const routes={'sequence-closing':()=>sequenceClosing(m.id),'historical-record':()=>editHistoricalRecord(m.subjectKind,m.id,m.collection,m.recordId),'earlier-self':()=>earlierSelf(m.id),'faction-transition':()=>factionTransition(m.id),evidence:()=>evidenceEditor(m.id,m.evidenceId),character:()=>editCharacter(m.id),block:()=>editBlock(m.cid,m.bid,m.kindId),change:()=>editChange(m.cid,m.bid,m.at,m.changeId),world:()=>editWorld(m.id,m.linkNode),connection:()=>editConnection(m.id),'scene-details':()=>sceneDetails(m.id),moment:()=>editMoment(m.id),knowledge:()=>knowledge(m.id,m.cid),'history-change':()=>newHistory(m.subjectKind,m.id),'story-settings':storySettings,'faction-block':()=>factionBlock(m.id,m.bid),'plot-role':()=>plotRole(m.id,m.cid),consequences:()=>consequenceDialog(m.id)};if(!routes[d.form]){toast('Export this draft to retain its original fields.');return;}try{routes[d.form]();}catch{unavailableEdit(d);return;}const form=$('#dialog[open] form');if(!form){unavailableEdit(d);return;}for(const el of form.elements){if(!el.name)continue;const values=d.values.filter(([name])=>name===el.name).map(([,value])=>value);if(el.type==='checkbox'||el.type==='radio')el.checked=values.includes(el.value);else if(values.length)el.value=values[0];}activeFormDraft=d.id;}

// Import is a two-phase operation: retain the exact input, then append validated stories.
importFile=async function(file){if(!file)return;if(file.size>32_000_000){toast('This file exceeds the supported 32 MB capacity.');return;}
  try{const original=await file.text(),rawData=JSON.parse(original),data=rawData.format==='counterplot'?W.legacy(rawData):W.validate(W.copy(rawData));const fingerprint=TutorialStorage.fingerprint(original),key='counterplot.migration.original.'+fingerprint;
    CounterplotTutorialStore.registerKey(key);if(!CounterplotTutorialStore.getItem(key))await CounterplotTutorialStore.setItem(key,original,'');
    modalData={kind:'import',data,fingerprint,key,metadata:Object.fromEntries(Object.entries(rawData).filter(([key])=>!['projects','trash','tutorialRecords','imports','recoveryCopies'].includes(key)))};
    dialog('BRING YOUR STORY WITH YOU','Ready to import',`<p>The original file has been retained on this device. These stories will be added as independent copies.</p>${data.projects.map(pr=>`<article class="history-row"><strong>${esc(pr.title)}</strong><p>${pr.characters.length} active characters · ${pr.nodes.length} outline pieces · ${pr.archive.length} archived items · ${pr.drafts.length} unfinished edits</p></article>`).join('')}<p>Story time, manuscript order, and outline order are preserved separately.</p>${data.tutorialRecords?'<p>This complete library also contains tutorial saves. Matching or missing saves can be restored; conflicting tutorial libraries are retained separately in Save a copy.</p>':''}${workspace.imports?.some(x=>x.fingerprint===fingerprint)?'<p>This file was imported before. Continuing creates another independent copy.</p>':''}`,btn('export-import-original','Download retained original','export')+btn('accept-import','Add independent copies','plus',true));
  }catch(error){toast('Import stopped. '+error.message);}
};
actions['export-import-original']=()=>{const original=CounterplotTutorialStore.getItem(modalData.key);download(original,'Counterplot original backup.json','application/json');};
actions['accept-import']=async()=>{const incoming=W.copy(modalData.data),metadata=modalData.metadata,fingerprint=modalData.fingerprint,key=modalData.key;if(!await flushWorkspace())return;
  if(mutate('Imported stories',()=>{W.mergeSwatches(workspace,incoming);for(const pr of incoming.projects){const oldId=pr.id;pr.forkedFrom={projectId:oldId,version:pr.version||'',importFingerprint:fingerprint};pr.id=W.uid();if(!sessionMode)stripTutorial(pr);if(incoming.active===oldId)incoming.active=pr.id;workspace.projects.push(pr);}for(const entry of incoming.trash||[]){entry.project.id=W.uid();(workspace.trash||=[]).push(entry);}workspace.active=incoming.active;(workspace.imports||=[]).push({fingerprint,key,metadata,at:new Date().toISOString()});ui.at='';ui.folded.clear();})){if(await flushWorkspace()){closeDialog();navigate('outline');await importTutorialRecords(incoming.tutorialRecords);}else toast('Imported in this tab. Export a backup while the device save is unavailable.');}
};

function faction(id){const e=p().world.find(w=>w.id===id);if(!e)return;modalData={kind:'faction',id};const blocks=W.factionAt(p(),e,ui.at);dialog('A GROUP WITH ITS OWN AIMS',e.name,(blocks||[]).map(b=>`<article class="history-row"><strong>${esc(b.title||b.label||human(b.kind))}</strong><p>${esc(b.text)}</p>${btn('faction-block','Edit','edit',false,`data-id="${id}" data-bid="${b.id}"`)}</article>`).join('')||'<p>Add the group’s wants, methods, values, boundaries, or obligations.</p>',btn('faction-block','Add faction piece','plus',true,`data-id="${id}"`)+recordTools('world',id)+btn('transfer-members','Transfer memberships','change',false,`data-id="${id}"`));}
function factionBlock(id,bid=''){const e=p().world.find(w=>w.id===id),b=e.faction?.blocks.find(x=>x.id===bid)||{kind:'want',text:'',detail:'',title:'',targetId:''};modalData={kind:'faction-block',id,bid};dialog('FACTION PIECE',e.name,select('Kind','kind',['want','method','value','boundary','capability','obligation','custom'].map(x=>[x,human(x)]),b.kind)+field('Label','title',b.title||b.label||'')+field('In their own terms','text',b.text,'','textarea')+field('Detail','detail',b.detail,'','textarea')+select('Target','targetId',targetOptions(),b.targetId)+select('Takes effect','momentId',momentOptions(),'')+field('Reason','reason','','','textarea'),submit('Keep faction piece'),'faction-block');}
function plotRole(id,cid=''){const plot=p().plots.find(x=>x.id===id);if(!plot)return;const c=person(cid)||p().characters[0];if(!c){toast('Create a character first.');return;}const track=plot.cast?.find(t=>t.characterId===c.id),value=W.roleAt(p(),track,ui.at);modalData={kind:'plot-role',id,cid:c.id};dialog('ROLE IN THIS PLOT',plot.label+' · '+plot.title,select('Character','characterId',peopleOptions().slice(1),c.id)+select('Takes effect','momentId',momentOptions(),'')+`<label><input name="inPlot" type="checkbox" ${value.inPlot?'checked':''}> In this plot</label>`+field('Roles · comma separated','roles',value.roles.join(', '),'Protagonist, mentor, opponent…')+field('Qualifier','note',value.note,'','textarea'),submit('Keep plot role'),'plot-role');}
const baseManagePlots=managePlots;
managePlots=function(){baseManagePlots();$('#dialog .dialog-body').insertAdjacentHTML('beforeend',p().plots.map(pl=>`<div class="history-row"><strong>${esc(pl.label)} · ${esc(pl.title)}</strong>${btn('plot-role','Cast roles','characters',false,`data-id="${pl.id}"`)}</div>`).join(''));};actions['manage-plots']=managePlots;
function consequenceDialog(key){modalData={kind:'consequences',id:key};dialog('ONE MOMENT, SEVERAL CONSEQUENCES','What changes here?',`<p class="help">All selected changes are kept together and undo together.</p>`+disclosure('Character life',p().characters.map(c=>select(c.name,'life-'+c.id,[['','No change'],['alive','Alive'],['dead','Dead']],'')).join(''),true)+disclosure('World state',p().world.filter(w=>!['fact','rule'].includes(w.type)).map(w=>field(w.name,'world-'+w.id,'','Leave blank for no change')).join(''))+disclosure('Connections',p().connections.map(r=>field(r.label,'connection-'+r.id,'','New relationship; blank for no change')).join(''))+consequenceExtras(key)+field('Reason','reason','','','textarea'),submit('Keep consequences'),'consequences');}
const moreSubmit=extraSubmit;
extraSubmit=function(form,data,m){const v=k=>String(data.get(k)||'').trim();
  if(form.dataset.form==='faction-block'){if(!v('text'))throw Error('Give the piece a few words.');if(mutate('Kept faction piece',()=>{const e=p().world.find(x=>x.id===m.id);e.faction||={blocks:[],changes:[],checkpoints:[]};const old=e.faction.blocks.find(b=>b.id===m.bid),b={...(old||{}),id:m.bid||W.uid(),kind:v('kind'),key:'custom',title:v('title'),text:v('text'),detail:v('detail'),context:'any',knownBy:old?.knownBy||[],locked:old?.locked||false,targetId:v('targetId'),links:old?.links||[]};if(v('momentId'))e.faction.changes.push({id:W.uid(),momentId:v('momentId'),blockId:b.id,operation:old?'replace':'add',block:b,reason:v('reason')});else if(old)Object.assign(old,b);else e.faction.blocks.push(b);})){closeDialog();}return true;}
  if(form.dataset.form==='plot-role'){if(mutate('Kept plot role',()=>{const plot=p().plots.find(x=>x.id===m.id);plot.cast||=[];let tr=plot.cast.find(x=>x.characterId===v('characterId'));if(!tr){tr={id:W.uid(),characterId:v('characterId'),opening:{inPlot:false,roles:[],note:''},changes:[],checkpoints:[]};plot.cast.push(tr);}const value={inPlot:data.has('inPlot'),roles:v('roles').split(',').map(x=>x.trim()).filter(Boolean),note:v('note')};if(v('momentId')){const existing=tr.changes.find(x=>x.momentId===v('momentId'));if(existing)Object.assign(existing,value);else tr.changes.push({id:W.uid(),momentId:v('momentId'),...value});}else tr.opening=value;}))closeDialog();return true;}
  if(form.dataset.form==='consequences'){const changes=[];for(const c of p().characters)if(v('life-'+c.id))changes.push({kind:'life',targetId:c.id,value:{status:v('life-'+c.id),reason:v('reason')}});for(const w of p().world)if(v('world-'+w.id))changes.push({kind:'world',targetId:w.id,value:{value:v('world-'+w.id),targetId:'',reason:v('reason')}});for(const r of p().connections)if(v('connection-'+r.id))changes.push({kind:'connection',targetId:r.id,value:{bond:v('connection-'+r.id),reason:v('reason')}});changes.push(...readConsequenceExtras(data,m.id));if(mutate('Kept scene consequences',pr=>W.consequences(pr,m.id,changes)))closeDialog();return true;}
  if(form.dataset.form==='transfer-members'){if(!v('destination')||v('destination')===m.id)throw Error('Choose another faction.');if(mutate('Transferred memberships',pr=>{for(const id of data.getAll('members')){const r=pr.connections.find(x=>x.id===id),copy=W.copy(r);copy.id=W.uid();if(copy.a===m.id)copy.a=v('destination');if(copy.b===m.id)copy.b=v('destination');copy.label+=' · transferred';pr.connections.push(copy);r.terms={...(r.terms||{}),membership:'former',active:false};}}))closeDialog();return true;}
  return moreSubmit(form,data,m);
};
Object.assign(actions,{'faction':el=>faction(el.dataset.id),'faction-block':el=>factionBlock(el.dataset.id,el.dataset.bid),'plot-role':el=>plotRole(el.dataset.id,el.dataset.cid),'consequences':el=>consequenceDialog(el.dataset.id),
  'transfer-members':el=>{const id=el.dataset.id;modalData={kind:'transfer-members',id};dialog('FACTION MEMBERSHIP','Move people to another group',select('Destination faction','destination',[['','Choose a faction'],...p().world.filter(w=>w.type==='group'&&w.id!==id).map(w=>[w.id,w.name])],'')+p().connections.filter(r=>r.a===id||r.b===id).map(r=>`<label class="check-chip"><input type="checkbox" name="members" value="${r.id}">${esc(r.label)}</label>`).join(''),submit('Transfer selected memberships'),'transfer-members');}
});

actions['structure-review']=()=>dialog('STRUCTURE REVIEW','A few things to consider',W.structureIssues(p()).map(x=>`<article class="history-row"><strong>${esc(name(node(x.id)))}</strong><p>${esc(x.text)}</p>${btn('branch-focus','Focus here','focus',false,`data-id="${x.id}"`)}</article>`).join('')||'<p>No structural questions found. Deliberate overlaps and open endings are yours to keep.</p>');
actions['continue-scene']=el=>{if(mutate('Added a continuation',pr=>{ui.selected=W.continueScene(pr,el.dataset.id).id;})){ui.mode='write';navigate('outline');}};

function consequenceExtras(key){
 const event=W.events(p()).find(e=>e.key===key),sceneId=event?.node.sceneId||event?.node.writingId||'';
 return disclosure('Character pieces',p().characters.map(c=>select(c.name+' · piece','block-id-'+c.id,[['','No change'],...W.stateAt(p(),c,key,true).map(b=>[b.id,b.label||b.text.slice(0,80)])],'')+field('New words for '+c.name,'block-text-'+c.id,'','','textarea')).join(''))+
 disclosure('Prominence and plot roles',p().characters.map(c=>field(c.name+' · prominence','prominence-'+c.id,'')+p().plots.map(pl=>field(c.name+' · '+pl.label+' roles','role-'+pl.id+'-'+c.id,'','Comma separated; blank leaves unchanged')).join('')).join(''))+
 disclosure('Knowledge and reader disclosure',p().world.filter(w=>w.type==='fact').map(w=>`<h3>${esc(w.name)}</h3>`+select('Learns this fact','knower-'+w.id,[['','Nobody new'],...p().characters.map(c=>[c.id,c.name]),...p().world.filter(e=>e.type==='group').map(e=>[e.id,e.name])],'')+(sceneId?select('Reader learns in this scene','reader-kind-'+w.id,[['','No change'],['shown','First shown'],['reinterpreted','Reinterpreted']],''):'')).join(''))+
 disclosure('Faction pieces',p().world.filter(w=>w.type==='group').map(w=>select(w.name+' · piece','faction-id-'+w.id,[['','No change'],...W.factionAt(p(),w,key).map(b=>[b.id,b.title||b.text.slice(0,80)])],'')+field('New words for '+w.name,'faction-text-'+w.id,'','','textarea')).join(''));
}
function readConsequenceExtras(data,key){const v=k=>String(data.get(k)||'').trim(),changes=[],reason=v('reason');
 for(const c of p().characters){const bid=v('block-id-'+c.id),text=v('block-text-'+c.id);if(bid&&text){const old=W.stateAt(p(),c,key,true).find(b=>b.id===bid);if(!old)throw Error('That character piece is absent before this moment.');changes.push({kind:'block',targetId:c.id,value:{op:'develop',blockId:bid,block:{...W.copy(old),text},reason}});}if(v('prominence-'+c.id))changes.push({kind:'prominence',targetId:c.id,value:{value:v('prominence-'+c.id),reason}});for(const pl of p().plots)if(v('role-'+pl.id+'-'+c.id))changes.push({kind:'role',targetId:c.id,plotId:pl.id,value:{inPlot:true,roles:v('role-'+pl.id+'-'+c.id).split(',').map(x=>x.trim()).filter(Boolean),note:'',reason}});}
 const e=W.events(p()).find(e=>e.key===key),sceneId=e?.node.sceneId||e?.node.writingId;
 for(const w of p().world){if(v('knower-'+w.id))changes.push({kind:'knowledge',targetId:w.id,value:{knowerId:v('knower-'+w.id)}});if(v('reader-kind-'+w.id)&&sceneId)changes.push({kind:'reader',targetId:w.id,value:{sceneId,kind:v('reader-kind-'+w.id),note:reason}});const bid=v('faction-id-'+w.id),text=v('faction-text-'+w.id);if(bid&&text){const old=W.factionAt(p(),w,key).find(b=>b.id===bid);changes.push({kind:'faction',targetId:w.id,value:{operation:'replace',blockId:bid,block:{...W.copy(old),text},reason}});}}
 return changes;
}
const basicConnections=connections;
connections=function(){return basicConnections()+`<section class="shared-stakes content-page">`+disclosure('Shared stakes',W.sharedStakes(p()).map(s=>`<article class="history-row"><strong>${esc(targetOptions().find(x=>x[0]===s.targetId)?.[1]||'Shared target')}</strong>${s.participants.map(x=>`<p>${esc(person(x.characterId)?.name)} · ${esc(x.text)}</p>`).join('')}</article>`).join('')||'<p>Attach two characters’ wants to the same target to see their shared stakes here.</p>')+'</section>';};

function castRoster(){modalData={kind:'cast-roster'};dialog('YOUR CAST','Put people in order',p().characters.map(c=>sequenceRow('characters',c.id,c.name,c.identity,btn('edit-character','Edit','edit',false,`data-id="${c.id}"`))).join(''));}
actions['cast-roster']=castRoster;
const previousCharacterPage=characters;
characters=function(){return previousCharacterPage().replace('<div class="page-actions">','<div class="page-actions">'+btn('cast-roster','Arrange cast','characters'));};
function characterPresence(c){const state=W.characterState(p(),c,ui.at),prominence=W.prominenceAt(p(),c,ui.at);return `<div class="character-presence" aria-label="Story presence at the selected moment"><span class="presence-badge" data-life-status="${esc(state.lifeStatus)}">${state.lifeStatus==='dead'?'Dead':'Alive'}</span>${prominence?`<span class="presence-badge">${esc(prominence)}</span>`:''}<small>${ui.at?esc(eventLabel(ui.at)):'At the beginning'}</small></div>`;}
const rosterNudge=actions['sequence-nudge'];actions['sequence-nudge']=el=>{rosterNudge(el);if(el.dataset.collection==='characters')castRoster();};
actions['pin-block']=el=>{if(!ui.at){mutate('Updated pinned piece',()=>{const b=person(el.dataset.cid).blocks.find(b=>b.id===el.dataset.id);b.pinned=!b.pinned;});return;}mutate('Changed emphasis at this moment',()=>{const c=person(el.dataset.cid),b=W.stateAt(p(),c,ui.at).find(b=>b.id===el.dataset.id);if(!b)throw Error('This piece is not present here.');const existing=c.changes.find(x=>x.at===ui.at&&x.blockId===b.id);if(existing&&existing.op!=='retire')existing.block.pinned=!b.pinned;else c.changes.push({id:W.uid(),at:ui.at,momentId:W.momentId(p(),ui.at),blockId:b.id,op:'develop',block:{...W.copy(b),pinned:!b.pinned},pinOnly:true,reason:'Changed emphasis at this point in the story'});});};

const helpText={outline:'Move cards to reshape the outline. Use Sequence for manuscript order, and Chronology to change story time. A scene can open, advance, or close several threads. Optional craft and continuity tools live beside the selected piece.',characters:'Drag a character into a story piece to add them to its cast. Drag a character block onto a moment to change it there. The timeline shows their state at that point; opening blocks remain independent.',world:'Keep places, objects, facts, rules, and factions here. Knowledge belongs to named people or factions and starts at a story moment. Reader appearances are separate, in manuscript order.',connections:'Connect people and factions, describe what each wants, and record how the relationship changes. Membership, leadership, and concealed ties live under optional terms.',archive:'Archived pieces keep their writing and history for later. Restore brings them back. Permanent deletion is separate and clears Undo history.'};
const existingGuide=help;
help=function(){existingGuide();$('#dialog .dialog-body').insertAdjacentHTML('afterbegin',`<aside class="history-row"><h3>Here in ${esc(human(ui.page))}</h3><p>${esc(helpText[ui.page]||helpText.outline)}</p>${btn('show-context-controls','Show the controls','focus')}</aside>`);};actions.help=help;
actions['show-context-controls']=()=>{closeDialog();const target=$(ui.page==='outline'?'.board-toolbar':ui.page==='characters'?'.time-strip':'.page-actions');if(target){target.classList.add('context-highlight');target.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});setTimeout(()=>target.classList.remove('context-highlight'),4000);}};
const contextualDialog=dialog;dialog=function(...args){contextualDialog(...args);const utilities=$('#dialog .dialog-utilities');utilities?.insertAdjacentHTML('afterbegin','<button type="button" class="text-btn" data-action="form-help" aria-expanded="false">Help</button>');};
actions['form-help']=el=>{const existing=$('#form-context-help');if(existing){existing.remove();el.setAttribute('aria-expanded','false');return;}const kind=$('#dialog form')?.dataset.form||modalData?.kind||'';const hints={'scene-details':'Everything here is optional. Point of view is separate from who participates. Linking a scene to a thread does not move its prose or change story time.',knowledge:'Tick who knows this, then choose when they learn it. Reader appearances describe what your audience sees, independently of character knowledge.','history-change':'Choose a moment in story time. The new value applies from that moment onward; earlier states remain intact.',consequences:'Choose the changes caused by this moment. They are saved as one action, and one Undo reverses the entire batch.','faction-block':'A faction can have wants, methods, values, boundaries, abilities, and obligations. Choose a moment to change its history, or leave Opening state to edit its starting pieces.'};const note=document.createElement('aside');note.id='form-context-help';note.className='history-row';note.textContent=hints[kind]||'Enter only the details that help your story. Changes stay in this form until you keep them. Unfinished edits are in Archive → Unfinished edits.';$('#dialog .dialog-body').prepend(note);el.setAttribute('aria-expanded','true');};
function earlierSelf(id){const c=person(id);if(!c)return;modalData={kind:'earlier-self',id};dialog('MAKE ROOM BEFORE THE OPENING','An earlier self for '+c.name,'<p>Your current opening will become a saved state before the existing moments. Later writing, history, and other characters stay intact.</p>'+field('Earlier state name','earlierLabel','')+field('Opening to preserve','preservedLabel',c.openingLabel||'')+field('Saved opening date','storyDate','','','date')+select('Start the earlier self with','seed',[['copy','Copied pieces, ready to revise'],['blank','A blank set of pieces']],'copy')+select('Earlier life status','lifeStatus',[['alive','Alive'],['dead','Dead']],c.lifeStatus),submit('Add earlier self'),'earlier-self');}
actions['earlier-self']=el=>earlierSelf(el.dataset.id);draftable.add('earlier-self');
function factionTransition(id){modalData={kind:'faction-transition',id};dialog('A CHANGE IN ORGANIZATION','Split, merge, or absorb',select('What happens?','mode',[['split','Splits into successors'],['merge','Merges with another faction'],['absorb','Is absorbed by another faction']],'split')+select('At story moment','moment',momentOptions().slice(1),momentOptions()[1]?.[0]||'')+select('Other faction, for merge or absorption','partnerId',[['','Choose a faction'],...p().world.filter(w=>w.type==='group'&&w.id!==id).map(w=>[w.id,w.name])],'')+field('Successor names · one per line','names','','','textarea')+disclosure('Transfer selected members',p().characters.map(c=>`<label class="check-chip"><input name="members" type="checkbox" value="${c.id}">${esc(c.name)}</label>`).join(''))+'<p>Earlier memberships remain in history. Selected people join the first successor.</p>',submit('Keep faction transition'),'faction-transition');}
actions['transfer-members']=el=>factionTransition(el.dataset.id);draftable.add('faction-transition');
const chronologySubmit=extraSubmit;
extraSubmit=function(form,data,m){const v=k=>String(data.get(k)||'').trim();if(form.dataset.form==='earlier-self'){if(mutate('Added an earlier self',pr=>{W.addEarlierSelf(pr,m.id,{earlierLabel:v('earlierLabel'),preservedLabel:v('preservedLabel'),storyDate:v('storyDate'),seed:v('seed'),lifeStatus:v('lifeStatus')});ui.at='';}))closeDialog();return true;}if(form.dataset.form==='faction-transition'){if(mutate('Kept faction transition',pr=>W.transitionFaction(pr,{sourceId:m.id,partnerId:v('partnerId'),mode:v('mode'),names:v('names').split('\n'),moment:v('moment'),memberIds:data.getAll('members')})))closeDialog();return true;}return chronologySubmit(form,data,m);};
function evidenceEditor(id,evidenceId=''){const n=node(id);if(!n||n.type!=='I'){toast('Choose an Inquiry thread.');return;}const link=(n.evidenceLinks||[]).find(x=>x.id===evidenceId)||{sourceType:'fact',sourceId:'',bearing:'supports',note:''};modalData={kind:'evidence',id,evidenceId};dialog('INQUIRY EVIDENCE','What bears on this question?',select('Existing fact or scene','source',[['','Choose evidence'],...p().world.filter(w=>w.type==='fact').map(w=>['fact:'+w.id,w.name]),...W.reading(p()).map(s=>['scene:'+(s.sceneId||s.writingId),name(s)])],link.sourceId?link.sourceType+':'+link.sourceId:'')+select('How it bears on the answer','bearing',[['supports','Supports'],['challenges','Challenges'],['complicates','Complicates']],link.bearing)+field('Why?','note',link.note,'','textarea'),submit('Keep evidence link'),'evidence');}
const detailWithEvidence=sceneDetails;
sceneDetails=function(id){detailWithEvidence(id);const n=node(id);if(n?.type==='I')$('#dialog .dialog-body').insertAdjacentHTML('beforeend',disclosure('Evidence and interpretation',(n.evidenceLinks||[]).map(x=>`<article class="history-row"><strong>${esc(x.bearing)} · ${esc(p().world.find(w=>w.id===x.sourceId)?.name||W.allNodes(p()).find(s=>(s.sceneId||s.writingId)===x.sourceId)?.title||x.sourceId)}</strong><p>${esc(x.note)}</p>${btn('edit-evidence','Edit evidence','edit',false,`data-id="${id}" data-evidence-id="${x.id}"`)}</article>`).join('')+btn('edit-evidence','Link evidence','plus',false,`data-id="${id}"`)));};actions['scene-details']=el=>sceneDetails(el.dataset.id);actions['edit-evidence']=el=>evidenceEditor(el.dataset.id,el.dataset.evidenceId);draftable.add('evidence');
const evidenceSubmit=extraSubmit;extraSubmit=function(form,data,m){const v=k=>String(data.get(k)||'').trim();if(form.dataset.form==='evidence'){const [sourceType,sourceId]=v('source').split(':');if(!sourceId)throw Error('Choose an existing fact or scene.');if(mutate('Kept evidence link',()=>{const n=node(m.id);n.evidenceLinks||=[];const previous=n.evidenceLinks.find(x=>x.id===m.evidenceId),record={id:m.evidenceId||W.uid(),sourceType,sourceId,bearing:v('bearing'),note:v('note')};if(previous)Object.assign(previous,record);else n.evidenceLinks.push(record);})){closeDialog();}return true;}return evidenceSubmit(form,data,m);};
function historicalSubject(kind,id){return kind==='character'?W.allCharacters(p()).find(c=>c.id===id):kind==='world'?W.allWorld(p()).find(w=>w.id===id):W.allConnections(p()).find(r=>r.id===id);}
function historicalRows(subject,kind){if(kind==='character')return [['changes',subject.changes],['lifeChanges',subject.lifeChanges],['stateCheckpoints',subject.stateCheckpoints],['prominence.changes',subject.prominence.changes],['prominence.checkpoints',subject.prominence.checkpoints]];if(kind==='world')return [['stateChanges',subject.stateChanges||[]],['faction.changes',subject.faction?.changes||[]],['faction.checkpoints',subject.faction?.checkpoints||[]]];return [['changes',subject.changes||[]]];}
history=function(kind,id){if(kind==='node'){consequenceDialog(W.events(p()).find(e=>e.nodeId===id)?.key||'');return;}const subject=historicalSubject(kind,id);if(!subject)return;modalData={kind:'history',subjectKind:kind,id};dialog('HISTORY',subject.name||subject.label,historicalRows(subject,kind).flatMap(([collection,rows])=>rows.map(x=>`<article class="history-row"><strong>${esc(x.status||x.block?.text||x.value||x.bond||human(collection.split('.').at(-1)))}</strong><small>${esc(momentOptions().find(y=>y[0]===(x.momentId||W.momentId(p(),x.at)))?.[1]||'Opening')}</small><p>${esc(x.reason||'')}</p>${btn('edit-historical-record','Edit change','edit',false,`data-kind="${kind}" data-id="${id}" data-collection="${collection}" data-record="${x.id}"`)}</article>`)).join('')||'<p>No timed changes yet.</p>',btn('new-history','Add change','plus',true,`data-kind="${kind}" data-id="${id}"`));};actions.history=el=>history(el.dataset.kind,el.dataset.id);
function editHistoricalRecord(kind,id,collection,recordId){const subject=historicalSubject(kind,id),rows=historicalRows(subject,kind).find(([name])=>name===collection)?.[1],x=rows?.find(x=>x.id===recordId);if(!x)return;modalData={kind:'historical-record',subjectKind:kind,id,collection,recordId};let body=select('At story moment','momentId',momentOptions().slice(1),x.momentId||W.momentId(p(),x.at));
 if(x.blocks){body+=x.blocks.map(b=>field(b.label||b.title||human(b.kind),'checkpoint-'+b.id,b.text,'','textarea')).join('');if(x.lifeStatus)body+=select('Life status','lifeStatus',[['alive','Alive'],['dead','Dead']],x.lifeStatus);}
 else if(kind==='character'&&collection==='changes'||collection==='faction.changes'){body+=select('Operation','operation',[['add','Gain piece'],['replace','Change piece'],['retire','Retire piece']],x.operation||(x.op==='develop'?'replace':x.op))+field('New words','text',x.block?.text||'','','textarea')+field('Detail','detail',x.block?.detail||'','','textarea');}
 else if(collection==='lifeChanges')body+=select('Life status','status',[['alive','Alive'],['dead','Dead']],x.status);
 else if(collection.startsWith('prominence.'))body+=field('Prominence','value',collection==='prominence.checkpoints'?x.value.value:x.value);
 else if(collection==='stateChanges')body+=field('New value','value',x.value)+select('Target','targetId',targetOptions(),x.targetId||'');
 else{const state=W.connectionState(p(),subject,x.momentId);body+=field('Connection','bond',x.bond??state.bond)+field('One wants','aWant',x.aWant??state.aWant)+field('Other wants','bWant',x.bWant??state.bWant)+field('Notes','notes',x.notes??state.notes,'','textarea')+connectionTermsFields({...state.terms,...x.terms});}
 body+=field('Reason','reason',x.reason||'','','textarea');dialog('REVISE A HISTORICAL RECORD',subject.name||subject.label,body,btn('remove-historical-record','Remove this change','trash')+submit('Keep revised change'),'historical-record');}
function connectionTermsFields(t={}){return disclosure('Terms at this moment',select('Membership','membership',['unspecified','member','associate','former','none'].map(x=>[x,human(x)]),t.membership||'unspecified')+field('Position','position',t.position||'')+select('Visibility','visibility',['open','concealed','contested'].map(x=>[x,human(x)]),t.visibility||'open')+field('First side’s tie','aTie',t.aTie||'')+field('Second side’s tie','bTie',t.bTie||'')+select('Supporting fact','factId',[['','None'],...p().world.filter(e=>e.type==='fact').map(e=>[e.id,e.name])],t.factId||'')+`<label><input name="active" type="checkbox" ${t.active!==false?'checked':''}> Active</label><label><input name="leadership" type="checkbox" ${t.leadership?'checked':''}> Leadership</label>`);}
const basicNewHistory=newHistory;newHistory=function(kind,id,key=''){basicNewHistory(kind,id,key);if(kind==='connection')$('#dialog .dialog-body').insertAdjacentHTML('beforeend',connectionTermsFields(W.connectionState(p(),historicalSubject(kind,id),key).terms));};actions['new-history']=el=>newHistory(el.dataset.kind,el.dataset.id);draftable.add('historical-record');
actions['edit-historical-record']=el=>editHistoricalRecord(el.dataset.kind,el.dataset.id,el.dataset.collection,el.dataset.record);
actions['remove-historical-record']=()=>{const m=modalData;if(mutate('Removed historical change',()=>{const subject=historicalSubject(m.subjectKind,m.id),keys=m.collection.split('.');let owner=subject;for(const key of keys.slice(0,-1))owner=owner[key];owner[keys.at(-1)]=owner[keys.at(-1)].filter(x=>x.id!==m.recordId);})){closeDialog();}};
const historicalSubmit=extraSubmit;extraSubmit=function(form,data,m){const v=k=>String(data.get(k)||'').trim(),terms=()=>({membership:v('membership'),position:v('position'),visibility:v('visibility'),aTie:v('aTie'),bTie:v('bTie'),factId:v('factId'),active:data.has('active'),leadership:data.has('leadership')});
 if(form.dataset.form==='historical-record'){if(!v('momentId'))throw Error('Choose a story moment.');if(mutate('Revised historical change',()=>{const subject=historicalSubject(m.subjectKind,m.id),x=historicalRows(subject,m.subjectKind).find(([name])=>name===m.collection)[1].find(x=>x.id===m.recordId);x.momentId=v('momentId');if(x.at)x.at=W.events(p()).find(e=>e.id===x.momentId).key;x.reason=v('reason');if(x.blocks){for(const b of x.blocks)b.text=v('checkpoint-'+b.id);if(data.has('lifeStatus'))x.lifeStatus=v('lifeStatus');}else if(data.has('operation')){const op=v('operation');if(m.subjectKind==='character'){x.op=op==='replace'?'develop':op;delete x.operation;}else x.operation=op;if(op==='retire')x.block=null;else{if(!x.block)throw Error('Restore this piece through a new change so its type and identity are explicit.');x.block.text=v('text');x.block.detail=v('detail');}}else if(data.has('status'))x.status=v('status');else if(data.has('value')){if(m.collection==='prominence.checkpoints')x.value={...x.value,value:v('value')};else x.value=v('value');if(data.has('targetId'))x.targetId=v('targetId');}else{for(const key of ['bond','aWant','bWant','notes'])x[key]=v(key);x.terms=terms();}}))closeDialog();return true;}
 if(form.dataset.form==='history-change'&&m.subjectKind==='connection'){if(!v('momentId'))throw Error('Choose a story moment.');if(mutate('Kept connection change',()=>{const r=historicalSubject('connection',m.id);r.changes||=[];const existing=r.changes.find(x=>x.momentId===v('momentId')),record={id:existing?.id||W.uid(),momentId:v('momentId'),bond:v('bond'),aWant:v('aWant'),bWant:v('bWant'),notes:v('notes'),reason:v('reason'),terms:terms()};if(existing)Object.assign(existing,record);else r.changes.push(record);}))closeDialog();return true;}
 return historicalSubmit(form,data,m);
};
const recoverSimpleDraft=actions['recover-draft'];
actions['recover-draft']=el=>{const d=p().drafts.find(x=>x.id===el.dataset.id);if(!d||d.form||d.kind==='scene'){recoverSimpleDraft(el);return;}const value=d.draft||{},cid=d.character||value.characterId||value.focus||'',id=value.id||value.entityId||value.targetId||'',moment=value.momentId||value.mid||d.preservedMomentId||'';let opened=true;
 if(d.kind==='name'&&person(cid))editCharacter(cid);
 else if(d.kind==='block'&&person(cid)){if(d.preservedMomentId)editChange(cid,value.id,W.events(p()).find(e=>e.id===d.preservedMomentId)?.key||'');else editBlock(cid,person(cid).blocks.some(b=>b.id===value.id)?value.id:'',value.kind||'custom');}
 else if(['connection','en-tie'].includes(d.kind))editConnection(p().connections.some(r=>r.id===id)?id:'');
 else if(['entity','en-faction-block'].includes(d.kind)){if(d.kind==='entity')editWorld(p().world.some(w=>w.id===id)?id:'');else if(p().world.some(w=>w.id===(value.entityId||id)))factionBlock(value.entityId||id,value.blockId||value.id);else opened=false;}
 else if(['life','entity-state','connection-change'].includes(d.kind))newHistory(d.kind==='life'?'character':d.kind==='entity-state'?'world':'connection',cid||d.entity||d.connection||id,moment);
 else if(d.kind==='earlier-opening'&&person(cid))earlierSelf(cid);
 else if(d.kind==='en-role')plotRole(value.plotId,cid);
 else if(d.kind==='evidence')evidenceEditor(d.thread||value.threadId,value.id);
 else opened=false;
 if(!opened){modalData={kind:'legacy-draft',id:d.id};dialog('RECOVERED WORK IN PROGRESS',human(d.kind),'<p>This unfinished record is preserved separately. Edit the original fields here, or export it for reference; your accepted story stays intact.</p>'+legacyDraftFields(value),submit('Keep recovered draft'),'legacy-draft');return;}
 const form=$('#dialog form');if(!form)return;const mapped={...value,label:value.label??value.title,pinned:value.pinned??value.locked,lifeStatus:value.lifeStatus??value.status,momentId:moment,preservedLabel:value.preservedLabel||'',earlierLabel:value.earlierLabel||''};for(const field of form.elements){if(!field.name||!(field.name in mapped))continue;const raw=mapped[field.name];if(field.type==='checkbox')field.checked=!!raw;else if(typeof raw==='string')field.value=raw;}
 activeFormDraft=d.id;captureFormDraft();
};
function legacyDraftFields(value,prefix=''){return Object.entries(value).filter(([key])=>!['id','sources','sourceHash','parentHash','ensembleSnapshot','blockSources'].includes(key)).map(([key,item])=>{const path=prefix?prefix+'.'+key:key;if(typeof item==='string'||typeof item==='number')return field(human(key),path,String(item),'',typeof item==='number'?'number':'textarea');if(typeof item==='boolean')return `<label class="check-chip"><input type="checkbox" name="${esc(path)}" ${item?'checked':''}>${esc(human(key))}</label>`;if(item&&typeof item==='object')return disclosure(human(key),legacyDraftFields(item,path));return '';}).join('');}
const recoveredDraftSubmit=extraSubmit;extraSubmit=function(form,data,m){if(form.dataset.form==='legacy-draft'){if(mutate('Kept recovered unfinished draft',()=>{const d=p().drafts.find(x=>x.id===m.id);for(const field of form.elements){if(!field.name)continue;const keys=field.name.split('.');if(keys.some(k=>['__proto__','prototype','constructor'].includes(k)))throw Error('Unsupported draft field.');let owner=d.draft;for(const key of keys.slice(0,-1))owner=owner[key];const last=keys.at(-1);owner[last]=field.type==='checkbox'?field.checked:field.type==='number'?Number(field.value):field.value;}d.updatedAt=new Date().toISOString();})){closeDialog();}return true;}return recoveredDraftSubmit(form,data,m);};
