const ORIGINAL_KINDS = {
    want: { label: 'Want', plural: 'Wants', prefix: 'Wants', symbol: '→', question: 'What do they want?', hint: 'A direction, not a whole biography.', description: 'Something they seek, keep, change, or escape.', detail: 'What would getting it look like?', options: [
            ['protect', 'Protect', 'Keep someone or something safe.'], ['escape', 'Escape', 'Get free of a situation or obligation.'], ['find', 'Find', 'Locate something missing or unknown.'], ['win', 'Win', 'Gain a position, contest, or opportunity.'], ['belong', 'Belong', 'Be accepted without pretending.'], ['understand', 'Understand', 'Make sense of something unresolved.'], ['repair', 'Repair', 'Put right something damaged.'], ['create', 'Create', 'Bring something into the world.'], ['keep', 'Keep', 'Hold on to what is already theirs.'], ['change', 'Change', 'Make a situation different.'], ['reveal', 'Reveal', 'Bring something hidden into the open.'], ['hide', 'Conceal', 'Keep something from being discovered.'], ['destroy', 'Destroy', 'End something they cannot tolerate.'], ['return', 'Return', 'Get back to a person, place, or former life.'], ['connect', 'Get closer', 'Make a real connection.'], ['release', 'Let go', 'Stop carrying what no longer serves them.'], ['experience', 'Experience', 'Feel, witness, or try something for itself.'], ['choose', 'Choose freely', 'Recover the right to decide.']
        ] },
    method: { label: 'Method', plural: 'Methods', prefix: 'Usually tries to', symbol: '↗', question: 'How do they go after it?', hint: 'The move they tend to make first.', description: 'A repeatable strategy, useful somewhere and costly elsewhere.', detail: 'When does this work or fail?', options: [
            ['trade', 'Trade favors', 'Turn usefulness into an exchange.'], ['control', 'Control information', 'Decide who learns what, and when.'], ['trust', 'Earn trust', 'Become someone others will rely on.'], ['charm', 'Use charm', 'Make people want to say yes.'], ['force', 'Apply pressure', 'Make refusal difficult or costly.'], ['rules', 'Follow the rules', 'Seek legitimacy and an established route.'], ['defy', 'Break the rules', 'Act outside a system that blocks them.'], ['care', 'Care for someone', 'Meet a real need before asking for anything.'], ['observe', 'Observe and wait', 'Notice what impatient people miss.'], ['cooperate', 'Cooperate', 'Make a plan people can pursue together.'], ['withdraw', 'Keep their distance', 'Protect room to think or avoid exposure.'], ['truth', 'Tell the truth', 'Give others the information to decide.'], ['conceal', 'Hide vulnerability', 'Keep weakness out of the transaction.'], ['humor', 'Use humor', 'Change the emotional terms of an encounter.'], ['experiment', 'Try an experiment', 'Test a small, reversible version first.'], ['endure', 'Outlast the pressure', 'Keep going when others would stop.'], ['ask', 'Ask for help', 'Accept dependence instead of disguising it.'], ['perform', 'Prove their worth', 'Let skill or accomplishment make the case.']
        ] },
    value: { label: 'Value', plural: 'Values', prefix: 'Values', symbol: '◇', question: 'What matters to them?', hint: 'Add more than one. Let them disagree.', description: 'A real commitment, not a virtue score.', detail: 'Who or what makes this personal?', options: [
            ['loyalty', 'Loyalty', 'Stand by a person or commitment.'], ['freedom', 'Freedom', 'Keep the ability to choose.'], ['care', 'Compassion', 'Take another person’s needs seriously.'], ['justice', 'Justice', 'Insist that wrongs and power be answered.'], ['dignity', 'Dignity', 'Refuse to treat people as disposable.'], ['security', 'Security', 'Build a life that is not always at risk.'], ['belonging', 'Belonging', 'Have somewhere to be fully known.'], ['curiosity', 'Curiosity', 'Pursue what is not yet understood.'], ['recognition', 'Recognition', 'Have their contribution seen.'], ['pleasure', 'Pleasure', 'Make room for delight and enjoyment.'], ['order', 'Order', 'Make the world predictable enough to trust.'], ['faith', 'Faith', 'Stay committed beyond what can be proved.'], ['mastery', 'Mastery', 'Do something exceptionally well.'], ['honesty', 'Honesty', 'Keep language and intention aligned.'], ['beauty', 'Beauty', 'Care about how life feels and looks.'], ['solidarity', 'Solidarity', 'Tie their well-being to other people’s.'], ['peace', 'Peace', 'Make space without domination or constant struggle.'], ['independence', 'Independence', 'Avoid having their choices owned by others.']
        ] },
    boundary: { label: 'Boundary', plural: 'Boundaries', prefix: 'Will not', symbol: '⊣', question: 'Where is their line?', hint: 'A refusal can protect them—or trap them.', description: 'What they refuse to do, even when refusal costs them.', detail: 'What might make holding this line costly?', options: [
            ['betray', 'Betray someone who trusts them', 'A relationship puts a limit on ambition.'], ['beg', 'Ask for what should be freely given', 'Pride or dignity closes an easy route.'], ['harm', 'Hurt someone uninvolved', 'Success cannot be paid for by a bystander.'], ['lie', 'Lie to someone they love', 'An intimate relationship needs honesty.'], ['abandon', 'Leave someone behind', 'They will not be the only one to escape.'], ['obey', 'Obey an order they believe is wrong', 'Authority cannot settle the question.'], ['depend', 'Become dependent on someone', 'Even offered help has a price.'], ['sell', 'Sell out their work', 'A standard they will not exchange for success.'], ['forgive', 'Pretend the harm never happened', 'Reconciliation cannot erase accountability.'], ['control', 'Take away another person’s choice', 'Care is not ownership.'], ['admit', 'Admit they were wrong', 'A limit that may be part of the problem.'], ['surrender', 'Give up without trying', 'Persistence protects hope, but may prolong damage.']
        ] },
    belief: { label: 'Belief', plural: 'Beliefs', prefix: 'Believes', symbol: '“', description: 'An operating rule. It may be true, false, partial, or useful.', detail: 'What experience makes this credible to them?', options: [
            ['needed', 'Being needed keeps me safe', 'Usefulness feels like protection.'], ['control', 'Someone must stay in control', 'Uncertainty feels irresponsible.'], ['truth', 'Truth gives people a choice', 'Information is a form of agency.'], ['mercy', 'Mercy leaves room for change', 'A person is not only their worst act.'], ['earned', 'Care has to be earned', 'Affection seems conditional.'], ['alone', 'Depending on people gives them power', 'Self-reliance feels safer.'], ['rules', 'The rules protect people like us', 'Legitimacy has real value to them.'], ['break', 'Some rules exist to keep us small', 'Disobedience can be self-respect.'], ['together', 'We survive by taking care of each other', 'Reciprocity makes risk bearable.'], ['cost', 'Every victory asks someone to pay', 'They look for the hidden payer.'], ['ordinary', 'An ordinary life is worth defending', 'Not everything must become an achievement.'], ['uncertain', 'I can act without being certain', 'Doubt need not mean paralysis.']
        ] },
    contradiction: { label: 'Competing selves', plural: 'Competing selves', prefix: 'Can be', symbol: '↔', description: 'Two real ways of being, brought out by different situations.', detail: 'What brings out each side?', options: [
            ['bold', 'Bold with strangers; careful with loved ones', 'Intimacy changes the stakes.'], ['gentle', 'Gentle in private; severe in public', 'Audience changes their behavior.'], ['generous', 'Generous with money; guarded with time', 'Giving does not mean the same thing everywhere.'], ['principled', 'Principled in theory; pragmatic for family', 'Commitments do not weigh equally.'], ['social', 'Socially effortless; privately lonely', 'Performance is not connection.'], ['fearless', 'Calm in danger; afraid of being known', 'Physical and emotional risk diverge.'], ['skeptical', 'Skeptical of authority; hungry for approval', 'They want something they distrust.'], ['patient', 'Patient with others; brutal with themself', 'Compassion has an exception.']
        ] },
    joy: { label: 'Ordinary life', plural: 'Ordinary life', prefix: 'Finds life in', symbol: '✳', description: 'Pleasure, play, habits, taste, and a life outside the plot.', detail: 'A concrete detail that makes it theirs', options: [
            ['make', 'Making things nobody asked for', 'Pleasure without a task or audience.'], ['food', 'Sharing a familiar meal', 'A small ritual of belonging.'], ['music', 'Playing with rhythm and sound', 'They notice a world others pass over.'], ['repair', 'Repairing small, broken things', 'Attention with a tangible result.'], ['walk', 'Walking without a destination', 'A way to be present rather than useful.'], ['tease', 'Affectionate teasing', 'A private language with someone else.'], ['collect', 'Collecting objects with no obvious value', 'Meaning need not be practical.'], ['routine', 'A carefully kept daily ritual', 'A modest pocket of continuity.'], ['animals', 'Being around animals', 'A relationship outside performance.'], ['games', 'Taking an unimportant game seriously', 'Competition without enormous stakes.'], ['garden', 'Tending something that grows', 'Care measured over time.'], ['story', 'Telling a story better each time', 'Memory as a shared pleasure.']
        ] },
    capability: { label: 'Ability & limit', plural: 'Abilities & limits', prefix: 'Can', symbol: '∴', description: 'A skill, advantage, or extraordinary power with an actual boundary.', detail: 'Hard limit, condition, or cost', options: [
            ['social', 'Read a room', 'Notice alliances, omissions, and discomfort.'], ['physical', 'Move where others cannot', 'An unusual physical route or aptitude.'], ['technical', 'Make a system do something unexpected', 'Knowledge creates access.'], ['memory', 'Remember what others overlook', 'Attention or memory becomes useful.'], ['status', 'Get through a closed door', 'Status or credentials confer access.'], ['language', 'Move between languages and worlds', 'Translation includes social context.'], ['care', 'Make people feel understood', 'Listening can change an encounter.'], ['improvise', 'Build something from what is at hand', 'Constraints become material.'], ['uncanny', 'Perceive something ordinarily hidden', 'An extraordinary ability; define its limits.'], ['endurance', 'Keep going past an ordinary limit', 'Specify what makes recovery necessary.']
        ] },
    obligation: { label: 'Obligation', plural: 'Obligations', prefix: 'Owes', symbol: '↩', description: 'A promise, debt, role, or duty that competes with a want.', detail: 'What comes due, and when?', options: [
            ['promise', 'A promise that has become costly', 'The old commitment still makes a claim.'], ['debt', 'A favor they have not repaid', 'Someone may now ask for it back.'], ['care', 'Care to someone who depends on them', 'A legitimate need outside their ambition.'], ['role', 'The duties of a role they accepted', 'An identity comes with work.'], ['repair', 'Repair for harm they caused', 'Responsibility is not just a feeling.'], ['inherit', 'A duty inherited from someone else', 'They did not choose the original agreement.'], ['deadline', 'A result by a particular time', 'Delay changes the available choices.'], ['silence', 'Keeping someone else’s confidence', 'Information cannot be spent freely.']
        ] },
    allegiance: { label: 'Allegiance', plural: 'Allegiances', prefix: 'Tied to', symbol: '⚑', description: 'An institution, community, cause, or chosen family.', detail: 'What do they give, and what do they receive?', options: [
            ['institution', 'An institution that gave them a place', 'Security and status can create loyalty.'], ['community', 'A community that needs them', 'Belonging is also responsibility.'], ['cause', 'A cause larger than their own comfort', 'A chosen commitment with consequences.'], ['family', 'A family with competing expectations', 'Love and obligation can disagree.'], ['profession', 'The standards of their work', 'Craft can demand refusal.'], ['patron', 'A patron whose help was not free', 'Gratitude and dependence overlap.'], ['outsiders', 'People the system leaves outside', 'Solidarity may cost access.'], ['self', 'No group they trust completely', 'Independence can be a position, not an absence.']
        ] },
    secret: { label: 'Private knowledge', plural: 'Private knowledge', prefix: 'Keeps private', symbol: '◒', description: 'Something hidden. A summary, not automatic viewpoint knowledge.', detail: 'Author-only truth or supporting detail', options: [
            ['identity', 'A concealed identity', 'Their public role omits something important.'], ['loyalty', 'An undisclosed allegiance', 'Someone has an incomplete picture of their loyalties.'], ['harm', 'Their part in an earlier harm', 'Responsibility has not been recognized.'], ['need', 'A need they cannot admit', 'They conceal something they want from others.'], ['evidence', 'Evidence someone else wants', 'Information has not yet been shared.'], ['love', 'A feeling they have not expressed', 'Silence is not the absence of attachment.'], ['doubt', 'Doubt beneath public certainty', 'Their performed position is not the whole truth.'], ['gift', 'An ability they keep hidden', 'Knowledge of the ability would change its value.']
        ] },
    experience: { label: 'Formative experience', plural: 'Formative experiences', prefix: 'Carries', symbol: '⌁', description: 'Something that shaped them. Not a compulsory wound or explanation.', detail: 'What did they take from it—and what else could it mean?', options: [
            ['victory', 'A victory won the wrong way', 'Success and discomfort share a memory.'], ['care', 'Care received when it was not earned', 'A counterexample to conditional affection.'], ['loss', 'A loss nobody could prevent', 'Not every harm has a villain.'], ['betrayal', 'Trust that was used against them', 'A strategy may have once been protective.'], ['recognition', 'Being seen at the right moment', 'Approval changed what seemed possible.'], ['failure', 'A public failure they survived', 'Shame and resilience may coexist.'], ['escape', 'Leaving a world they still miss', 'Freedom does not erase attachment.'], ['discovery', 'Discovering they were wrong', 'An unsettling experience of learning.']
        ] },
    custom: { label: 'Your own block', plural: 'Your own blocks', prefix: 'Also', symbol: '+', description: 'Anything this vocabulary misses. Define it on your terms.', detail: 'Context or detail', options: [] }
};