const {test}=require('node:test'),assert=require('node:assert/strict');
const W=require('../src/core.js'),SE=require('../tutorial/story-edits.js'),D=require('../tutorial/definition.js'),SM=require('../tutorial/studio-model.js');
const fs=require('node:fs'),path=require('node:path');
const definition=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../tutorial/MGS3 — Tutorial definition.json')));
function workspace(){const p=W.project('One');p.nodes=[{...W.node('C'),title:'First',opening:'An opening',closing:'An ending'}];return {format:'counterplot-workshop',schema:1,active:p.id,projects:[p]};}
function validProject(p){return W.validate({format:'counterplot-workshop',schema:1,active:p.id,projects:[p]});}
for(const field of ['title','opening','closing','notes','prose'])test('Scene edit round trip: '+field,()=>{const a=workspace().projects[0],b=W.copy(a);b.nodes[0][field]='Fan wording '+field;const patch=SE.diff(a,b),result=SE.apply(a,patch,{force:true});assert.deepEqual(result.project,b);assert.equal(a.nodes[0][field],field==='title'?'First':field==='opening'?'An opening':field==='closing'?'An ending':'');validProject(result.project);});
test('Unchanged partial scene does not delete invisible sample material',()=>{const d=definition(),scene=SM.expectedScene(d,0,0).workspace.projects[0];assert.deepEqual(SE.diff(scene,W.copy(scene)),[]);assert.equal(d.sample.nodes.length>scene.nodes.length,true);});
test('Scene three-way merge preserves learner wording',()=>{const a=workspace().projects[0],b=W.copy(a),learner=W.copy(a);b.nodes[0].opening='New author wording';learner.nodes[0].opening='My own wording';const result=SE.apply(learner,SE.diff(a,b));assert.equal(result.project.nodes[0].opening,'My own wording');assert.equal(result.skipped.length,1);});
test('Scene insertion, nested node and character changes are atomic and valid',()=>{const a=workspace().projects[0],b=W.copy(a),n=W.node('M',b.nodes[0].id),c=W.character('Snake');b.nodes.push(n);c.blocks.push(W.block('want'));b.characters.push(c);n.cast.push(c.id);const result=SE.apply(a,SE.diff(a,b));assert.deepEqual(result.project,b);validProject(result.project);});
test('Nested character fields preserve unrelated edits',()=>{const a=workspace().projects[0],c=W.character('Snake');c.blocks.push(W.block('want'),W.block('fear'));a.characters.push(c);const b=W.copy(a),learner=W.copy(a);b.characters[0].blocks[0].text='Authored want';learner.characters[0].blocks[1].text='Learner fear';const result=SE.apply(learner,SE.diff(a,b));assert.equal(result.project.characters[0].blocks[0].text,'Authored want');assert.equal(result.project.characters[0].blocks[1].text,'Learner fear');});
test('Scene reordering preserves unknown learner-created slots',()=>{const a=workspace().projects[0];a.nodes.push(W.node('I'),W.node('M'));const b=W.copy(a);b.nodes.reverse();const learner=W.copy(a),extra=W.node('E');learner.nodes.splice(1,0,extra);const result=SE.apply(learner,SE.diff(a,b));assert.equal(result.project.nodes[1].id,extra.id);assert.deepEqual(result.project.nodes.filter(n=>n.id!==extra.id).map(n=>n.id),b.nodes.map(n=>n.id));});
test('Learner reordering is not overwritten by author transition',()=>{const a=workspace().projects[0];a.nodes.push(W.node('I'),W.node('M'));const b=W.copy(a);b.nodes.reverse();const learner=W.copy(a);[learner.nodes[0],learner.nodes[1]]=[learner.nodes[1],learner.nodes[0]];assert.deepEqual(SE.apply(learner,SE.diff(a,b)).project,learner);});
test('Archive scene patch is reversible without removing archive contents',()=>{const a=workspace().projects[0],b=W.copy(a);W.archiveNode(b,b.nodes[0].id);const r=SE.apply(a,SE.diff(a,b),{force:true}).project;assert.deepEqual(r,b);validProject(r);assert.deepEqual(SE.apply(r,SE.diff(b,a),{force:true}).project,a);});
test('Consecutive field edits compact without erasing earlier fields',()=>{const a=workspace().projects[0],b=W.copy(a),c=W.copy(a);b.nodes[0].title='Two';c.nodes[0].title='Three';const patch=SE.append(SE.diff(a,b),SE.diff(b,c));assert.equal(patch.length,1);assert.deepEqual(SE.apply(a,patch).project,c);});
test('Prototype paths are rejected',()=>{for(const key of ['__proto__','constructor','prototype'])assert.throws(()=>SE.validate([{kind:'value',path:['nodes',{id:'safe'},key],had:false,has:true,value:{polluted:true}}]),/Unsafe/);assert.equal({}.polluted,undefined);});
test('Identity changes are rejected',()=>assert.throws(()=>SE.validate([{kind:'value',path:['nodes',{id:'safe'},'id'],had:true,before:'safe',has:true,value:'different'}]),/Unsafe/));
test('Scene edits survive definition validation and exact final-stage rendering',()=>{let d=definition();const a=SM.expectedScene(d,21,0).workspace.projects[0],b=W.copy(a);b.nodes[0].title='Winston’s Snake';b.nodes[0].closing='My ending';d.lessons[21].goals[0].storyEdits={enter:SE.diff(a,b)};d=D.validate(d,W);const actual=SM.expectedScene(d,21,0).workspace.projects[0];assert.equal(actual.nodes[0].title,b.nodes[0].title);assert.equal(actual.nodes[0].closing,b.nodes[0].closing);W.validate(SM.expectedScene(d,21,0).workspace);});
test('Entry, completion and exit story edits are separately represented',()=>{let d=definition(),l=d.lessons[21],g=l.goals[0];const a=SM.expectedScene(d,21,0).workspace.projects[0],b=W.copy(a);b.nodes[0].notes='On entry';g.storyEdits={enter:SE.diff(a,b)};const c=SM.expectedScene(d,21,0,'complete').workspace.projects[0],e=W.copy(c);e.nodes[0].notes='On completion';g.storyEdits.complete=SE.diff(c,e);const x=SM.expectedScene(d,21,0,'exit').workspace.projects[0],y=W.copy(x);y.nodes[0].notes='On Next';g.storyEdits.exit=SE.diff(x,y);d=D.validate(d,W);for(const [phase,text]of [['enter','On entry'],['complete','On completion'],['exit','On Next']])assert.equal(SM.expectedScene(d,21,0,phase).workspace.projects[0].nodes[0].notes,text);});
test('No default tutorial content is rewritten by scene editing',()=>{const d=definition(),sample=JSON.stringify(d.sample),a=SM.expectedScene(d,21,0).workspace.projects[0],b=W.copy(a);b.nodes[0].title='A human edit';d.lessons[21].goals[0].storyEdits={enter:SE.diff(a,b)};assert.equal(JSON.stringify(D.validate(d,W).sample),sample);});
test('Delete inactive story leaves active story and all its content untouched',()=>{const w=workspace(),p=W.project('Two');w.projects.push(p);const active=W.copy(w.projects[0]);W.trashProject(w,p.id);assert.equal(w.active,active.id);assert.deepEqual(w.projects[0],active);assert.deepEqual(w.trash[0].project,p);W.validate(w);});
test('Delete active story chooses another safely',()=>{const w=workspace(),p=W.project('Two');w.projects.push(p);const old=W.copy(w.projects[0]);W.trashProject(w,w.active);assert.equal(w.active,p.id);assert.deepEqual(w.trash[0].project,old);W.validate(w);});
test('Last story deletion gives a truly empty shelf, with restorable source',()=>{const w=workspace(),old=W.copy(w.projects[0]);W.trashProject(w,w.active);assert.equal(W.shelfProjects(w).length,0);assert.equal(w.projects.length,1);W.validate(w);const reloaded=W.validate(JSON.parse(JSON.stringify(w)));W.restoreProject(reloaded,old.id);assert.deepEqual(reloaded.projects,[old]);assert.equal(reloaded.active,old.id);assert.equal(reloaded.trash.length,0);});
test('Restoring deleted story keeps archived content, references and metadata intact',()=>{const w=workspace(),p=w.projects[0];p.tutorialId='mgs3';p.references=[{id:'r',title:'My source',url:'https://example.com',note:'Personal notes'}];W.archiveNode(p,p.nodes[0].id);const original=W.copy(p);W.trashProject(w,p.id);W.restoreProject(w,p.id);assert.deepEqual(w.projects[0],original);W.validate(w);});
test('Permanent deletion only removes selected trash entry',()=>{const w=workspace(),p=W.project('Two');w.projects.push(p);W.trashProject(w,w.active);const id=w.trash[0].project.id;W.purgeProject(w,id);assert.equal(w.trash.length,0);assert.deepEqual(w.projects,[p]);W.validate(w);});
test('Trash contents are validated on reload/import, not treated as an opaque stash',()=>{const w=workspace();W.trashProject(w,w.active);w.trash[0].project.nodes[0].parentId='missing-parent';assert.throws(()=>W.validate(w),/containing/);});
test('Trash cannot collide with a live story identity',()=>{const w=workspace();w.trash=[{project:W.copy(w.projects[0]),deletedAt:new Date().toISOString()}];assert.throws(()=>W.validate(w),/Duplicate/);});
test('An invalid deleted story timestamp is rejected',()=>{const w=workspace();W.trashProject(w,w.active);w.trash[0].deletedAt='invalid';assert.throws(()=>W.validate(w),/Invalid deleted/);});
test('Recovery shelf has a non-destructive safety limit',()=>{const w=workspace();w.trash=Array.from({length:200},()=>({project:W.project('Old'),deletedAt:new Date().toISOString()}));const before=W.copy(w);assert.throws(()=>W.trashProject(w,w.active),/full/);assert.deepEqual(w,before);});
test('Old visible editor recovery becomes an independent full tutorial',()=>{const d=definition(),w=SM.expectedScene(d,21,0).workspace,old=JSON.stringify(d);w.projects[0].nodes[0].title='Recovered fan version';w.projects[0].nodes[0].closing='Still visible';const r=SM.recoverDefinition({format:'counterplot-tutorial-recovery',version:1,definition:d,scene:w,index:21,step:0,phase:'enter'});assert.notEqual(r.definition.id,'mgs3');assert.equal(JSON.stringify(d),old);const visible=SM.expectedScene(r.definition,r.index,r.step,r.phase).workspace;assert.equal(visible.projects[0].nodes[0].closing,'Still visible');assert.equal(visible.projects[0].nodes[0].title,'Recovered fan version');W.validate(visible);});
test('Recovery respects completed and exit phases without changing entry',()=>{for(const phase of ['complete','exit']){const d=definition(),w=SM.expectedScene(d,21,0,phase).workspace;w.projects[0].nodes[0].notes='Recovery at '+phase;const r=SM.recoverDefinition({format:'counterplot-tutorial-recovery',version:1,definition:d,scene:w,index:21,step:0,phase});assert.equal(r.phase,phase);assert.equal(SM.expectedScene(r.definition,21,0,phase).workspace.projects[0].nodes[0].notes,'Recovery at '+phase);assert.notEqual(SM.expectedScene(r.definition,21,0,'enter').workspace.projects[0].nodes[0].notes,'Recovery at '+phase);}});
test('Recovery rejects malformed scene without touching definition',()=>{const d=definition(),w=SM.expectedScene(d,21,0).workspace,old=JSON.stringify(d);w.projects[0].nodes[0].parentId='nonexistent';assert.throws(()=>SM.recoverDefinition({format:'counterplot-tutorial-recovery',version:1,definition:d,scene:w,index:21,step:0}));assert.equal(JSON.stringify(d),old);});

test('Permanent archived removal remains part of the authored scene',()=>{const d=definition(),a=SM.expectedScene(d,21,0).workspace.projects[0],b=W.copy(a),n=b.nodes.find(n=>n.type==='B');W.archiveNode(b,n.id);W.purgeArchive(b,[b.archive.find(x=>x.nodes?.some(y=>y.id===n.id)).id]);const result=SE.apply(a,SE.diff(a,b),{force:true}).project;assert.deepEqual(result,b);assert.ok(result.tutorialRemoved.includes(n.id));const box=SM.expectedScene(d,21,0).workspace;box.projects=[result];W.validate(box);});
test('Authored removal markers merge with unrelated learner removals',()=>{const a=workspace().projects[0],b=W.copy(a),learner=W.copy(a);b.tutorialRemoved=['author-removed'];learner.tutorialRemoved=['learner-removed'];assert.deepEqual(SE.apply(learner,SE.diff(a,b)).project.tutorialRemoved,['learner-removed','author-removed']);assert.throws(()=>SE.validate([{kind:'value',path:['tutorialRemoved'],had:false,has:true,value:'bad'}]),/removal/);});
