const test=require('node:test'),assert=require('node:assert/strict');
const W=require('../src/integration.js');
function fixture(){const p=W.project('A sequence');const outer=W.node('C'),inner=W.node('E',outer.id),beat=W.node('B',inner.id),last=W.node('B');outer.id='outer';inner.id='inner';inner.parentId=outer.id;beat.id='beat';beat.parentId=inner.id;last.id='last';outer.closing='A changed person';inner.closing='The chase ends';p.nodes=[outer,inner,beat,last];return p;}
const wrap=p=>({format:'counterplot-workshop',schema:2,active:p.id,projects:[p]});
test('existing nesting gains closing positions without changing reading order or chronology',()=>{const p=fixture();W.normalize(p);assert.deepEqual(p.readingSequence,['outer:open','inner:open','beat:open','inner:close','outer:close','last:open']);const timeline=W.copy(p.timeline),reading=W.copy(p.readingOrder);delete p.readingSequence;W.validate(wrap(p));assert.deepEqual(p.timeline,timeline);assert.deepEqual(p.readingOrder,reading);assert.equal(W.readingMoments(p).filter(x=>x.edge==='close').length,2);});
test('custom legacy reading order survives the addition of closing moments',()=>{const p=fixture();p.readingOrder=['last','beat','inner','outer'];W.normalize(p);assert.deepEqual(p.readingOrder,['last','beat','inner','outer']);assert.deepEqual(W.readingMoments(p).filter(x=>x.edge==='open').map(x=>x.node.id),p.readingOrder);});
test('closing positions reorder independently, survive reload, and never retime history',()=>{const p=fixture();W.normalize(p);const timeline=W.copy(p.timeline),nodes=W.copy(p.nodes),reading=W.copy(p.readingOrder);W.reorder(p,'readingSequence','inner:close','beat:open');const restored=W.validate(JSON.parse(JSON.stringify(wrap(p)))).projects[0];assert.deepEqual(restored.readingSequence,p.readingSequence);assert.deepEqual(restored.timeline,timeline);assert.deepEqual(restored.nodes,nodes);assert.deepEqual(restored.readingOrder,reading);W.reorder(restored,'readingSequence','last:open','outer:open');assert.equal(W.reading(restored)[0].id,'last');assert.deepEqual(restored.timeline,timeline);});
test('archive, restore, rekey, and permanent deletion preserve valid moment references',()=>{const p=fixture();W.normalize(p);const before=W.copy(p.readingSequence);W.archiveNode(p,'inner');W.validate(wrap(p));assert.equal(W.readingMoments(p).some(e=>e.node.id==='inner'),false);W.restore(p,p.archive[0].id);W.validate(wrap(p));assert.deepEqual(p.readingSequence,before);W.rekeyEntity(p,'node','inner','renamed');W.validate(wrap(p));assert(p.readingSequence.includes('renamed:close'));W.archiveNode(p,'renamed');W.purgeArchive(p,[p.archive[0].id]);W.validate(wrap(p));assert(!p.readingSequence.some(key=>key.startsWith('renamed:')||key.startsWith('beat:')));});
test('new pieces and continuation remain consistent with manuscript order',()=>{const p=fixture();W.normalize(p);const n=W.node('B','inner');p.nodes.push(n);W.validate(wrap(p));assert.equal(p.readingSequence.filter(key=>key===n.id+':open').length,1);const next=W.continueScene(p,'beat');W.validate(wrap(p));assert.equal(W.reading(p)[W.reading(p).findIndex(n=>n.id==='beat')+1].id,next.id);assert.deepEqual(W.readingMoments(p).filter(x=>x.edge==='open').map(x=>x.node.id),p.readingOrder);});
test('invalid and duplicate sequence references are rejected',()=>{for(const keys of [['missing:close'],['outer:wrong'],['outer:open','outer:open']]){const p=fixture();p.readingSequence=keys;assert.throws(()=>W.validate(wrap(p)),/Reading sequence|reading moment|reading position/);}});

test('piece-order edits from older tabs keep saved closing positions',()=>{const p=fixture();W.normalize(p);W.reorder(p,'readingSequence','inner:close','beat:open');const closes=p.readingSequence.map((key,i)=>key.endsWith(':close')?[i,key]:null).filter(Boolean);p.readingOrder=['last','outer','inner','beat'];W.validate(wrap(p));assert.deepEqual(W.readingMoments(p).filter(x=>x.edge==='open').map(x=>x.node.id),p.readingOrder);assert.deepEqual(p.readingSequence.map((key,i)=>key.endsWith(':close')?[i,key]:null).filter(Boolean),closes);});
