const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),W=require('../src/core.js'),{data}=require('../tutorial/mgs3-project.cjs'),lessons=require('../tutorial/lessons.cjs');
const p=data.projects[0],c=id=>p.characters.find(c=>c.id===id),n=id=>p.nodes.find(n=>n.id===id);
test('MGS3 project validates with all four MICE kinds and a character frame',()=>{W.validate(data);assert.equal(p.nodes[0].type,'C');assert.equal(p.nodes[0].id,'loyalty');assert.equal(W.events(p).at(-2).key,'loyalty:close');assert.equal(W.events(p).at(-1).node.id,'call');assert.deepEqual([...new Set(p.nodes.map(n=>n.type))].sort(),['B','C','E','I','M'])});
test('MICE threads carry the structure with only three optional beat cards',()=>{const ids=W.ordered(p).map(x=>x.node).filter(n=>n.type==='B').map(n=>n.id);assert.deepEqual(ids,['escort','award','call']);assert.equal(p.nodes.filter(n=>n.type!=='B').length,29);assert.ok(n('drop').prose);assert.ok(n('inquiry').closing.includes('recording'));});
test('Snake gains knowledge, loses an objective, and acquires his title at their moments',()=>{const blocks=at=>W.stateAt(p,c('snake'),at);assert.ok(blocks('bridge:close').find(b=>b.id==='snake-belief').text.includes('against'));assert.ok(!blocks('torture:close').some(b=>b.id==='snake-duty'));assert.ok(blocks('torture:close').find(b=>b.id==='snake-body').text.includes('Right eye'));assert.ok(!blocks('inquiry:close').some(b=>b.id==='snake-bigboss'));assert.ok(blocks('award:open').some(b=>b.id==='snake-bigboss'));assert.equal(W.review(p,c('snake')).length,0)});
test('Secret allegiances precede their reveals; the audience coda is not Snake knowledge',()=>{assert.ok(c('boss').blocks.some(b=>b.text==='The defection is a cover.'));assert.ok(c('eva').blocks.some(b=>b.text==='Chinese operative.'));assert.ok(!c('eva').changes.some(x=>x.blockId==='eva-secret'));assert.ok(!c('snake').changes.some(x=>x.at==='call:open'));for(const x of p.characters)assert.equal(W.review(p,x).length,0)});
test('Every cast, world, relationship, and lesson target resolves',()=>{for(const x of p.nodes){x.cast.forEach(id=>assert.ok(c(id)));x.worldIds.forEach(id=>assert.ok(p.world.some(w=>w.id===id)))}for(const r of p.connections){assert.ok(c(r.a));assert.ok(c(r.b))}for(const l of lessons){const t=l.target;if(t.piece)assert.ok(require('../tutorial/construction.js').teachingSample(p).nodes.find(n=>n.id===t.piece));if(t.world)assert.ok(p.world.some(w=>w.id===t.world));if(t.character)assert.ok(c(t.character));if(t.block)assert.ok(c(t.character).blocks.some(b=>b.id===t.block));if(t.time)assert.ok(W.events(p).some(e=>e.key===t.time));assert.ok(l.steps.length>=1&&l.steps.length<=4);assert.equal(l.goals.length,l.steps.length)}});
test('Every guide lesson stays short enough for its companion panel',()=>{for(const l of lessons){const count=[l.intro,...l.steps,l.look,l.why,l.notice||''].join(' ').split(/\s+/).length;assert.ok(count<225,`${l.title}: ${count} words`);for(const step of l.steps)assert.ok(step.split(/\s+/).length<43,l.title)}});
test('Practice archive is explicitly separate from canon and can be restored and purged',()=>{const x=W.copy(data);W.restore(x.projects[0],'archive-alternate');W.validate(x);assert.ok(x.projects[0].nodes.find(n=>n.id==='practice-quiet').notes.includes('NON-CANON'));W.purgeArchive(x.projects[0],['archive-practice']);W.validate(x);assert.equal(x.projects[0].archive.length,0)});
test('Tutorial uses byte-identical base app script and styles',()=>{const base=fs.readFileSync(path.join(__dirname,'../Counterplot Workshop.html'),'utf8'),tour=fs.readFileSync(path.join(__dirname,'../tutorial/MGS3 — Counterplot tutorial.html'),'utf8');const app=s=>s.match(/<script>([\s\S]*?)<\/script>/)[1];const style=s=>s.match(/<style>([\s\S]*?)<\/style>/)[1];assert.equal(app(tour),app(base));assert.equal(style(tour),style(base));assert.ok(tour.includes('id="tutorial-data"'));assert.ok(base.includes('id="tutorial-data"'));const embedded=s=>JSON.parse(s.match(/<script type="application\/json" id="embedded-workspace">([\s\S]*?)<\/script>/)[1]);assert.equal(embedded(base),null);assert.equal(embedded(tour).tutorialBuild,true)});
test('Tutorial images, colors, and references survive export-shaped JSON copies',()=>{const x=JSON.parse(JSON.stringify(data));W.validate(x);assert.ok(c('snake').references.some(r=>r.image.startsWith('data:image/png')));assert.ok(n('loyalty').references.some(r=>r.image.startsWith('data:image/png')));assert.ok(JSON.stringify(data).length*2<2800000,'Room for a working copy and a new compressed portrait')});

test('All seventeen characters have real Delta portraits; Raikov participates in the access thread',()=>{assert.equal(p.characters.length,17);for(const c of p.characters)assert.ok(c.portrait.startsWith('data:image/png;base64,'));assert.ok(n('capture').cast.includes('raikov'));assert.ok(p.connections.some(r=>r.b==='raikov'));});
test('Tutorial cleanup removes other projects, retains revised edits, and stays scoped to its save',()=>{const vm=require('node:vm'),old=W.copy(data);old.projects[0].title='My revised outline';old.projects.push({...W.copy(old.projects[0]),id:'old-edition'});old.active='old-edition';const el={textContent:JSON.stringify(data)};let saved;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../tutorial/upgrade.js'),'utf8'),{Workshop:W,document:{getElementById:()=>el},localStorage:{getItem:key=>{assert.equal(key,data.saveKey);return JSON.stringify(old)},setItem:(key,value)=>{assert.equal(key,data.saveKey);saved=value}}});const result=JSON.parse(saved);assert.equal(result.projects.length,1);assert.equal(result.projects[0].title,'My revised outline');assert.equal(result.active,p.id);assert.equal(result.tutorialShelfVersion,1);});
test('Tutorial cleanup installs current edition when only an obsolete edition exists',()=>{const vm=require('node:vm'),old=W.copy(data);old.projects[0].id='old-edition';old.active='old-edition';const el={textContent:JSON.stringify(data)};let saved;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../tutorial/upgrade.js'),'utf8'),{Workshop:W,document:{getElementById:()=>el},localStorage:{getItem:()=>JSON.stringify(old),setItem:(key,value)=>saved=value}});assert.equal(JSON.parse(saved).projects.length,1);assert.equal(JSON.parse(saved).active,p.id)});
test('Tutorial cleanup runs once, preserving projects added afterward',()=>{const vm=require('node:vm'),old=W.copy(data);old.tutorialShelfVersion=1;old.projects.push({...W.copy(old.projects[0]),id:'later-copy'});const el={textContent:JSON.stringify(data)};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../tutorial/upgrade.js'),'utf8'),{Workshop:W,document:{getElementById:()=>el},localStorage:{getItem:()=>JSON.stringify(old),setItem:()=>assert.fail('Must not delete new work on reload')}})});
test('Missions are consecutive sibling Milieus and bosses are ordered',()=>{assert.equal(n('drop').type,'M');assert.equal(n('jungle').type,'M');assert.equal(n('drop').parentId,n('jungle').parentId);const order=W.ordered(p).map(x=>x.node.id);const bosses=['ocelot-duel','pain-fight','fear-fight','end-fight','fury-fight','sorrow-fight','volgin-fight','shagohod-fight','flowers-scene','aircraft-duel'];for(let i=1;i<bosses.length;i++)assert.ok(order.indexOf(bosses[i])>order.indexOf(bosses[i-1]));for(const id of ['pain','fear','end','fury','sorrow','johnny'])assert.ok(c(id));});

const checks=require('../tutorial/checks.js');
test('Guided edit has at most 22 tasks and no manual completion control',()=>{assert.equal(lessons.length,22);assert.ok(lessons.every(l=>l.goals.every(g=>g.focus&&g.check&&g.text)));assert.ok(!fs.readFileSync(path.join(__dirname,'../tutorial/guide.js'),'utf8').includes('guide-done'))});
test('Guide edit checks reject unchanged and empty values and require saved target changes',()=>{const rule={kind:'edit',entity:'node',id:'end-fight',field:'opening'},base=checks.value(data,rule);assert.equal(checks.completed(rule,base,base),false);assert.equal(checks.completed(rule,base,''),false);assert.equal(checks.completed(rule,base,base+' \n\t'),false);assert.equal(checks.completed(rule,base,' \n '),false);const w=W.copy(data);w.projects[0].nodes.find(n=>n.id==='end-fight').opening='Snake must locate The End.';assert.equal(checks.completed(rule,base,checks.value(w,rule)),true);assert.equal(checks.completed(rule,base,null),false)});
test('Guide validates the specific clicked control and before/after order',()=>{const rule={kind:'action',action:'fold',id:'loyalty'};assert.equal(checks.completed(rule,null,null,{action:'fold',id:'crisis'}),false);assert.equal(checks.completed(rule,null,null,{action:'fold',id:'loyalty'}),true);const w=W.copy(data),before=checks.value(w,{kind:'order'});W.move(w.projects[0],'end-fight','fear-fight','before');const after=checks.value(w,{kind:'order'});assert.ok(checks.completed({kind:'order'},before,after));assert.equal(checks.completed({kind:'restore-order'},after,after,{action:'undo'},before),false);assert.ok(checks.completed({kind:'restore-order'},after,before,{action:'undo'},before));});
test('Guide creation checks require added data, not an open form',()=>{assert.equal(checks.completed({kind:'count'},2,2),false);assert.ok(checks.completed({kind:'count'},2,3));assert.equal(checks.completed({kind:'reference'},['one'],['one']),false);assert.ok(checks.completed({kind:'reference'},['one'],['one','two']));});

const construction=require('../tutorial/construction.js');
test('Construction starts empty and keeps its own save',()=>{const w=construction.starter(data);W.validate(w);assert.notEqual(w.saveKey,data.saveKey);for(const key of ['nodes','characters','world','connections','archive'])assert.equal(w.projects[0][key].length,0);assert.ok(w.tutorialBuild)});
test('Staged construction reaches the full story while preserving learner edits',()=>{const w=construction.starter(data),p=w.projects[0];for(const stage of ['bridge','orders','middle']){construction.assemble(p,data.projects[0],stage);W.validate(w)}assert.ok(!p.nodes.some(n=>n.id==='escort'));const escort=W.copy(data.projects[0].nodes.find(n=>n.id==='escort'));escort.prose='My staging choice.';p.nodes.push(escort);construction.assemble(p,data.projects[0],'finalfight');assert.ok(p.nodes.findIndex(n=>n.id==='flowers-scene')<p.nodes.findIndex(n=>n.id==='escort'));p.nodes.find(n=>n.id==='loyalty').opening='My revised opening.';p.characters[0].blocks[0].text='My objective.';construction.assemble(p,data.projects[0],'complete');W.validate(w);assert.equal(p.nodes.length,34);assert.equal(p.characters.length,17);assert.equal(p.nodes.find(n=>n.id==='escort').prose,'My staging choice.');assert.equal(p.nodes.find(n=>n.id==='loyalty').opening,'My revised opening.');assert.equal(p.characters[0].blocks[0].text,'My objective.');for(const c of p.characters)assert.equal(W.review(p,c).length,0);const before=JSON.stringify(p);construction.assemble(p,data.projects[0],'complete');assert.equal(JSON.stringify(p),before)});
test('Construction checks require the requested link, archive, and timed change',()=>{const w=construction.starter(data),p=w.projects[0];construction.assemble(p,data.projects[0],'bridge');const rule={kind:'timed-change',character:'snake',block:'snake-belief',at:'bridge:close'};assert.equal(checks.completed(rule,[],checks.value(w,rule)),false);p.characters.find(c=>c.id==='snake').changes.push(W.copy(c('snake').changes.find(x=>x.id==='s-belief-bridge')));assert.equal(checks.completed(rule,[],checks.value(w,rule)),true);W.archiveNode(p,'bridge');assert.equal(checks.value(w,{kind:'archived',id:'bridge'}),true);assert.equal(checks.value(w,{kind:'restored',id:'bridge'}),false);W.restore(p,p.archive[0].id);assert.equal(checks.value(w,{kind:'restored',id:'bridge'}),true)});

test('Opening lessons build C E M I and defer mission closings',()=>{const sample=construction.teachingSample(p),node=id=>sample.nodes.find(n=>n.id===id);assert.deepEqual(lessons.slice(0,4).map(l=>l.goals[0].check.type),['C','E','M','I']);for(const lesson of lessons.slice(1,4))assert.deepEqual(lesson.goals.map(g=>g.nodeFields),[['title'],['opening']]);assert.equal(node('drop').parentId,'defection');assert.equal(node('mission-question').parentId,'drop');assert.equal(node('defection').closing,'Sokolov is unable to defect.');assert.deepEqual(lessons.find(l=>l.id==='bridge-change').goals.slice(0,3).map(g=>g.check.id),['mission-question','drop','defection']);const w=construction.starter(data);construction.assemble(w.projects[0],sample,'complete');W.validate(w);});
