import { test, expect } from '@playwright/test';
const base=process.env.TEST_SERVER_URL;
test.use({ignoreHTTPSErrors:true});
test('account recovery enrolls, rotates, resets once, revokes sessions and retains writing',async({page,browser})=>{
 test.skip(!base,'Requires an isolated local Pages/D1 server via TEST_SERVER_URL');
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const email=`recovery-${crypto.randomUUID()}@example.test`,password='Initial private password 123',nextPassword='Recovered private password 456';
 await page.goto(base);await page.getByRole('button',{name:'New here? Create an account'}).click();await page.locator('[name=email]').fill(email);await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'Create account ↗',exact:true}).click();
 await expect(page.locator('.sync-panel')).toBeHidden();await page.locator('[data-action=new-blank-scene]').click();await page.locator('[data-draft=notes]').fill('The original story must survive account recovery.');await page.locator('[data-action=save-scene]').click();await page.evaluate(()=>counterplotSync.flush());
 const other=await browser.newContext({ignoreHTTPSErrors:true});const second=await other.newPage();await second.goto(base);await second.locator('[name=email]').fill(email);await second.locator('[name=password]').fill(password);await second.getByRole('button',{name:'Sign in ↗',exact:true}).click();await expect(second.locator('.sync-panel')).toBeHidden();
 await page.locator('.account-button:visible').first().click();await page.getByRole('button',{name:'Manage recovery codes',exact:true}).click();await page.locator('[name=password]').fill('Wrong password');await page.getByRole('button',{name:'Generate recovery codes'}).click();await expect(page.locator('.auth-error')).toHaveText('Password did not match');await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'Generate recovery codes'}).click();await expect(page.locator('.recovery-codes')).toBeVisible();const oldCodes=(await page.locator('.recovery-codes').innerText()).split('\n');expect(oldCodes).toHaveLength(8);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download codes',exact:true}).click();expect((await download).suggestedFilename()).toBe('counterplot-recovery-codes.txt');await page.getByRole('button',{name:'I saved these codes'}).click();await page.getByRole('button',{name:'Back to writing',exact:true}).click();
 await page.locator('.account-button:visible').first().click();await page.getByRole('button',{name:'Manage recovery codes',exact:true}).click();await expect(page.locator('.sync-panel')).toContainText('8 unused codes');await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'Generate recovery codes'}).click();await expect(page.locator('.recovery-codes')).toBeVisible();const codes=(await page.locator('.recovery-codes').innerText()).split('\n');expect(codes).not.toEqual(oldCodes);await page.getByRole('button',{name:'I saved these codes'}).click();await page.getByRole('button',{name:'Back to writing',exact:true}).click();
 await page.locator('.account-button:visible').first().click();await page.getByRole('button',{name:'Sign out on this device',exact:true}).click();await page.getByRole('button',{name:'Recover with a saved code'}).click();await page.locator('[name=email]').fill(email);await page.locator('[name=code]').fill(oldCodes[0]);await page.locator('[name=password]').fill(nextPassword);await page.getByRole('button',{name:'Reset password',exact:true}).click();await expect(page.locator('.auth-error')).toContainText('did not match');await page.locator('[name=code]').fill(codes[0]);await page.getByRole('button',{name:'Reset password',exact:true}).click();await expect(page.locator('.sync-panel h1')).toHaveText('Password changed.');
 expect((await second.request.get(base+'/api/auth/session')).status()).toBe(401);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('[name=email]').fill(email);await page.locator('[name=password]').fill(nextPassword);await page.getByRole('button',{name:'Sign in ↗',exact:true}).click();await expect(page.locator('.sync-panel')).toBeHidden();expect(await page.evaluate(()=>counterplotDiagnostics.snapshot().projects[0].scenes[0].notes)).toBe('The original story must survive account recovery.');
 expect((await page.request.post(base+'/api/auth/reset',{headers:{Origin:base},data:{email,code:codes[0],password:nextPassword+' again'}})).status()).toBe(400);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await other.close();
});
