// Tutorial content only; shared application behavior is unchanged.
module.exports=(p,W,img,ref)=>{
 const old=new Map(p.nodes.map(n=>[n.id,n]));p.nodes=[];
 const add=(id,type,parentId,title,opening,closing,cast,worldIds,notes='')=>{const n={...W.node(type,parentId),...(old.get(id)||{}),id,type,parentId,title,opening,closing,cast,worldIds,notes,status:'planned'};p.nodes.push(n);return n;};
 add('loyalty','C','','Snake becomes Big Boss','Snake is a FOX operative who trusts The Boss, his former instructor.','After killing The Boss and learning her true orders, Snake accepts the title Big Boss and visits her grave.',['snake','boss'],[],'Character interpretation: the ending shows Snake grieving for his mentor and questioning how his country treated her. MGS3 does not establish every decision he makes in later games.');
 add('inquiry','I','loyalty','Why does The Boss defect?','The Boss discusses loyalty with Snake before the mission. Her later defection leaves him trying to understand her actions.','EVA’s recording explains that The Boss was following American orders. Her defection was a cover to recover the Philosophers’ Legacy.',['snake','boss','eva'],['legacy'],'This question spans both missions. The recording answers it after Snake has already killed The Boss. Snake cannot act on information he has not received.');
 add('drop','M','inquiry','Virtuous Mission','Snake parachutes into Tselinoyarsk to extract Sokolov.','The extraction fails. Snake leaves Soviet territory injured after The Boss takes Sokolov and Volgin launches a nuclear weapon.',['snake','zero','boss','paramedic','sokolov'],['tsel','radio'],'This is the first visit to Soviet territory. Its departure closes this Milieu. Operation Snake Eater begins a separate visit.').prose='Snake lands in the forest and retrieves his equipment from a tree. He contacts Major Zero and heads toward Rassvet to find Sokolov.';
 add('sokolov-rescue','E','drop','Rescue Sokolov at Rassvet','Sokolov is being held at a ruined factory. Snake must reach him before taking him to the extraction point.','Snake finds Sokolov and defeats Ocelot’s unit. He escorts Sokolov toward the bridge.',['snake','sokolov','ocelot'],['rassvet','shagohod'],'Sokolov identifies the Shagohod as the weapon he has been forced to develop. Snake criticizes Ocelot’s pistol technique during their first confrontation.');
 add('bridge','C','drop','The Boss turns against Snake','Snake expects The Boss to help him complete the rescue.','The Boss announces her defection, breaks Snake’s arm, and throws him from the bridge. Snake now believes she is working against him.',['snake','boss','sokolov','volgin','pain','fear','end','fury'],['tsel','cobras'],'The Cobras help take Sokolov. The change recorded here concerns Snake’s belief; The Boss’s actual allegiance has not changed.');
 add('nuclear-launch','E','drop','Volgin launches an American nuclear weapon','The Boss brings American nuclear weapons as part of her apparent defection. Volgin takes one.','Volgin destroys the research facility with it. Its American origin implicates the United States and prompts a new mission.',['volgin','boss','snake'],['coldwar'],'This local Event ends with the launch and its immediate consequences. The broader political crisis continues after Snake’s evacuation.');
 add('jungle','M','inquiry','Operation Snake Eater','A week later, Snake returns to Soviet territory to rescue Sokolov, destroy the Shagohod, and kill Volgin and The Boss.','Snake and EVA leave Soviet territory in an aircraft after completing the operation.',['snake','eva','zero','paramedic','sigint'],['tsel','radio','survival'],'The second mission is a sibling of Virtuous Mission. Its nested threads cover events during this second visit.');
 add('crisis','E','jungle','Complete the mission and resolve the crisis','The United States must prove it was not responsible for the nuclear attack. Snake is ordered to eliminate The Boss and stop Volgin’s weapon program.','Snake destroys the Shagohod and kills The Boss. Volgin is defeated, and the United States can deny involvement in her defection.',['snake','boss','volgin','zero'],['coldwar','shagohod'],'This Event covers the mission objectives. The surrounding Milieu remains open until Snake leaves Soviet territory.');
 add('return','E','crisis','Continue after The Boss intercepts Snake','The Boss confronts Snake shortly after his second insertion and orders him to leave.','She disarms him, but he continues to the rendezvous at Rassvet.',['snake','boss'],['tsel'],'Her ability to defeat Snake establishes the training he must overcome in the final fight.');
 add('eva-contact','I','crisis','Find the contact at Rassvet','Snake expects to meet an operative called ADAM.','EVA arrives instead, identifies herself as his contact, and provides equipment and information.',['snake','eva'],['rassvet'],'She is useful to Snake, but her claimed identity remains unverified. Her real employer is revealed in the final recording.');
 add('ocelot-unit','E','crisis','Escape the Ocelot Unit at Rassvet','Ocelot and his soldiers surround the factory where Snake has met EVA.','Snake defeats the soldiers and leaves Rassvet. EVA gets away.',['snake','eva','ocelot'],['rassvet'],'This is the unit encounter before Snake’s one-on-one duel with Ocelot.');
 add('revolvers','C','crisis','Ocelot adopts Snake’s advice','Snake criticizes Ocelot’s handling of an automatic pistol during their first meeting.','Ocelot returns with revolvers and challenges Snake again. He has changed his equipment in response to the criticism.',['snake','ocelot'],[],'This small Character thread concerns a specific change in technique. It does not claim that Ocelot’s motives or loyalties have changed.');
 add('ocelot-duel','E','revolvers','Boss encounter · Ocelot','Ocelot stops Snake at Bolshaya Past and challenges him to a revolver duel.','Snake wins the duel. Hornets interrupt the aftermath, and Snake falls into the caves.',['snake','ocelot','pain'],['tsel'],'The fight develops their rivalry while forcing Snake onto the cave route.');
 add('pain-fight','E','crisis','Boss encounter · The Pain','The Pain blocks Snake’s route through the flooded cave and attacks with hornets.','Snake defeats The Pain and continues toward Ponizovje.',['snake','pain'],['cobras'],'Water provides protection from the swarms. The encounter has a concrete local problem and resolution, which makes Event a useful classification.');
 add('granin-route','I','crisis','Locate Sokolov through Granin','Snake searches Graniny Gorki for Sokolov but finds Granin, a rival weapons designer.','Granin explains that Sokolov is at Groznyj Grad and gives Snake access to the route toward the fortress.',['snake','granin','sokolov'],['grad','shagohod'],'Granin resents the rejection of his walking-tank design in favor of Sokolov’s Shagohod. His resentment explains why he helps Snake.');
 add('fear-fight','E','crisis','Boss encounter · The Fear','The Fear ambushes Snake in the forest with a poisoned bolt, traps, and stealth camouflage.','Snake treats the poison, locates The Fear, and defeats him before continuing north.',['snake','fear'],['cobras','survival'],'The Fear moves between trees and needs food to recover stamina. His tactics make observation and survival equipment relevant to the fight.');
 add('end-fight','I','crisis','Boss encounter · Find The End','The End conceals himself across Sokrovenno and begins a sniper duel. Snake must locate him to proceed.','Snake finds and defeats The End, then continues toward the mountains.',['snake','end'],['cobras','survival'],'This outline follows the standard sniper duel. The game also allows The End to die before or outside that duel. Inquiry emphasizes locating the concealed opponent.');
 add('mountain-route','M','crisis','Cross Krasnogorje','Snake enters the mountain route leading to Groznyj Grad.','He reaches the underground approach to the fortress after meeting EVA for information.',['snake','eva'],['tsel','grad'],'The journey changes from forest cover to exposed mountain terrain. EVA supplies information needed for the infiltration.');
 add('fury-fight','E','crisis','Boss encounter · The Fury','The Fury blocks the underground tunnel with a flamethrower and jetpack.','Snake defeats The Fury and escapes the burning tunnel into Groznyj Grad.',['snake','fury'],['cobras','grad'],'The narrow passages restrict movement and make the spreading fire an immediate obstacle.');
 add('capture','I','crisis','Reach Sokolov inside Groznyj Grad','Sokolov is inside a restricted section of the fortress. Snake needs a disguise that will pass its guards.','Snake steals Raikov’s uniform and uses the mask to reach Sokolov. Volgin recognizes that he is an impostor and captures him.',['snake','sokolov','raikov','volgin','boss'],['grad'],'The disguise solves the access problem. It does not protect Snake once Volgin examines him.');
 add('torture','M','crisis','Escape captivity at Groznyj Grad','Snake is imprisoned and tortured after his disguise is exposed.','Snake leaves the prison through the sewer and jumps into the river while fleeing his pursuers.',['snake','volgin','boss','eva','ocelot','johnny'],['grad'],'Sokolov appears to be killed during the interrogation. Snake loses his right eye while intervening as Ocelot threatens EVA.');
 add('prison-escape','I','torture','Find a way out of the cell','Snake has lost his equipment and is locked in a cell guarded by Johnny.','Snake gets the cell open and reaches the sewer.',['snake','johnny','sorrow'],['grad'],'The game offers several escape methods. Johnny’s optional conversation and photograph can provide the door frequency; the outline does not require one particular method.');
 add('sorrow-fight','M','crisis','Boss encounter · The Sorrow’s river','After the river jump, Snake enters a supernatural encounter with The Sorrow and the dead.','Snake uses the revival pill to leave the encounter and wakes in the real river.',['snake','sorrow'],['cobras'],'The procession reflects people the player has killed. The Sorrow is already dead; this is not another opponent Snake kills. Milieu describes entering and leaving this altered environment.');
 add('resupply','I','crisis','Recover Snake’s equipment from EVA','Snake has escaped but lacks the equipment needed to finish the mission.','He meets EVA behind the waterfall. She returns his gear and supplies C3 for destroying the Shagohod.',['snake','eva'],['grad'],'The answer supplies both the missing equipment and the means to attack the weapon.');
 add('sabotage','E','crisis','Destroy the Shagohod','Snake returns to the weapons laboratory and plants C3 on its fuel tanks.','The laboratory explodes, but Volgin drives the Shagohod out. Snake and EVA finally disable it after a pursuit.',['snake','eva','volgin'],['grad','shagohod'],'The first attempt fails to destroy the weapon, so this Event remains open through the pursuit.');
 add('volgin-fight','E','sabotage','Boss encounter · Volgin','Volgin catches Snake during the sabotage and attacks him in the laboratory.','Snake defeats Volgin in the laboratory and escapes before the explosives detonate.',['snake','volgin','ocelot','boss'],['grad'],'Volgin uses electricity during the fight. Defeating him here does not end the Shagohod threat.');
 add('shagohod-fight','E','sabotage','Boss encounter · The Shagohod','Volgin pursues Snake and EVA in the Shagohod as they escape on a motorcycle.','They disable the Shagohod and fight Volgin outside it. A lightning strike ends his attack.',['snake','eva','volgin'],['shagohod'],'The pursuit includes an attempt to stop the vehicle at a bridge. The final confrontation resolves the weapon threat established in the sabotage thread.');
 add('escort','B','crisis','Help EVA after the crash','EVA is injured when the motorcycle crashes. Snake treats her and helps her reach the lake.','',['snake','eva'],['survival'],'This optional beat records the injury and the practical help Snake provides. It does not need a separate long-running story question.');
 add('flowers-scene','C','crisis','Boss encounter · Snake defeats The Boss','The Boss orders Snake to fight her at Rokovoj Bereg. He has been unable to defeat her in their earlier encounters.','Snake wins the fight and shoots her with the Patriot. He has surpassed his instructor and carried out the order to kill her.',['snake','boss'],['flowers','patriot','legacy'],'Before the fight, The Boss describes her history and her relationship with The Sorrow. Afterward she gives Snake the Legacy. Her true American assignment remains unknown to him.');
 add('aircraft-duel','E','jungle','Ocelot’s final challenge','Ocelot boards the escape aircraft and challenges Snake once more.','Their final contest ends, Ocelot leaves, and Snake and EVA continue their escape.',['snake','eva','ocelot'],['tsel'],'The confrontation follows The Boss’s death and precedes EVA’s recording.');
 add('award','B','loyalty','Snake receives the title Big Boss','The United States awards Snake the title Big Boss after the operation.','',['snake'],[],'This beat records the new title. The Character thread closes with the later visit to The Boss’s grave.');
 add('call','B','','Coda · Ocelot’s call','Ocelot reports to the CIA director. The call identifies him as ADAM and reveals that the Legacy recovery is incomplete.','',['ocelot'],['legacy'],'Snake does not hear this conversation. Its information belongs to the audience, not to Snake’s character state.');
 const gallery='https://www.spriters-resource.com/pc_computer/metalgearsoliddsnakeeater/asset/481808/';
 const people=[
 ['pain','The Pain','Cobra Unit · hornet control','ThePain','Controls hornets to attack and shield himself.','Blocks Snake in the flooded cave.'],
 ['fear','The Fear','Cobra Unit · ambush specialist','TheFear','Stealth camouflage, crossbows, traps, and rapid movement between trees.','Ambushes Snake after the meeting with Granin.'],
 ['end','The End','Cobra Unit · sniper','TheEnd','Concealment, tracking, and long-range tranquilizer fire.','Challenges Snake to a sniper duel in Sokrovenno.'],
 ['fury','The Fury','Cobra Unit · former cosmonaut','TheFury','Flamethrower, protective suit, and jetpack.','Blocks the underground route into Groznyj Grad.'],
 ['sorrow','The Sorrow','Deceased Cobra member · spirit medium','TheSorrow','Communicates with the dead and appears as a spirit.','Confronts Snake with the dead in the river encounter.'],
 ['johnny','Johnny','Prison guard · Groznyj Grad','Johnny','Guards Snake’s cell and brings him food.','Optional conversations reveal that he misses his family.']
 ];
 for(const [id,name,identity,file,ability,role] of people){const c={...W.character(name),id,identity,color:'green',portrait:img('delta/CharacterIcon_'+file+'.png'),notes:role};c.blocks=[['work',role],['capability',ability],['allegiance',id==='johnny'?'Groznyj Grad prison staff':'Cobra Unit']].map(([kind,text],i)=>({...W.block(kind,text),id:id+'-block-'+i,detail:'',pinned:i===0}));c.references=[ref(id+'-portrait','Delta Character Viewer portrait',gallery,'Game art © Konami; asset listing by vi7ual.')];p.characters.push(c);}
 p.characters.find(c=>c.id==='sorrow').notes='The Boss killed The Sorrow in 1962 under orders. They had been lovers and had a son. MGS3 provides clues connecting their son to Ocelot; Snake does not learn that identity here.';
 p.characters.find(c=>c.id==='boss').identity='FOX instructor · former Cobra Unit leader';
 p.connections.push({id:'boss-sorrow',a:'boss',b:'sorrow',label:'Former partners and parents',notes:'The Boss and The Sorrow were lovers and had a son. Orders forced them onto opposing sides, and she killed him in 1962.',color:'bone'});
 for(const id of ['pain','fear','end','fury'])p.connections.push({id:'boss-'+id,a:'boss',b:id,label:'Cobra Unit comrades',notes:'Served with The Boss in the Cobra Unit. Fights Snake during Operation Snake Eater.',color:'green'});
 p.id='mgs3-tutorial-v3';p.title='MGS3 · Detailed MICE outline';p.subtitle='Virtuous Mission and Operation Snake Eater · Full spoilers';
 require('./plain-language.cjs')(p);
};
