const {data}=require('./mgs3-project.cjs'),sample=data.projects[0];
const a=(action,id)=>`[data-action="${action}"]${id!==undefined?`[data-id="${id}"]`:''}`;
const goal=(text,setup,focus,check,extra={})=>({text,setup,focus,check,...extra});
const click=(action,id)=>({kind:'action',action,id});
const create=(entity,id,extra={})=>({kind:'create',entity,id,...extra});
const node=(id,type,parent,text)=>goal(text,{page:'outline',reveal:parent},a('quick-piece',type),create('node',id,{type,parent}),{drop:parent?`[data-node="${parent}"] > .node-children > .inside-drop` :'.outline-tail',sampleNode:id});
const titleNode=(id,type,parent,text)=>({...node(id,type,parent,text),nodeFields:['title']});
const field=(id,name,text,setup={})=>goal(text,{piece:id,...setup},`[data-inline="node"][data-id="${id}"][data-field="${name}"]`,{kind:'demo-node',entity:'node',id,field:name},{sampleNode:id,nodeFields:[name]});
const demo=(form,fields,selects={})=>({form,fields,selects});
const inspect=(id,text)=>goal(text,{piece:id,select:false},a('select-node',id),click('select-node',id));
const lessons=[
['build-c','Introduce the person who changes','Let’s introduce Naked Snake. A Character thread promises that the person we meet will be changed by what happens. MICE gives us a language for making narrative promises and paying them off.','Each thread has an opening and a closing. Nested threads develop promises inside a larger one. We can plan Snake’s destination now while leaving the mission outcomes unwritten.',[
 titleNode('loyalty','C','','Drag Character into the empty outline. Watch “Snake becomes Big Boss” write itself in. Read or edit the title, then press Next. Your own wording is always kept.'),
 field('loyalty','opening','Watch the opening write in: Snake trusts The Boss, his former instructor. This establishes the relationship the story will test.'),
 field('loyalty','closing','Watch the closing write in: Snake has killed his mentor and learned her true orders. This is the destination of his Character thread; the missions will develop how he gets there.')]],
['build-e','Give Snake a rescue objective','What will put Snake under pressure? Sokolov wants to defect, and Snake must extract him. Add an Event inside the Character thread so this mission contributes to Snake’s larger story.','An Event opens with a problem and closes when it is resolved, successfully or unsuccessfully. The opening promises an outcome. Leave that outcome blank until we reach it.',[
 titleNode('defection','E','loyalty','Drag Event inside Snake’s Character thread. “Defection of Sokolov” writes in automatically. Read or edit it before continuing.'),
 field('defection','opening','Watch the opening write in: Sokolov wants to leave, and Snake must get him out. We have introduced the rescue problem without deciding its outcome here.')]],
['build-m','Enter the mission’s setting','To attempt that rescue, Snake must enter Soviet territory. Nest Virtuous Mission inside the defection Event: this visit is part of the attempt to get Sokolov out.','A Milieu thread opens with entry into a place or situation and closes with departure. Its boundaries contain the experiences of that visit. We will write the departure later.',[
 titleNode('drop','M','defection','Drag Milieu inside Defection of Sokolov. Watch “Virtuous Mission” write in, then continue when you are ready.'),
 field('drop','opening','Watch the opening write in: Snake parachutes into Tselinoyarsk. Entering the setting opens this Milieu; leaving it will close the promise.')]],
['build-i','Raise a question within the mission','The Boss joins the operation. Let’s make the uncertainty explicit: why is Snake’s former instructor here? Nest that question inside Virtuous Mission.','An Inquiry opens a question and closes with an answer. That answer may be limited by what a character knows. The question belongs inside this visit because Snake reaches his first answer during it.',[
 titleNode('mission-question','I','drop','Drag Inquiry inside Virtuous Mission. The question “Why did The Boss join this mission?” writes in automatically. Read or edit it before continuing.'),
 field('mission-question','opening','Watch the opening question write in. Leave its closing blank: we have promised an explanation, but Snake has not reached one yet.')]],
['make-person','Create Snake in Characters','The C card describes a story thread. The Characters panel stores the person who participates in it. Create Snake there now.','A character can appear in many threads. Their profile and changes stay connected to the same person, instead of becoming separate copies on every card.',[
 goal('Open Characters, then click New character. Watch the sample write in, review the name and role, then click Create character. Your own wording works too.',{page:'characters'},a('new-character'),create('character','snake'),{demo:demo('character',{name:'Naked Snake',identity:'FOX operative and former student of The Boss.'})})]],
['add-want','Give Snake a starting objective','A name alone does not explain what drives a person. Add a Want block for the rescue objective.','Building blocks separate useful traits: Want, Belief, Value, possessions, skills, and more. Add only what helps you develop this character.',[
 goal('Click Add a building block, choose Want, then watch the objective write in. Read or revise the objective before saving.',{character:'snake'},a('add-block'),create('block','snake-want',{character:'snake',blockKind:'want'}),{demo:demo('block',{text:'Complete the mission.'}),picker:'want'})]],
['revise-want','Make the objective specific','“Complete the mission” is too general to guide this part of the story. Replace it with a concrete rescue objective.','Editing a starting block changes the baseline profile. Recording a change at a story moment is different: it preserves the baseline and adds what becomes true later.',[
 goal('Click the Want block. Replace “Complete the mission.” with “Rescue Sokolov.” and click Save piece.',{character:'snake'},a('edit-block','snake-want'),{kind:'edit',entity:'block',id:'snake-want',character:'snake',field:'text'})]],
['cast-snake','Put the character in the rescue','Return to the rescue Event and attach Snake. His profile can now be inspected from the thread.','The outline tells you what happens; the cast links tell you who participates. A character link refers back to the Characters panel and reflects changes at this point in the story.',[
 goal('Drag Naked Snake from the cast onto the rescue thread. Or click Add someone, tick Naked Snake, and keep the links.',{piece:'defection'},a('cast','defection'),{kind:'contains',entity:'node',id:'defection',field:'cast',value:'snake'})]],
['bridge-change','Close the first mission’s promises','Skip ahead: the tutorial adds the rest of Virtuous Mission, The Boss, and more starting blocks for Snake. At the bridge she attacks him; he concludes that she has defected.','Record a change to Snake’s Belief at the bridge’s closing. His starting trust stays intact. The Boss’s real allegiance is separate from what Snake believes about her.',[
 field('mission-question','closing','First close the Inquiry. Snake reads The Boss’s actions as a defection. This answers his immediate question, although the full truth remains hidden.',{stage:'bridge'}),
 field('drop','closing','Next close the Milieu. Snake leaves Soviet territory injured. His departure ends this visit, even though the rescue has failed.'),
 field('defection','closing','Now close the Event: Sokolov is unable to defect. A promise needs an outcome, not necessarily success. The failed rescue creates the need for another mission.'),
 goal('Click the closing change button on the bridge thread, then choose Snake’s Belief. Watch the sample write in, review the new belief and reason, and keep the change.',{stage:'bridge',piece:'bridge'},a('show-changes','bridge'),{kind:'timed-change',character:'snake',block:'snake-belief',at:'bridge:close'},{picker:'snake-belief',demo:demo('change',{text:'The Boss is working against my mission.',reason:'The Boss attacks Snake and takes Sokolov, so he believes she has defected.'},{at:'bridge:close'})})]],
['timeline','Inspect the same person at two times','The change now belongs to a specific moment. Use Snake’s timeline to compare what is true before and after it.','Moving through the timeline recalculates the profile. Editing the starting block would rewrite the baseline; adding a timed change lets both states exist in the same story.',[
 goal('Click the bridge’s opening and read Snake’s Belief block.',{character:'snake'},a('time','bridge:open'),click('time','bridge:open')),
 goal('Click the bridge’s closing. Confirm that his belief has changed while his other blocks remain available.',{},a('time','bridge:close'),click('time','bridge:close'))]],
['world-object','Create the weapon in World','Open a new Milieu for Operation Snake Eater. Its new orders follow the failed rescue. The Shagohod is an object in the world that gives the mission a concrete target.','World stores reusable places, objects, rules, groups, and facts. The entry describes the weapon; an Event thread describes the attempt to destroy it.',[
 titleNode('jungle','M','loyalty','Drag a new Milieu inside Snake’s Character thread. Name this new visit Operation Snake Eater; the first visit is already closed.'),
 field('jungle','opening','Write the new opening: Snake returns with orders to rescue Sokolov, destroy the Shagohod, and kill Volgin and The Boss. This visit makes a new promise.'),
 goal('Open World and click Add to the world. Watch the sample write in, review the Shagohod entry, then save it.',{stage:'orders',page:'world'},a('new-world'),create('world','shagohod'),{demo:demo('world',{name:'The Shagohod',notes:'Sokolov’s nuclear weapon platform. Snake is ordered to destroy it during Operation Snake Eater.'},{type:'object'})})]],
['world-link','Connect a Milieu to its setting','The Shagohod belongs to the mission. Tselinoyarsk is the place Snake enters. Link them without duplicating their descriptions.','Milieu cards have an optional Setting / culture row. Link an existing entry or create one there. A place or culture can serve many visits; linking it is useful, never compulsory.',[
 goal('In the mission’s Linked world entries, click + Link. Select The Shagohod and keep the links.',{piece:'crisis'},a('link-world','crisis'),{kind:'contains',entity:'node',id:'crisis',field:'worldIds',value:'shagohod'}),
 goal('On Operation Snake Eater, use Setting / culture → Link, then New setting. Press Insert sample and save Tselinoyarsk; the new place links itself to this Milieu.',{piece:'jungle'},a('milieu-link','jungle'),create('world','tsel'),{milieuFor:'jungle',demo:demo('world',{name:'Tselinoyarsk',notes:'Soviet territory where both missions take place. The route includes forests, caves, mountains, and military facilities.'},{type:'place'})}),
 goal('Open Tselinoyarsk from the Milieu’s Setting / culture row. This is the same entry you can reuse on any other visit.',{piece:'jungle'},a('edit-world','tsel'),click('edit-world','tsel'))]],
['connection','Describe the relationship behind the conflict','Snake and The Boss share training and trust. Their connection explains why the order to kill her affects him differently from the other mission objectives.','Connections hold the relationship between two characters. They provide context for the outline; timed character changes still record exactly when a person’s belief or circumstances change.',[
 goal('Open Connections and click Connect two people. Watch the sample write in, review the relationship, then click Connect them.',{page:'connections'},a('new-connection'),create('connection','snake-boss'),{demo:demo('connection',{label:'Student and mentor',notes:'The Boss trained Snake. Her apparent defection forces him to fight the person he trusted as his instructor.'},{a:'snake',b:'boss'})})]],
['add-beat','Add a smaller development','Skip ahead: the Cobra encounters, captivity, and Shagohod pursuit appear with their cast, world links, and character changes. Add the moment where Snake helps the injured EVA after the crash.','An optional beat develops an existing thread without needing its own opening and closing question. Helping EVA reverses their earlier dependence: he now provides the practical help.',[
 node('escort','B','crisis','Add an Optional beat inside the mission Event. Press Insert sample, then read or revise the crash and escort description.')]],
['write','Draft directly from an outline piece','The outline gives you the event’s purpose. Write mode gives you space to draft how it plays out. Any thread or beat can hold prose.','Insert sample offers a short original staging example. It is not game dialogue. Outline wording, prose, and linked characters belong to the same piece.',[
 goal('Click Write this piece for the escort beat, then Insert sample. Change or add one detail and click outside to save. The guide waits while you write.',{piece:'escort'},a('write-node','escort'),{kind:'edit',entity:'node',id:'escort',field:'prose'},{inlineDemo:{id:'escort',field:'prose',text:'Snake checks EVA’s wound and helps her stand. He waits while she finds her footing, then supports her as they continue toward the lake.'}})]],
['move','Control the order of events','Add the final encounter, then place the escort immediately before it. Moving an entire thread carries its nested pieces with it.','Drag handles move pieces. Before/after drop positions change sequence; dropping inside a thread changes nesting. The Move menu provides the same control without dragging.',[
 goal('Use the escort beat’s handle to move it before the final Boss encounter. Or open the handle’s menu, choose that encounter and Before this piece, then move it.',{stage:'finalfight',piece:'escort'},a('move-node','escort'),{kind:'before',id:'escort',anchor:'flowers-scene',parent:'crisis'})]],
['archive','Try removing a piece','Temporarily archive the escort beat. This lets you see how the outline reads without that development.','Archive keeps the piece and its attached changes available for restoration. It is useful for trying a structural cut without immediately deleting the material.',[
 goal('Click Archive on the escort beat, or drag its handle to the tray’s Archive target.',{piece:'escort'},a('archive-node','escort'),{kind:'archived',id:'escort'}),
 goal('Click Undo in the top bar. The beat returns with its prose.',{},a('undo'),{kind:'restored',id:'escort'}),
 goal('Click Redo to apply the cut again. Next you will restore it through Archive.',{},a('redo'),{kind:'archived',id:'escort'})]],
['restore','Bring the cut back','The escort matters because it shows Snake helping EVA after relying on her. Restore it to keep that development.','Archive is another view of the same project. Restoration returns the material and its attached data; check its placement in the outline after restoring.',[
 goal('Open Archive. Find Help EVA after the crash and click Restore.',{page:'archive'},'.archive-row:has(h3) [data-action="restore"]',{kind:'restored',id:'escort'})]],
['plots','Make a plot view without copying the story','Use an A plot to follow the main mission. Master plot continues to show every piece, including material outside this view.','A, B, C, and later plots are labels for views, not MICE types. One piece can belong to several plots. Editing a shared piece changes it in Master and every assigned view.',[
 goal('Click Manage plots, then Add plot. Watch the sample write in, review the A plot name, and save it.',{page:'outline'},a('manage-plots'),{kind:'plot-created'},{demo:demo('plot',{label:'A',title:'The mission'})}),
 goal('Open Choose plot views for the mission thread. Tick A plot, keep the nested-pieces option, and save.',{piece:'crisis'},a('plot-membership','crisis'),{kind:'plot-assigned',id:'crisis'}),
 goal('Click A plot to see its pieces, then return to Master plot for the whole story.',{page:'outline'},'.plot-toolbar nav',{kind:'plot-cycle'})]],
['reference','Keep a reference beside the moment','Add a staging reference to the final fight. A reference can hold a picture, a link, or a note about a choice you want to remember.','Reference notes support drafting without changing the story’s events. Keep interpretation distinct from facts, especially when explaining what Snake privately thinks.',[
 goal('Open Pictures & references on the final fight, then add a reference. Watch the sample write in, review the staging note, and save. An image is optional.',{piece:'flowers-scene'},a('references','flowers-scene'),{kind:'reference',id:'flowers-scene'},{demo:demo('reference',{title:'Mentor and student',note:'Use their shared training to connect the final fight with the earlier encounters where The Boss defeats Snake.'})})]],
['finish-story','Complete the story and inspect the reveal','Skip ahead: the escape, EVA’s recording, the award, and Ocelot’s coda complete the outline. The remaining cast, world entries, relationships, and timed changes are filled in while your edits are kept.','The missions end before Snake learns The Boss’s actual orders. That delayed answer changes how he understands what he has already done. Ocelot’s coda adds audience knowledge that Snake does not receive.',[
 goal('Open the Inquiry’s changes and compare Snake’s belief before and after EVA’s recording.',{stage:'complete',piece:'inquiry'},'.mini-change[data-id="inquiry"]',click('show-changes','inquiry')),
 inspect('call','Open Ocelot’s coda and read the audience-only notes. It sits outside Snake’s completed Character thread.')]],
['keep-work','Keep your finished project','You have built threads, created and linked characters, tracked change, used World and Connections, drafted prose, moved and restored a piece, and made a plot view.','Your work saves in this browser. A backup keeps the editable project available for import. Save a copy also offers a readable export for sharing. You can keep editing after the tutorial ends.',[
 goal('Click Save a copy, then choose the editable JSON backup. Keep the downloaded file; it contains your complete project.',{page:'outline'},a('export'),click('export-json'))]]
];
lessons[13][4][0].setup.stage='middle';
module.exports=lessons.map(([id,title,intro,why,goals],i)=>({id,title,intro,why,group:i<4?'Build MICE':i<10?'Build characters':i<13?'Connect the story':i<18?'Develop and revise':'Finish and keep',tag:`Stage ${i+1}`,target:goals[0].setup,steps:goals.map(g=>g.text),look:why,goals}));
