// Keep browser/portable validation and the server validator identical.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { parse } from 'acorn';
const html = readFileSync('index.html', 'utf8');
const names = ['KINDS','PRESSURES','TONES','ENTITY_TYPES','ARC_EFFECTS','STORY_RANGE','SCENE_KINDS','SCENE_FIELDS','OUTCOMES','SCENE_ROLES','CONTEXTS','CounterplotStory','CounterplotEnsemble','clone','dependencies','validateWorkspace'];
const found = new Map();
const hashes = [];
for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
  if (/type=["']application\/json/i.test(match[1])) continue;
  const source = match[2]; hashes.push("'sha256-" + createHash('sha256').update(source).digest('base64') + "'");
  const visit = node => {
    if (!node || typeof node !== 'object') return;
    if (node.type === 'VariableDeclarator' && names.includes(node.id?.name)) found.set(node.id.name, 'const ' + source.slice(node.start, node.end) + ';');
    if (node.type === 'FunctionDeclaration' && names.includes(node.id?.name)) found.set(node.id.name, source.slice(node.start, node.end));
    for (const value of Object.values(node)) if (Array.isArray(value)) value.forEach(visit); else if (value?.type) visit(value);
  };
  visit(parse(source, { ecmaVersion: 'latest' }));
}
for (const name of names) if (!found.has(name)) throw Error('Missing validator dependency: ' + name);
const outputs = {
  'functions/_lib/workspace-validation.js': '// Generated by scripts/generate-runtime.mjs. Edit the browser source, then regenerate.\n' + names.map(n => found.get(n)).join('\n') + '\nexport { validateWorkspace };\n',
  '_headers': '/*\n  X-Frame-Options: DENY\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Content-Type-Options: nosniff\n  Content-Security-Policy: default-src \'self\'; script-src ' + hashes.join(' ') + "; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'\n"
};
for (const [path, content] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) { if (readFileSync(path, 'utf8') !== content) throw Error(path + ' is stale; run npm run generate'); }
  else writeFileSync(path, content);
}
